In [1]:
from sentence_transformers import SentenceTransformer
import torch
# Load embedding model
device = "cuda" if torch.cuda.is_available() else "cpu"
model = SentenceTransformer("google/embeddinggemma-300m", device=device)

def create_embedding(texts):
    if type(texts) == list: # the input param is a list contains text chunks
        embeddings = model.encode(texts)
        return embeddings
    elif type(texts) == str: # just one text chunk
        embedding = model.encode([texts])
        return embedding
    else:
        raise ValueError("The texts paramters should be str or list[str]")

print(device)

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

cuda

In [2]:
import os
dir_path = os.getcwd()
print("The directory of this script is:", dir_path)
root_path = os.path.dirname(dir_path)
print("The root directory is:", root_path)

The directory of this script is: d:\Documents\GitHub\NodeRAG\testing
The root directory is: d:\Documents\GitHub\NodeRAG

In [3]:
#LLM api call
from google import genai
with open(f"{root_path}/API_KEY.txt", "r", encoding="utf-8") as f:
    API_KEY = f.read()

def call_gemini(text):
    client = genai.Client(api_key = API_KEY)
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=text
    )
    return response.text, response.usage_metadata.total_token_count

In [4]:
import sys
import numpy as np
sys.path.append(root_path)
from testing.metrics.faithfulness import compute_faithfulness #Detect hallucinations: Measures how much the LLM answer is based on the retrieved context
"""
question: str,
answer: str,
contexts: List[str],
call_gemini,
max_retries: int = 5
"""
from testing.metrics.context_recall import compute_context_recall #Evaluate retrieval coverage: Measures how much of the reference (ground-truth) answer is supported by the retrieved context.
"""
question: str,
contexts: List[str],
reference_answer: str,
call_gemini,
max_retries: int = 5
"""
from testing.metrics.coverage import compute_coverage #Measures how completely a model’s response covers the factual content of a reference (ground-truth) answer.
"""
question: str,
reference: str,
response: str,
call_gemini,
max_retries: int = 5
"""
from testing.metrics.rouge import compute_rouge
#Calculate F-1 of lexical overlap by LCS: longest common subsequence (in terms of word order, adjacency not required)
#Precision = len(LCS) / len(Answer)
#Recall = len(LCS) / len(Ref)
"""
answer: str,
ground_truth: str,
rouge_type: str = "rougeL",
mode: str = "fmeasure"
"""
from testing.metrics.accuracy import compute_answer_accuracy
"""
question: str,
answer: str,
ground_truth: str,
call_gemini,
create_embedding,
weights: List[float] = [0.75, 0.25],
beta: float = 1.0,
max_retries: int = 5
"""
print("Import evaluation functions")

Import evaluation functions

In [5]:
import pandas as pd
medical_questions_answered_loaded = pd.read_parquet("data/normal_rag_answer.parquet")
relevant_questions = medical_questions_answered_loaded[medical_questions_answered_loaded["question_type"] == "Complex Reasoning"]
question_ids = relevant_questions['id'].to_list()
relevant_questions

,id,source,question,answer,question_type,evidence,evidence_relations,LLM_answer,LLM_context,LLM_tokens
0,Medical-604c9d44,Medical,Why is a patient with fair skin and a history ...,Because both fair skin and immune suppression ...,Complex Reasoning,Fair skin is an independent risk factor for ba...,"Fair skin, light hair, and light eye color inc...",A patient with fair skin is at a higher risk f...,Here are distinct categories of high-level inf...,2727.0
1,Medical-df366063,Medical,If a patient presents with a shiny bump on the...,"A medical and family history, physical and ski...",Complex Reasoning,A medical and family history should be perform...,BCC presents as shiny bumps; BCC most commonly...,If a patient presents with a shiny bump on the...,Basal cell skin cancer can affect anyone but i...,2838.0
2,Medical-0a90f1f2,Medical,How does the management of recurrent basal cel...,Management of recurrence depends on risk and r...,Complex Reasoning,Management of recurrent basal cell carcinoma d...,Recurrence refers to BCC returning to the orig...,The provided text defines recurrence for basal...,"The deeper a tumor has invaded into the skin, ...",1976.0
3,Medical-831bb1e6,Medical,Which combination of risk factors should promp...,"A combination of older age, fair skin, and fam...",Complex Reasoning,Older age is a risk factor for basal cell carc...,Older age is associated with higher risk of BC...,The retrieved context identifies several risk ...,Basal cell skin cancer can affect anyone but i...,3321.0
4,Medical-01e3a9ea,Medical,Why might a patient with a shiny bump and a hi...,Because radiation therapy is a risk factor for...,Complex Reasoning,A shiny bump can be a symptom of basal cell ca...,Radiation therapy is a risk factor for BCC; BC...,A patient with a shiny bump would typically un...,If blastic plasmacytoid dendritic cell neoplas...,1368.0
...,...,...,...,...,...,...,...,...,...,...
504,Medical-1eda4787,Medical,Which patients with breast cancer should recei...,All patients of reproductive potential should ...,Complex Reasoning,All patients of reproductive potential should ...,Fertility preservation should be discussed bef...,Patients with breast cancer who wish to have c...,Patients who wish to have children after cance...,1918.0
505,Medical-24f2e8ea,Medical,How does the presence of HER2 positivity alter...,HER2 positivity adds HER2-targeted therapy to ...,Complex Reasoning,HER2 positivity adds HER2-targeted therapy to ...,HER2-targeted therapy is used for HER2-positiv...,The presence of HER2 positivity in invasive br...,HER2 is a protein involved in normal cell grow...,1042.0
506,Medical-d1a87cb4,Medical,What combination of clinical findings and diag...,Symptoms like bone pain or neurological sympto...,Complex Reasoning,Symptoms like bone pain or neurological sympto...,Metastatic breast cancer (MBC) is breast cance...,"Metastatic breast cancer, also known as Stage ...",Stage 4 cancer indicates that the disease has ...,1808.0
507,Medical-311d66d6,Medical,Which risk factors should be evaluated in a pa...,"Family history, BRCA1/2 mutations, and assigne...",Complex Reasoning,Family history should be evaluated as a risk f...,"Risk factors include family history, BRCA muta...",When a patient presents with a new breast lump...,"A physical exam, including a breast exam, will...",3410.0
508,Medical-ac117ebf,Medical,Why is a biopsy essential in both the diagnosi...,Biopsy is essential for definitive diagnosis a...,Complex Reasoning,A biopsy is essential for definitive diagnosis...,Biopsy is required for definitive diagnosis an...,A biopsy is essential because it confirms a ca...,This is similar to the sonogram used for pregn...,1784.0

In [6]:
try:
    medical_questions_evaluated = pd.read_parquet("data/evaluations/normal_rag_evaluated.parquet")
    medical_questions_evaluated = (
        medical_questions_evaluated
        .set_index("qid")
        .to_dict(orient="index")
    )
except:
    medical_questions_evaluated = {}


medical_questions_evaluated

{'Medical-604c9d44': {'accuracy': 0.7840551137432007,
  'rouge': 0.16129032258064516,
  'context_recall': 1.0,
  'tokens': 6680},
 'Medical-df366063': {'accuracy': 0.6993219851989176,
  'rouge': 0.18421052631578946,
  'context_recall': 1.0,
  'tokens': 8401},
 'Medical-0a90f1f2': {'accuracy': 0.7039262353929487,
  'rouge': 0.09433962264150943,
  'context_recall': 1.0,
  'tokens': 9721},
 'Medical-831bb1e6': {'accuracy': 0.4881982803028321,
  'rouge': 0.24489795918367346,
  'context_recall': 1.0,
  'tokens': 12291},
 'Medical-01e3a9ea': {'accuracy': 0.5165452986475643,
  'rouge': 0.1764705882352941,
  'context_recall': 0.0,
  'tokens': 5392},
 'Medical-c69c2732': {'accuracy': 0.6595893024948254,
  'rouge': 0.14084507042253522,
  'context_recall': 1.0,
  'tokens': 6553},
 'Medical-f034d77d': {'accuracy': 0.5630378631125551,
  'rouge': 0.13186813186813187,
  'context_recall': 1.0,
  'tokens': 9813},
 'Medical-1eab8fa2': {'accuracy': 0.5205341457945618,
  'rouge': 0.24390243902439024,
  'context_recall': 1.0,
  'tokens': 11906},
 'Medical-14016ce3': {'accuracy': 0.187298983335495,
  'rouge': 0.1702127659574468,
  'context_recall': 0.0,
  'tokens': 3328},
 'Medical-5e530443': {'accuracy': 0.20787547528743744,
  'rouge': 0.2926829268292683,
  'context_recall': 0.0,
  'tokens': 7029},
 'Medical-c8dd3e29': {'accuracy': 0.18885651230812073,
  'rouge': 0.15384615384615385,
  'context_recall': 0.0,
  'tokens': 5608},
 'Medical-a9a52704': {'accuracy': 0.8521297956664969,
  'rouge': 0.42857142857142866,
  'context_recall': 1.0,
  'tokens': 7057},
 'Medical-346b12e8': {'accuracy': 0.7127497493739252,
  'rouge': 0.1408450704225352,
  'context_recall': 1.0,
  'tokens': 6689},
 'Medical-8ff5dd5a': {'accuracy': 0.22511957585811615,
  'rouge': 0.28571428571428575,
  'context_recall': 0.0,
  'tokens': 4360},
 'Medical-322bb52d': {'accuracy': 0.7576541900119141,
  'rouge': 0.19672131147540986,
  'context_recall': 1.0,
  'tokens': 10947},
 'Medical-35fee661': {'accuracy': 0.4563199132264226,
  'rouge': 0.19672131147540983,
  'context_recall': 1.0,
  'tokens': 7356},
 'Medical-f473bcb0': {'accuracy': 0.9753583668912476,
  'rouge': 0.392156862745098,
  'context_recall': 1.0,
  'tokens': 4420},
 'Medical-f3af6f24': {'accuracy': 0.5135557382818874,
  'rouge': 0.24489795918367344,
  'context_recall': 0.5,
  'tokens': 6362},
 'Medical-ade4b34a': {'accuracy': 0.5481893320433902,
  'rouge': 0.23880597014925373,
  'context_recall': 0.0,
  'tokens': 7664},
 'Medical-ade95016': {'accuracy': 0.6073125600439819,
  'rouge': 0.1935483870967742,
  'context_recall': 1.0,
  'tokens': 5802},
 'Medical-8435c9f6': {'accuracy': 0.7159355580325251,
  'rouge': 0.1971830985915493,
  'context_recall': 1.0,
  'tokens': 6267},
 'Medical-23e6b6df': {'accuracy': 0.6551669047982934,
  'rouge': 0.23255813953488375,
  'context_recall': 0.5,
  'tokens': 8137},
 'Medical-4744dfa7': {'accuracy': 0.19919320940971375,
  'rouge': 0.18666666666666668,
  'context_recall': 0.0,
  'tokens': 4889},
 'Medical-59ea36ca': {'accuracy': 0.1610906571149826,
  'rouge': 0.061538461538461535,
  'context_recall': 0.0,
  'tokens': 6051},
 'Medical-4124f00f': {'accuracy': 0.310792237490921,
  'rouge': 0.07894736842105264,
  'context_recall': 1.0,
  'tokens': 7837},
 'Medical-ed26b623': {'accuracy': 0.47860710997455136,
  'rouge': 0.18666666666666668,
  'context_recall': 0.0,
  'tokens': 10457},
 'Medical-fbc9e7ec': {'accuracy': 0.5077159901015567,
  'rouge': 0.10526315789473682,
  'context_recall': 0.0,
  'tokens': 6554},
 'Medical-9a34e14c': {'accuracy': 0.5952086150200897,
  'rouge': 0.25,
  'context_recall': 1.0,
  'tokens': 7040},
 'Medical-bfe2b31f': {'accuracy': 0.8051181494589668,
  'rouge': 0.163265306122449,
  'context_recall': 1.0,
  'tokens': 7853},
 'Medical-b6fbf092': {'accuracy': 0.5815307348570766,
  'rouge': 0.14583333333333334,
  'context_recall': 0.0,
  'tokens': 8703},
 'Medical-55898188': {'accuracy': 0.8253131866023827,
  'rouge': 0.14432989690721648,
  'context_recall': 1.0,
  'tokens': 7923},
 'Medical-8b99b755': {'accuracy': 0.5502071505774597,
  'rouge': 0.1958041958041958,
  'context_recall': 0.0,
  'tokens': 9536},
 'Medical-e0f29bbd': {'accuracy': 0.686609399278195,
  'rouge': 0.2535211267605634,
  'context_recall': 0.0,
  'tokens': 8448},
 'Medical-55f0c0e2': {'accuracy': 0.793534040411206,
  'rouge': 0.2947368421052632,
  'context_recall': 1.0,
  'tokens': 12585},
 'Medical-8407a0ab': {'accuracy': 0.6431485520452074,
  'rouge': 0.13333333333333333,
  'context_recall': 1.0,
  'tokens': 7012},
 'Medical-7b4429ac': {'accuracy': 0.6372799006012796,
  'rouge': 0.14193548387096774,
  'context_recall': 0.0,
  'tokens': 13731},
 'Medical-6d12f4ff': {'accuracy': 0.45748971398478444,
  'rouge': 0.08955223880597016,
  'context_recall': 1.0,
  'tokens': 8580},
 'Medical-baed6d13': {'accuracy': 0.7534585016179264,
  'rouge': 0.2298850574712644,
  'context_recall': 1.0,
  'tokens': 9550},
 'Medical-eb7624ca': {'accuracy': 0.49150013107383334,
  'rouge': 0.1951219512195122,
  'context_recall': 1.0,
  'tokens': 10901},
 'Medical-0a6379ff': {'accuracy': 0.5900655984409791,
  'rouge': 0.1764705882352941,
  'context_recall': 0.0,
  'tokens': 6670},
 'Medical-462ecc23': {'accuracy': 0.5209130227192432,
  'rouge': 0.21686746987951808,
  'context_recall': 1.0,
  'tokens': 8767},
 'Medical-2782702e': {'accuracy': 0.43122510395463753,
  'rouge': 0.17391304347826086,
  'context_recall': 0.0,
  'tokens': 5490},
 'Medical-f978cb28': {'accuracy': 0.5183001935122025,
  'rouge': 0.2153846153846154,
  'context_recall': 1.0,
  'tokens': 5543},
 'Medical-4f5a8531': {'accuracy': 0.7770873009666351,
  'rouge': 0.15384615384615383,
  'context_recall': 1.0,
  'tokens': 5140},
 'Medical-db5aa2e3': {'accuracy': 0.8634034479816367,
  'rouge': 0.3050847457627119,
  'context_recall': 0.0,
  'tokens': 6615},
 'Medical-193a4b7f': {'accuracy': 0.5851663648519684,
  'rouge': 0.509090909090909,
  'context_recall': 0.0,
  'tokens': 6087},
 'Medical-e9ac42f1': {'accuracy': 0.8268290519114356,
  'rouge': 0.3508771929824561,
  'context_recall': 1.0,
  'tokens': 4583},
 'Medical-78897235': {'accuracy': 0.19933760166168213,
  'rouge': 0.16666666666666663,
  'context_recall': 0.0,
  'tokens': 7486},
 'Medical-33494794': {'accuracy': 0.1908172369003296,
  'rouge': 0.1568627450980392,
  'context_recall': 0.0,
  'tokens': 5342},
 'Medical-a7826934': {'accuracy': 0.9332640889356171,
  'rouge': 0.31884057971014496,
  'context_recall': 1.0,
  'tokens': 10060},
 'Medical-50bafb57': {'accuracy': 0.5059831171807859,
  'rouge': 0.21333333333333335,
  'context_recall': 1.0,
  'tokens': 10374},
 'Medical-24373ebe': {'accuracy': 0.5992525517495209,
  'rouge': 0.21538461538461537,
  'context_recall': 1.0,
  'tokens': 9135},
 'Medical-9528082d': {'accuracy': 0.8007389664209963,
  'rouge': 0.15384615384615383,
  'context_recall': 1.0,
  'tokens': 8626},
 'Medical-8b16a7bd': {'accuracy': 0.8634032691768861,
  'rouge': 0.3125,
  'context_recall': 1.0,
  'tokens': 9484},
 'Medical-4fe06961': {'accuracy': 0.8325366734978374,
  'rouge': 0.273972602739726,
  'context_recall': 0.0,
  'tokens': 9701},
 'Medical-41b1601a': {'accuracy': 0.44050261373704935,
  'rouge': 0.11111111111111109,
  'context_recall': 0.0,
  'tokens': 6569},
 'Medical-38fe5331': {'accuracy': 0.6046968102080139,
  'rouge': 0.25396825396825395,
  'context_recall': 1.0,
  'tokens': 6477},
 'Medical-4987de7f': {'accuracy': 0.4960280239102062,
  'rouge': 0.12244897959183672,
  'context_recall': 0.0,
  'tokens': 5149},
 'Medical-c2ead218': {'accuracy': 0.6032822280653458,
  'rouge': 0.3157894736842105,
  'context_recall': 0.0,
  'tokens': 5498},
 'Medical-4d01de98': {'accuracy': 0.5866847633971741,
  'rouge': 0.30985915492957744,
  'context_recall': 1.0,
  'tokens': 9609},
 'Medical-34a9155d': {'accuracy': 0.46405148502935384,
  'rouge': 0.15584415584415584,
  'context_recall': 1.0,
  'tokens': 8150},
 'Medical-b7e4be0e': {'accuracy': 0.40097892280408937,
  'rouge': 0.15584415584415584,
  'context_recall': 0.0,
  'tokens': 6329},
 'Medical-96bb3762': {'accuracy': 0.9018994370577774,
  'rouge': 0.2765957446808511,
  'context_recall': 1.0,
  'tokens': 5929},
 'Medical-7ea7ec68': {'accuracy': 0.8899928281186066,
  'rouge': 0.19999999999999998,
  'context_recall': 0.0,
  'tokens': 10088},
 'Medical-e7d1cd1c': {'accuracy': 0.7240918576217377,
  'rouge': 0.3478260869565218,
  'context_recall': 1.0,
  'tokens': 4507},
 'Medical-c7c59020': {'accuracy': 0.6011162399800354,
  'rouge': 0.24324324324324323,
  'context_recall': 1.0,
  'tokens': 6374},
 'Medical-ee49f3e8': {'accuracy': 0.8936492899535141,
  'rouge': 0.2191780821917808,
  'context_recall': 1.0,
  'tokens': 6272},
 'Medical-b77d8e3d': {'accuracy': 0.8048125415440421,
  'rouge': 0.15789473684210525,
  'context_recall': 1.0,
  'tokens': 5588},
 'Medical-6fb8996b': {'accuracy': 0.47234824295228983,
  'rouge': 0.1923076923076923,
  'context_recall': 1.0,
  'tokens': 4824},
 'Medical-edc3c6eb': {'accuracy': 0.9695851802200928,
  'rouge': 0.29508196721311475,
  'context_recall': 1.0,
  'tokens': 5364},
 'Medical-f3048835': {'accuracy': 0.7359181046041456,
  'rouge': 0.24324324324324326,
  'context_recall': 1.0,
  'tokens': 9347},
 'Medical-f79d978d': {'accuracy': 0.6887872195734794,
  'rouge': 0.2150537634408602,
  'context_recall': 1.0,
  'tokens': 9164},
 'Medical-47504b64': {'accuracy': 0.41269922253188474,
  'rouge': 0.21951219512195122,
  'context_recall': 1.0,
  'tokens': 7462},
 'Medical-328006b7': {'accuracy': 0.4212546177905445,
  'rouge': 0.17142857142857143,
  'context_recall': 0.0,
  'tokens': 7221},
 'Medical-659d7c0a': {'accuracy': 0.9053020293416725,
  'rouge': 0.30303030303030304,
  'context_recall': 1.0,
  'tokens': 5601},
 'Medical-689b17ad': {'accuracy': 0.1842740774154663,
  'rouge': 0.21333333333333335,
  'context_recall': 0.0,
  'tokens': 4396},
 'Medical-a7e62dce': {'accuracy': 0.2151460349559784,
  'rouge': 0.3125,
  'context_recall': 0.0,
  'tokens': 4626},
 'Medical-80912696': {'accuracy': 0.7188363074589681,
  'rouge': 0.3018867924528302,
  'context_recall': 0.0,
  'tokens': 4487},
 'Medical-aa1b8dbb': {'accuracy': 0.4710960089743703,
  'rouge': 0.28,
  'context_recall': 0.0,
  'tokens': 7781},
 'Medical-d256aef2': {'accuracy': 0.9706126749046784,
  'rouge': 0.26666666666666666,
  'context_recall': 1.0,
  'tokens': 6813},
 'Medical-c09d2bcb': {'accuracy': 0.5846475958355408,
  'rouge': 0.36666666666666664,
  'context_recall': 0.0,
  'tokens': 5982},
 'Medical-5fdb115b': {'accuracy': 0.395104914863797,
  'rouge': 0.1923076923076923,
  'context_recall': 0.0,
  'tokens': 5846},
 'Medical-9231a873': {'accuracy': 0.486546486574468,
  'rouge': 0.27692307692307694,
  'context_recall': 1.0,
  'tokens': 5343},
 'Medical-ad0cc053': {'accuracy': 0.21079453825950623,
  'rouge': 0.23333333333333334,
  'context_recall': 0.0,
  'tokens': 5508},
 'Medical-5a6b98a7': {'accuracy': 0.9036830479802833,
  'rouge': 0.25352112676056343,
  'context_recall': 1.0,
  'tokens': 6512},
 'Medical-1c53b384': {'accuracy': 0.8415841906783635,
  'rouge': 0.22857142857142856,
  'context_recall': 0.0,
  'tokens': 6084},
 'Medical-0e2be889': {'accuracy': 0.2232576459646225,
  'rouge': 0.3181818181818182,
  'context_recall': 0.0,
  'tokens': 11424},
 'Medical-ff2105ab': {'accuracy': 0.5965786724907669,
  'rouge': 0.29729729729729726,
  'context_recall': 0.0,
  'tokens': 7476},
 'Medical-6a90b47e': {'accuracy': 0.21728618443012238,
  'rouge': 0.23999999999999996,
  'context_recall': 1.0,
  'tokens': 11791},
 'Medical-0d237b40': {'accuracy': 0.33649481829960276,
  'rouge': 0.28571428571428575,
  'context_recall': 0.0,
  'tokens': 10236},
 'Medical-cfab4b2d': {'accuracy': 0.4857391118586629,
  'rouge': 0.358974358974359,
  'context_recall': 1.0,
  'tokens': 8722},
 'Medical-b2da7aee': {'accuracy': 0.6154232263218397,
  'rouge': 0.23529411764705882,
  'context_recall': 0.0,
  'tokens': 8636},
 'Medical-7b422282': {'accuracy': 0.5210323810202393,
  'rouge': 0.24096385542168675,
  'context_recall': 0.0,
  'tokens': 6795},
 'Medical-fc13ecfe': {'accuracy': 0.7359489202051472,
  'rouge': 0.3555555555555555,
  'context_recall': 1.0,
  'tokens': 7711},
 'Medical-3447851a': {'accuracy': 0.7811947166427521,
  'rouge': 0.275,
  'context_recall': 0.0,
  'tokens': 6174},
 'Medical-97022167': {'accuracy': 0.9120005314504493,
  'rouge': 0.29729729729729726,
  'context_recall': 1.0,
  'tokens': 8976},
 'Medical-781a9787': {'accuracy': 0.5101454734427247,
  'rouge': 0.20289855072463767,
  'context_recall': 0.6666666666666666,
  'tokens': 7702},
 'Medical-104b2f70': {'accuracy': 0.9890389441818848,
  'rouge': 0.39999999999999997,
  'context_recall': 1.0,
  'tokens': 7843},
 'Medical-e1ede6d6': {'accuracy': 0.8623621761319692,
  'rouge': 0.3010752688172043,
  'context_recall': 1.0,
  'tokens': 9282},
 'Medical-e8957bed': {'accuracy': 0.8838343421099625,
  'rouge': 0.2692307692307693,
  'context_recall': 1.0,
  'tokens': 4879},
 'Medical-38fc968c': {'accuracy': 0.6823630451706066,
  'rouge': 0.1702127659574468,
  'context_recall': 1.0,
  'tokens': 8602},
 'Medical-00ef7b5d': {'accuracy': 0.40488082167029416,
  'rouge': 0.21359223300970875,
  'context_recall': 0.6666666666666666,
  'tokens': 7246},
 'Medical-ebfc4679': {'accuracy': 0.6003815829378876,
  'rouge': 0.22580645161290322,
  'context_recall': 1.0,
  'tokens': 8275},
 'Medical-f27c64c0': {'accuracy': 0.8469489733516085,
  'rouge': 0.3287671232876712,
  'context_recall': 0.0,
  'tokens': 7523},
 'Medical-5b17d14f': {'accuracy': 0.8776558871229102,
  'rouge': 0.45833333333333326,
  'context_recall': 1.0,
  'tokens': 5361},
 'Medical-bea3adf4': {'accuracy': 0.6056133806142975,
  'rouge': 0.22222222222222218,
  'context_recall': 0.5,
  'tokens': 4759},
 'Medical-99dd217e': {'accuracy': 0.8599976977061766,
  'rouge': 0.3539823008849558,
  'context_recall': 1.0,
  'tokens': 9448},
 'Medical-166bcaa7': {'accuracy': 0.4369880088309461,
  'rouge': 0.21818181818181817,
  'context_recall': 1.0,
  'tokens': 7163},
 'Medical-48cb097c': {'accuracy': 0.8658865178783347,
  'rouge': 0.35714285714285715,
  'context_recall': 1.0,
  'tokens': 7583},
 'Medical-a88065af': {'accuracy': 0.6555541569332431,
  'rouge': 0.21052631578947367,
  'context_recall': 1.0,
  'tokens': 6934},
 'Medical-c41cab28': {'accuracy': 0.602019265237825,
  'rouge': 0.2564102564102564,
  'context_recall': 0.5,
  'tokens': 4322},
 'Medical-f00f6356': {'accuracy': 0.5789741930627272,
  'rouge': 0.2448979591836735,
  'context_recall': 0.0,
  'tokens': 8875},
 'Medical-c22fc609': {'accuracy': 0.850612888681694,
  'rouge': 0.14705882352941177,
  'context_recall': 1.0,
  'tokens': 4859},
 'Medical-e7ebb96c': {'accuracy': 0.19942085444927216,
  'rouge': 0.14925373134328357,
  'context_recall': 0.0,
  'tokens': 5473},
 'Medical-c7bf38df': {'accuracy': 0.6959786414683431,
  'rouge': 0.1951219512195122,
  'context_recall': 1.0,
  'tokens': 7120},
 'Medical-833304f8': {'accuracy': 0.8932033280013046,
  'rouge': 0.35135135135135137,
  'context_recall': 1.0,
  'tokens': 5656},
 'Medical-efd5b238': {'accuracy': 0.7476938834791245,
  'rouge': 0.24,
  'context_recall': 1.0,
  'tokens': 6568},
 'Medical-52ca0ffb': {'accuracy': 0.6248497621863893,
  'rouge': 0.11320754716981134,
  'context_recall': 0.0,
  'tokens': 9179},
 'Medical-16a39fa8': {'accuracy': 0.9757992624711511,
  'rouge': 0.36923076923076925,
  'context_recall': 1.0,
  'tokens': 5225},
 'Medical-a5d38351': {'accuracy': 0.8055134474751171,
  'rouge': 0.20895522388059704,
  'context_recall': 1.0,
  'tokens': 5697},
 'Medical-f57e3ab2': {'accuracy': 0.5585666199191863,
  'rouge': 0.1627906976744186,
  'context_recall': 1.0,
  'tokens': 7857},
 'Medical-7b682af7': {'accuracy': 0.22245334088802338,
  'rouge': 0.3225806451612903,
  'context_recall': 0.0,
  'tokens': 6736},
 'Medical-def9b488': {'accuracy': 0.5234295606133159,
  'rouge': 0.1818181818181818,
  'context_recall': 0.0,
  'tokens': 6299},
 'Medical-950b879f': {'accuracy': 0.858526170205837,
  'rouge': 0.34375,
  'context_recall': 1.0,
  'tokens': 6715},
 'Medical-35afeb4b': {'accuracy': 0.838302379786573,
  'rouge': 0.411764705882353,
  'context_recall': 1.0,
  'tokens': 5117},
 'Medical-b9f39886': {'accuracy': 0.2288726419210434,
  'rouge': 0.2716049382716049,
  'context_recall': 1.0,
  'tokens': 7247},
 'Medical-6d56985a': {'accuracy': 0.9644828735657074,
  'rouge': 0.4186046511627907,
  'context_recall': 1.0,
  'tokens': 4495},
 'Medical-f9e22272': {'accuracy': 0.7335391043950032,
  'rouge': 0.5263157894736842,
  'context_recall': 1.0,
  'tokens': 4322},
 'Medical-efd1af00': {'accuracy': 0.7279752343351384,
  'rouge': 0.2285714285714286,
  'context_recall': 1.0,
  'tokens': 6190},
 'Medical-dc695a12': {'accuracy': 0.3983420558970814,
  'rouge': 0.31034482758620696,
  'context_recall': 0.0,
  'tokens': 6900},
 'Medical-34a70628': {'accuracy': 0.8376917302008491,
  'rouge': 0.5128205128205128,
  'context_recall': 1.0,
  'tokens': 6321},
 'Medical-5e3016f9': {'accuracy': 0.728249371005955,
  'rouge': 0.15189873417721517,
  'context_recall': 1.0,
  'tokens': 10405},
 'Medical-e0c754c6': {'accuracy': 0.3851599792343118,
  'rouge': 0.19047619047619047,
  'context_recall': 1.0,
  'tokens': 6718},
 'Medical-6ac9b753': {'accuracy': 0.9636937379274536,
  'rouge': 0.30188679245283023,
  'context_recall': 1.0,
  'tokens': 5469},
 'Medical-23080670': {'accuracy': 0.7119608222771596,
  'rouge': 0.24,
  'context_recall': 1.0,
  'tokens': 4625},
 'Medical-bd7c7e1a': {'accuracy': 0.7363208233768483,
  'rouge': 0.39344262295081966,
  'context_recall': 0.0,
  'tokens': 5911},
 'Medical-92ed141f': {'accuracy': 0.5781784057218751,
  'rouge': 0.14285714285714285,
  'context_recall': 0.0,
  'tokens': 7884},
 'Medical-6428d1f1': {'accuracy': 0.4698368012488454,
  'rouge': 0.2469135802469136,
  'context_recall': 1.0,
  'tokens': 6622},
 'Medical-04e9f25b': {'accuracy': 0.6553789185136369,
  'rouge': 0.3,
  'context_recall': 0.0,
  'tokens': 7612},
 'Medical-213bbcca': {'accuracy': 0.6654425680187359,
  'rouge': 0.4,
  'context_recall': 1.0,
  'tokens': 8215},
 'Medical-e0a5fcc5': {'accuracy': 0.8256686388966259,
  'rouge': 0.2553191489361702,
  'context_recall': 1.0,
  'tokens': 9507},
 'Medical-423d4257': {'accuracy': 0.6837073839226153,
  'rouge': 0.196078431372549,
  'context_recall': 0.0,
  'tokens': 14974},
 'Medical-68ea8206': {'accuracy': 0.8231993078732153,
  'rouge': 0.25396825396825395,
  'context_recall': 1.0,
  'tokens': 7712},
 'Medical-e2ac8ec4': {'accuracy': 0.21821416914463043,
  'rouge': 0.1111111111111111,
  'context_recall': 1.0,
  'tokens': 6463},
 'Medical-413d4c7e': {'accuracy': 0.7654161588241097,
  'rouge': 0.2191780821917808,
  'context_recall': 0.0,
  'tokens': 6376},
 'Medical-f63520dd': {'accuracy': 0.5770049301158052,
  'rouge': 0.24691358024691357,
  'context_recall': 1.0,
  'tokens': 8215},
 'Medical-8307a348': {'accuracy': 0.5196763008457932,
  'rouge': 0.2191780821917808,
  'context_recall': 1.0,
  'tokens': 10429},
 'Medical-86e095c3': {'accuracy': 0.4763154834092229,
  'rouge': 0.32786885245901637,
  'context_recall': 0.5,
  'tokens': 5729},
 'Medical-02d254bc': {'accuracy': 0.9481745048124389,
  'rouge': 0.45454545454545453,
  'context_recall': 1.0,
  'tokens': 8607},
 'Medical-83eb6b6b': {'accuracy': 0.6825729883243594,
  'rouge': 0.16,
  'context_recall': 1.0,
  'tokens': 7549},
 'Medical-df78005a': {'accuracy': 0.8397186755534034,
  'rouge': 0.6818181818181819,
  'context_recall': 1.0,
  'tokens': 4852},
 'Medical-f8e45373': {'accuracy': 0.9892785846562042,
  'rouge': 0.7169811320754716,
  'context_recall': 1.0,
  'tokens': 5493},
 'Medical-b503f3f3': {'accuracy': 0.4576764255303767,
  'rouge': 0.25396825396825395,
  'context_recall': 0.0,
  'tokens': 8320},
 'Medical-705f9e89': {'accuracy': 0.992956131621701,
  'rouge': 0.5925925925925926,
  'context_recall': 1.0,
  'tokens': 3240}}

In [7]:
def all_valid(values):
    return all(
        v is not None and not np.isnan(v)
        for v in values
    )

In [8]:
#accuracy
#rouge-L
#context recall

from tqdm import tqdm
import time
sep = "\n\n" + "-"*100 + "\n\n"
MAX_RETRIES = 10
SLEEP_SEC = 30

def get_answers():
    for qid in tqdm(question_ids):
        if qid in medical_questions_evaluated:
            continue

        row = relevant_questions.loc[relevant_questions["id"] == qid].iloc[0]
        row_eval = {}

        question = row["question"]
        reference = row["answer"]
        answer = row["LLM_answer"]
        context = row["LLM_context"]
        contexts = context.split(sep)
        
        rouge_score = compute_rouge(answer, reference)
        accuracy, token1 = None, None
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                accuracy, token1 = compute_answer_accuracy(question, answer, reference, call_gemini, create_embedding)
                break
            except Exception as e:
                code = e.error.code if hasattr(e, "error") else e
                print(f"[ERROR] qid={qid} accuracy calculation failed after {attempt} retries: {code}")
                if attempt == MAX_RETRIES:
                    return
                time.sleep(SLEEP_SEC * attempt)  #backoff

        context_recall, token2 = None, None
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                context_recall, token2 = compute_context_recall(question, contexts, reference, call_gemini)
                break
            except Exception as e:
                code = e.error.code if hasattr(e, "error") else e
                print(f"[ERROR] qid={qid} context recall calculation failed after {attempt} retries: {code}")
                if attempt == MAX_RETRIES:
                    return
                time.sleep(SLEEP_SEC * attempt)  #backoff
        if all_valid([accuracy, context_recall, token1, token2]):
            row_eval["accuracy"] = accuracy
            row_eval["rouge"] = rouge_score
            row_eval["context_recall"] = context_recall
            row_eval["tokens"] = token1 + token2
            medical_questions_evaluated[qid] = row_eval
get_answers()

100%|██████████| 509/509 [2:58:56<00:00, 21.09s/it]

In [9]:
medical_questions_evaluated

{'Medical-604c9d44': {'accuracy': 0.7840551137432007,
  'rouge': 0.16129032258064516,
  'context_recall': 1.0,
  'tokens': 6680},
 'Medical-df366063': {'accuracy': 0.6993219851989176,
  'rouge': 0.18421052631578946,
  'context_recall': 1.0,
  'tokens': 8401},
 'Medical-0a90f1f2': {'accuracy': 0.7039262353929487,
  'rouge': 0.09433962264150943,
  'context_recall': 1.0,
  'tokens': 9721},
 'Medical-831bb1e6': {'accuracy': 0.4881982803028321,
  'rouge': 0.24489795918367346,
  'context_recall': 1.0,
  'tokens': 12291},
 'Medical-01e3a9ea': {'accuracy': 0.5165452986475643,
  'rouge': 0.1764705882352941,
  'context_recall': 0.0,
  'tokens': 5392},
 'Medical-c69c2732': {'accuracy': 0.6595893024948254,
  'rouge': 0.14084507042253522,
  'context_recall': 1.0,
  'tokens': 6553},
 'Medical-f034d77d': {'accuracy': 0.5630378631125551,
  'rouge': 0.13186813186813187,
  'context_recall': 1.0,
  'tokens': 9813},
 'Medical-1eab8fa2': {'accuracy': 0.5205341457945618,
  'rouge': 0.24390243902439024,
  'context_recall': 1.0,
  'tokens': 11906},
 'Medical-14016ce3': {'accuracy': 0.187298983335495,
  'rouge': 0.1702127659574468,
  'context_recall': 0.0,
  'tokens': 3328},
 'Medical-5e530443': {'accuracy': 0.20787547528743744,
  'rouge': 0.2926829268292683,
  'context_recall': 0.0,
  'tokens': 7029},
 'Medical-c8dd3e29': {'accuracy': 0.18885651230812073,
  'rouge': 0.15384615384615385,
  'context_recall': 0.0,
  'tokens': 5608},
 'Medical-a9a52704': {'accuracy': 0.8521297956664969,
  'rouge': 0.42857142857142866,
  'context_recall': 1.0,
  'tokens': 7057},
 'Medical-346b12e8': {'accuracy': 0.7127497493739252,
  'rouge': 0.1408450704225352,
  'context_recall': 1.0,
  'tokens': 6689},
 'Medical-8ff5dd5a': {'accuracy': 0.22511957585811615,
  'rouge': 0.28571428571428575,
  'context_recall': 0.0,
  'tokens': 4360},
 'Medical-322bb52d': {'accuracy': 0.7576541900119141,
  'rouge': 0.19672131147540986,
  'context_recall': 1.0,
  'tokens': 10947},
 'Medical-35fee661': {'accuracy': 0.4563199132264226,
  'rouge': 0.19672131147540983,
  'context_recall': 1.0,
  'tokens': 7356},
 'Medical-f473bcb0': {'accuracy': 0.9753583668912476,
  'rouge': 0.392156862745098,
  'context_recall': 1.0,
  'tokens': 4420},
 'Medical-f3af6f24': {'accuracy': 0.5135557382818874,
  'rouge': 0.24489795918367344,
  'context_recall': 0.5,
  'tokens': 6362},
 'Medical-ade4b34a': {'accuracy': 0.5481893320433902,
  'rouge': 0.23880597014925373,
  'context_recall': 0.0,
  'tokens': 7664},
 'Medical-ade95016': {'accuracy': 0.6073125600439819,
  'rouge': 0.1935483870967742,
  'context_recall': 1.0,
  'tokens': 5802},
 'Medical-8435c9f6': {'accuracy': 0.7159355580325251,
  'rouge': 0.1971830985915493,
  'context_recall': 1.0,
  'tokens': 6267},
 'Medical-23e6b6df': {'accuracy': 0.6551669047982934,
  'rouge': 0.23255813953488375,
  'context_recall': 0.5,
  'tokens': 8137},
 'Medical-4744dfa7': {'accuracy': 0.19919320940971375,
  'rouge': 0.18666666666666668,
  'context_recall': 0.0,
  'tokens': 4889},
 'Medical-59ea36ca': {'accuracy': 0.1610906571149826,
  'rouge': 0.061538461538461535,
  'context_recall': 0.0,
  'tokens': 6051},
 'Medical-4124f00f': {'accuracy': 0.310792237490921,
  'rouge': 0.07894736842105264,
  'context_recall': 1.0,
  'tokens': 7837},
 'Medical-ed26b623': {'accuracy': 0.47860710997455136,
  'rouge': 0.18666666666666668,
  'context_recall': 0.0,
  'tokens': 10457},
 'Medical-fbc9e7ec': {'accuracy': 0.5077159901015567,
  'rouge': 0.10526315789473682,
  'context_recall': 0.0,
  'tokens': 6554},
 'Medical-9a34e14c': {'accuracy': 0.5952086150200897,
  'rouge': 0.25,
  'context_recall': 1.0,
  'tokens': 7040},
 'Medical-bfe2b31f': {'accuracy': 0.8051181494589668,
  'rouge': 0.163265306122449,
  'context_recall': 1.0,
  'tokens': 7853},
 'Medical-b6fbf092': {'accuracy': 0.5815307348570766,
  'rouge': 0.14583333333333334,
  'context_recall': 0.0,
  'tokens': 8703},
 'Medical-55898188': {'accuracy': 0.8253131866023827,
  'rouge': 0.14432989690721648,
  'context_recall': 1.0,
  'tokens': 7923},
 'Medical-8b99b755': {'accuracy': 0.5502071505774597,
  'rouge': 0.1958041958041958,
  'context_recall': 0.0,
  'tokens': 9536},
 'Medical-e0f29bbd': {'accuracy': 0.686609399278195,
  'rouge': 0.2535211267605634,
  'context_recall': 0.0,
  'tokens': 8448},
 'Medical-55f0c0e2': {'accuracy': 0.793534040411206,
  'rouge': 0.2947368421052632,
  'context_recall': 1.0,
  'tokens': 12585},
 'Medical-8407a0ab': {'accuracy': 0.6431485520452074,
  'rouge': 0.13333333333333333,
  'context_recall': 1.0,
  'tokens': 7012},
 'Medical-7b4429ac': {'accuracy': 0.6372799006012796,
  'rouge': 0.14193548387096774,
  'context_recall': 0.0,
  'tokens': 13731},
 'Medical-6d12f4ff': {'accuracy': 0.45748971398478444,
  'rouge': 0.08955223880597016,
  'context_recall': 1.0,
  'tokens': 8580},
 'Medical-baed6d13': {'accuracy': 0.7534585016179264,
  'rouge': 0.2298850574712644,
  'context_recall': 1.0,
  'tokens': 9550},
 'Medical-eb7624ca': {'accuracy': 0.49150013107383334,
  'rouge': 0.1951219512195122,
  'context_recall': 1.0,
  'tokens': 10901},
 'Medical-0a6379ff': {'accuracy': 0.5900655984409791,
  'rouge': 0.1764705882352941,
  'context_recall': 0.0,
  'tokens': 6670},
 'Medical-462ecc23': {'accuracy': 0.5209130227192432,
  'rouge': 0.21686746987951808,
  'context_recall': 1.0,
  'tokens': 8767},
 'Medical-2782702e': {'accuracy': 0.43122510395463753,
  'rouge': 0.17391304347826086,
  'context_recall': 0.0,
  'tokens': 5490},
 'Medical-f978cb28': {'accuracy': 0.5183001935122025,
  'rouge': 0.2153846153846154,
  'context_recall': 1.0,
  'tokens': 5543},
 'Medical-4f5a8531': {'accuracy': 0.7770873009666351,
  'rouge': 0.15384615384615383,
  'context_recall': 1.0,
  'tokens': 5140},
 'Medical-db5aa2e3': {'accuracy': 0.8634034479816367,
  'rouge': 0.3050847457627119,
  'context_recall': 0.0,
  'tokens': 6615},
 'Medical-193a4b7f': {'accuracy': 0.5851663648519684,
  'rouge': 0.509090909090909,
  'context_recall': 0.0,
  'tokens': 6087},
 'Medical-e9ac42f1': {'accuracy': 0.8268290519114356,
  'rouge': 0.3508771929824561,
  'context_recall': 1.0,
  'tokens': 4583},
 'Medical-78897235': {'accuracy': 0.19933760166168213,
  'rouge': 0.16666666666666663,
  'context_recall': 0.0,
  'tokens': 7486},
 'Medical-33494794': {'accuracy': 0.1908172369003296,
  'rouge': 0.1568627450980392,
  'context_recall': 0.0,
  'tokens': 5342},
 'Medical-a7826934': {'accuracy': 0.9332640889356171,
  'rouge': 0.31884057971014496,
  'context_recall': 1.0,
  'tokens': 10060},
 'Medical-50bafb57': {'accuracy': 0.5059831171807859,
  'rouge': 0.21333333333333335,
  'context_recall': 1.0,
  'tokens': 10374},
 'Medical-24373ebe': {'accuracy': 0.5992525517495209,
  'rouge': 0.21538461538461537,
  'context_recall': 1.0,
  'tokens': 9135},
 'Medical-9528082d': {'accuracy': 0.8007389664209963,
  'rouge': 0.15384615384615383,
  'context_recall': 1.0,
  'tokens': 8626},
 'Medical-8b16a7bd': {'accuracy': 0.8634032691768861,
  'rouge': 0.3125,
  'context_recall': 1.0,
  'tokens': 9484},
 'Medical-4fe06961': {'accuracy': 0.8325366734978374,
  'rouge': 0.273972602739726,
  'context_recall': 0.0,
  'tokens': 9701},
 'Medical-41b1601a': {'accuracy': 0.44050261373704935,
  'rouge': 0.11111111111111109,
  'context_recall': 0.0,
  'tokens': 6569},
 'Medical-38fe5331': {'accuracy': 0.6046968102080139,
  'rouge': 0.25396825396825395,
  'context_recall': 1.0,
  'tokens': 6477},
 'Medical-4987de7f': {'accuracy': 0.4960280239102062,
  'rouge': 0.12244897959183672,
  'context_recall': 0.0,
  'tokens': 5149},
 'Medical-c2ead218': {'accuracy': 0.6032822280653458,
  'rouge': 0.3157894736842105,
  'context_recall': 0.0,
  'tokens': 5498},
 'Medical-4d01de98': {'accuracy': 0.5866847633971741,
  'rouge': 0.30985915492957744,
  'context_recall': 1.0,
  'tokens': 9609},
 'Medical-34a9155d': {'accuracy': 0.46405148502935384,
  'rouge': 0.15584415584415584,
  'context_recall': 1.0,
  'tokens': 8150},
 'Medical-b7e4be0e': {'accuracy': 0.40097892280408937,
  'rouge': 0.15584415584415584,
  'context_recall': 0.0,
  'tokens': 6329},
 'Medical-96bb3762': {'accuracy': 0.9018994370577774,
  'rouge': 0.2765957446808511,
  'context_recall': 1.0,
  'tokens': 5929},
 'Medical-7ea7ec68': {'accuracy': 0.8899928281186066,
  'rouge': 0.19999999999999998,
  'context_recall': 0.0,
  'tokens': 10088},
 'Medical-e7d1cd1c': {'accuracy': 0.7240918576217377,
  'rouge': 0.3478260869565218,
  'context_recall': 1.0,
  'tokens': 4507},
 'Medical-c7c59020': {'accuracy': 0.6011162399800354,
  'rouge': 0.24324324324324323,
  'context_recall': 1.0,
  'tokens': 6374},
 'Medical-ee49f3e8': {'accuracy': 0.8936492899535141,
  'rouge': 0.2191780821917808,
  'context_recall': 1.0,
  'tokens': 6272},
 'Medical-b77d8e3d': {'accuracy': 0.8048125415440421,
  'rouge': 0.15789473684210525,
  'context_recall': 1.0,
  'tokens': 5588},
 'Medical-6fb8996b': {'accuracy': 0.47234824295228983,
  'rouge': 0.1923076923076923,
  'context_recall': 1.0,
  'tokens': 4824},
 'Medical-edc3c6eb': {'accuracy': 0.9695851802200928,
  'rouge': 0.29508196721311475,
  'context_recall': 1.0,
  'tokens': 5364},
 'Medical-f3048835': {'accuracy': 0.7359181046041456,
  'rouge': 0.24324324324324326,
  'context_recall': 1.0,
  'tokens': 9347},
 'Medical-f79d978d': {'accuracy': 0.6887872195734794,
  'rouge': 0.2150537634408602,
  'context_recall': 1.0,
  'tokens': 9164},
 'Medical-47504b64': {'accuracy': 0.41269922253188474,
  'rouge': 0.21951219512195122,
  'context_recall': 1.0,
  'tokens': 7462},
 'Medical-328006b7': {'accuracy': 0.4212546177905445,
  'rouge': 0.17142857142857143,
  'context_recall': 0.0,
  'tokens': 7221},
 'Medical-659d7c0a': {'accuracy': 0.9053020293416725,
  'rouge': 0.30303030303030304,
  'context_recall': 1.0,
  'tokens': 5601},
 'Medical-689b17ad': {'accuracy': 0.1842740774154663,
  'rouge': 0.21333333333333335,
  'context_recall': 0.0,
  'tokens': 4396},
 'Medical-a7e62dce': {'accuracy': 0.2151460349559784,
  'rouge': 0.3125,
  'context_recall': 0.0,
  'tokens': 4626},
 'Medical-80912696': {'accuracy': 0.7188363074589681,
  'rouge': 0.3018867924528302,
  'context_recall': 0.0,
  'tokens': 4487},
 'Medical-aa1b8dbb': {'accuracy': 0.4710960089743703,
  'rouge': 0.28,
  'context_recall': 0.0,
  'tokens': 7781},
 'Medical-d256aef2': {'accuracy': 0.9706126749046784,
  'rouge': 0.26666666666666666,
  'context_recall': 1.0,
  'tokens': 6813},
 'Medical-c09d2bcb': {'accuracy': 0.5846475958355408,
  'rouge': 0.36666666666666664,
  'context_recall': 0.0,
  'tokens': 5982},
 'Medical-5fdb115b': {'accuracy': 0.395104914863797,
  'rouge': 0.1923076923076923,
  'context_recall': 0.0,
  'tokens': 5846},
 'Medical-9231a873': {'accuracy': 0.486546486574468,
  'rouge': 0.27692307692307694,
  'context_recall': 1.0,
  'tokens': 5343},
 'Medical-ad0cc053': {'accuracy': 0.21079453825950623,
  'rouge': 0.23333333333333334,
  'context_recall': 0.0,
  'tokens': 5508},
 'Medical-5a6b98a7': {'accuracy': 0.9036830479802833,
  'rouge': 0.25352112676056343,
  'context_recall': 1.0,
  'tokens': 6512},
 'Medical-1c53b384': {'accuracy': 0.8415841906783635,
  'rouge': 0.22857142857142856,
  'context_recall': 0.0,
  'tokens': 6084},
 'Medical-0e2be889': {'accuracy': 0.2232576459646225,
  'rouge': 0.3181818181818182,
  'context_recall': 0.0,
  'tokens': 11424},
 'Medical-ff2105ab': {'accuracy': 0.5965786724907669,
  'rouge': 0.29729729729729726,
  'context_recall': 0.0,
  'tokens': 7476},
 'Medical-6a90b47e': {'accuracy': 0.21728618443012238,
  'rouge': 0.23999999999999996,
  'context_recall': 1.0,
  'tokens': 11791},
 'Medical-0d237b40': {'accuracy': 0.33649481829960276,
  'rouge': 0.28571428571428575,
  'context_recall': 0.0,
  'tokens': 10236},
 'Medical-cfab4b2d': {'accuracy': 0.4857391118586629,
  'rouge': 0.358974358974359,
  'context_recall': 1.0,
  'tokens': 8722},
 'Medical-b2da7aee': {'accuracy': 0.6154232263218397,
  'rouge': 0.23529411764705882,
  'context_recall': 0.0,
  'tokens': 8636},
 'Medical-7b422282': {'accuracy': 0.5210323810202393,
  'rouge': 0.24096385542168675,
  'context_recall': 0.0,
  'tokens': 6795},
 'Medical-fc13ecfe': {'accuracy': 0.7359489202051472,
  'rouge': 0.3555555555555555,
  'context_recall': 1.0,
  'tokens': 7711},
 'Medical-3447851a': {'accuracy': 0.7811947166427521,
  'rouge': 0.275,
  'context_recall': 0.0,
  'tokens': 6174},
 'Medical-97022167': {'accuracy': 0.9120005314504493,
  'rouge': 0.29729729729729726,
  'context_recall': 1.0,
  'tokens': 8976},
 'Medical-781a9787': {'accuracy': 0.5101454734427247,
  'rouge': 0.20289855072463767,
  'context_recall': 0.6666666666666666,
  'tokens': 7702},
 'Medical-104b2f70': {'accuracy': 0.9890389441818848,
  'rouge': 0.39999999999999997,
  'context_recall': 1.0,
  'tokens': 7843},
 'Medical-e1ede6d6': {'accuracy': 0.8623621761319692,
  'rouge': 0.3010752688172043,
  'context_recall': 1.0,
  'tokens': 9282},
 'Medical-e8957bed': {'accuracy': 0.8838343421099625,
  'rouge': 0.2692307692307693,
  'context_recall': 1.0,
  'tokens': 4879},
 'Medical-38fc968c': {'accuracy': 0.6823630451706066,
  'rouge': 0.1702127659574468,
  'context_recall': 1.0,
  'tokens': 8602},
 'Medical-00ef7b5d': {'accuracy': 0.40488082167029416,
  'rouge': 0.21359223300970875,
  'context_recall': 0.6666666666666666,
  'tokens': 7246},
 'Medical-ebfc4679': {'accuracy': 0.6003815829378876,
  'rouge': 0.22580645161290322,
  'context_recall': 1.0,
  'tokens': 8275},
 'Medical-f27c64c0': {'accuracy': 0.8469489733516085,
  'rouge': 0.3287671232876712,
  'context_recall': 0.0,
  'tokens': 7523},
 'Medical-5b17d14f': {'accuracy': 0.8776558871229102,
  'rouge': 0.45833333333333326,
  'context_recall': 1.0,
  'tokens': 5361},
 'Medical-bea3adf4': {'accuracy': 0.6056133806142975,
  'rouge': 0.22222222222222218,
  'context_recall': 0.5,
  'tokens': 4759},
 'Medical-99dd217e': {'accuracy': 0.8599976977061766,
  'rouge': 0.3539823008849558,
  'context_recall': 1.0,
  'tokens': 9448},
 'Medical-166bcaa7': {'accuracy': 0.4369880088309461,
  'rouge': 0.21818181818181817,
  'context_recall': 1.0,
  'tokens': 7163},
 'Medical-48cb097c': {'accuracy': 0.8658865178783347,
  'rouge': 0.35714285714285715,
  'context_recall': 1.0,
  'tokens': 7583},
 'Medical-a88065af': {'accuracy': 0.6555541569332431,
  'rouge': 0.21052631578947367,
  'context_recall': 1.0,
  'tokens': 6934},
 'Medical-c41cab28': {'accuracy': 0.602019265237825,
  'rouge': 0.2564102564102564,
  'context_recall': 0.5,
  'tokens': 4322},
 'Medical-f00f6356': {'accuracy': 0.5789741930627272,
  'rouge': 0.2448979591836735,
  'context_recall': 0.0,
  'tokens': 8875},
 'Medical-c22fc609': {'accuracy': 0.850612888681694,
  'rouge': 0.14705882352941177,
  'context_recall': 1.0,
  'tokens': 4859},
 'Medical-e7ebb96c': {'accuracy': 0.19942085444927216,
  'rouge': 0.14925373134328357,
  'context_recall': 0.0,
  'tokens': 5473},
 'Medical-c7bf38df': {'accuracy': 0.6959786414683431,
  'rouge': 0.1951219512195122,
  'context_recall': 1.0,
  'tokens': 7120},
 'Medical-833304f8': {'accuracy': 0.8932033280013046,
  'rouge': 0.35135135135135137,
  'context_recall': 1.0,
  'tokens': 5656},
 'Medical-efd5b238': {'accuracy': 0.7476938834791245,
  'rouge': 0.24,
  'context_recall': 1.0,
  'tokens': 6568},
 'Medical-52ca0ffb': {'accuracy': 0.6248497621863893,
  'rouge': 0.11320754716981134,
  'context_recall': 0.0,
  'tokens': 9179},
 'Medical-16a39fa8': {'accuracy': 0.9757992624711511,
  'rouge': 0.36923076923076925,
  'context_recall': 1.0,
  'tokens': 5225},
 'Medical-a5d38351': {'accuracy': 0.8055134474751171,
  'rouge': 0.20895522388059704,
  'context_recall': 1.0,
  'tokens': 5697},
 'Medical-f57e3ab2': {'accuracy': 0.5585666199191863,
  'rouge': 0.1627906976744186,
  'context_recall': 1.0,
  'tokens': 7857},
 'Medical-7b682af7': {'accuracy': 0.22245334088802338,
  'rouge': 0.3225806451612903,
  'context_recall': 0.0,
  'tokens': 6736},
 'Medical-def9b488': {'accuracy': 0.5234295606133159,
  'rouge': 0.1818181818181818,
  'context_recall': 0.0,
  'tokens': 6299},
 'Medical-950b879f': {'accuracy': 0.858526170205837,
  'rouge': 0.34375,
  'context_recall': 1.0,
  'tokens': 6715},
 'Medical-35afeb4b': {'accuracy': 0.838302379786573,
  'rouge': 0.411764705882353,
  'context_recall': 1.0,
  'tokens': 5117},
 'Medical-b9f39886': {'accuracy': 0.2288726419210434,
  'rouge': 0.2716049382716049,
  'context_recall': 1.0,
  'tokens': 7247},
 'Medical-6d56985a': {'accuracy': 0.9644828735657074,
  'rouge': 0.4186046511627907,
  'context_recall': 1.0,
  'tokens': 4495},
 'Medical-f9e22272': {'accuracy': 0.7335391043950032,
  'rouge': 0.5263157894736842,
  'context_recall': 1.0,
  'tokens': 4322},
 'Medical-efd1af00': {'accuracy': 0.7279752343351384,
  'rouge': 0.2285714285714286,
  'context_recall': 1.0,
  'tokens': 6190},
 'Medical-dc695a12': {'accuracy': 0.3983420558970814,
  'rouge': 0.31034482758620696,
  'context_recall': 0.0,
  'tokens': 6900},
 'Medical-34a70628': {'accuracy': 0.8376917302008491,
  'rouge': 0.5128205128205128,
  'context_recall': 1.0,
  'tokens': 6321},
 'Medical-5e3016f9': {'accuracy': 0.728249371005955,
  'rouge': 0.15189873417721517,
  'context_recall': 1.0,
  'tokens': 10405},
 'Medical-e0c754c6': {'accuracy': 0.3851599792343118,
  'rouge': 0.19047619047619047,
  'context_recall': 1.0,
  'tokens': 6718},
 'Medical-6ac9b753': {'accuracy': 0.9636937379274536,
  'rouge': 0.30188679245283023,
  'context_recall': 1.0,
  'tokens': 5469},
 'Medical-23080670': {'accuracy': 0.7119608222771596,
  'rouge': 0.24,
  'context_recall': 1.0,
  'tokens': 4625},
 'Medical-bd7c7e1a': {'accuracy': 0.7363208233768483,
  'rouge': 0.39344262295081966,
  'context_recall': 0.0,
  'tokens': 5911},
 'Medical-92ed141f': {'accuracy': 0.5781784057218751,
  'rouge': 0.14285714285714285,
  'context_recall': 0.0,
  'tokens': 7884},
 'Medical-6428d1f1': {'accuracy': 0.4698368012488454,
  'rouge': 0.2469135802469136,
  'context_recall': 1.0,
  'tokens': 6622},
 'Medical-04e9f25b': {'accuracy': 0.6553789185136369,
  'rouge': 0.3,
  'context_recall': 0.0,
  'tokens': 7612},
 'Medical-213bbcca': {'accuracy': 0.6654425680187359,
  'rouge': 0.4,
  'context_recall': 1.0,
  'tokens': 8215},
 'Medical-e0a5fcc5': {'accuracy': 0.8256686388966259,
  'rouge': 0.2553191489361702,
  'context_recall': 1.0,
  'tokens': 9507},
 'Medical-423d4257': {'accuracy': 0.6837073839226153,
  'rouge': 0.196078431372549,
  'context_recall': 0.0,
  'tokens': 14974},
 'Medical-68ea8206': {'accuracy': 0.8231993078732153,
  'rouge': 0.25396825396825395,
  'context_recall': 1.0,
  'tokens': 7712},
 'Medical-e2ac8ec4': {'accuracy': 0.21821416914463043,
  'rouge': 0.1111111111111111,
  'context_recall': 1.0,
  'tokens': 6463},
 'Medical-413d4c7e': {'accuracy': 0.7654161588241097,
  'rouge': 0.2191780821917808,
  'context_recall': 0.0,
  'tokens': 6376},
 'Medical-f63520dd': {'accuracy': 0.5770049301158052,
  'rouge': 0.24691358024691357,
  'context_recall': 1.0,
  'tokens': 8215},
 'Medical-8307a348': {'accuracy': 0.5196763008457932,
  'rouge': 0.2191780821917808,
  'context_recall': 1.0,
  'tokens': 10429},
 'Medical-86e095c3': {'accuracy': 0.4763154834092229,
  'rouge': 0.32786885245901637,
  'context_recall': 0.5,
  'tokens': 5729},
 'Medical-02d254bc': {'accuracy': 0.9481745048124389,
  'rouge': 0.45454545454545453,
  'context_recall': 1.0,
  'tokens': 8607},
 'Medical-83eb6b6b': {'accuracy': 0.6825729883243594,
  'rouge': 0.16,
  'context_recall': 1.0,
  'tokens': 7549},
 'Medical-df78005a': {'accuracy': 0.8397186755534034,
  'rouge': 0.6818181818181819,
  'context_recall': 1.0,
  'tokens': 4852},
 'Medical-f8e45373': {'accuracy': 0.9892785846562042,
  'rouge': 0.7169811320754716,
  'context_recall': 1.0,
  'tokens': 5493},
 'Medical-b503f3f3': {'accuracy': 0.4576764255303767,
  'rouge': 0.25396825396825395,
  'context_recall': 0.0,
  'tokens': 8320},
 'Medical-705f9e89': {'accuracy': 0.992956131621701,
  'rouge': 0.5925925925925926,
  'context_recall': 1.0,
  'tokens': 3240},
 'Medical-8779d729': {'accuracy': 0.7306206225867395,
  'rouge': 0.3783783783783784,
  'context_recall': 1.0,
  'tokens': 5718},

In [10]:
df_eval = (
    pd.DataFrame.from_dict(medical_questions_evaluated, orient="index")
      .reset_index()
      .rename(columns={"index": "qid"})
)

In [11]:
df_eval.to_parquet("data/evaluations/normal_rag_evaluated.parquet")
df_eval_loaded = pd.read_parquet("data/evaluations/normal_rag_evaluated.parquet")
df_eval_loaded

                  qid  accuracy     rouge  context_recall  tokens
0    Medical-604c9d44  0.784055  0.161290             1.0    6680
1    Medical-df366063  0.699322  0.184211             1.0    8401
2    Medical-0a90f1f2  0.703926  0.094340             1.0    9721
3    Medical-831bb1e6  0.488198  0.244898             1.0   12291
4    Medical-01e3a9ea  0.516545  0.176471             0.0    5392
..                ...       ...       ...             ...     ...
504  Medical-1eda4787  0.732013  0.321429             0.0    5600
505  Medical-24f2e8ea  0.609938  0.339623             1.0    4073
506  Medical-d1a87cb4  0.547433  0.135135             0.0    7303
507  Medical-311d66d6  0.637592  0.280702             0.0    7154
508  Medical-ac117ebf  0.789984  0.328358             1.0    7166

[509 rows x 5 columns]

In [12]:
print("min:", df_eval_loaded["tokens"].min())
print("max:", df_eval_loaded["tokens"].max())
print("avg:", df_eval_loaded["tokens"].mean())
print("sum:", df_eval_loaded["tokens"].sum())

min: 2205
max: 16184
avg: 7570.2023575638505
sum: 3853233

In [13]:
print("min:", df_eval_loaded["accuracy"].min())
print("max:", df_eval_loaded["accuracy"].max())
print("avg:", df_eval_loaded["accuracy"].mean())
print("sum:", df_eval_loaded["accuracy"].sum())

min: 0.15925246477127075
max: 0.9944541453565185
avg: 0.6409751632634693
sum: 326.25635810110583

In [14]:
print("min:", df_eval_loaded["rouge"].min())
print("max:", df_eval_loaded["rouge"].max())
print("avg:", df_eval_loaded["rouge"].mean())
print("sum:", df_eval_loaded["rouge"].sum())

min: 0.061538461538461535
max: 0.7169811320754716
avg: 0.2685599192152199
sum: 136.69699888054691

In [15]:
print("min:", df_eval_loaded["context_recall"].min())
print("max:", df_eval_loaded["context_recall"].max())
print("avg:", df_eval_loaded["context_recall"].mean())
print("sum:", df_eval_loaded["context_recall"].sum())

min: 0.0
max: 1.0
avg: 0.6548788474132287
sum: 333.33333333333337