# Notebook 5: Community Detection and Aggregation

This notebook processes the attribute-enriched graph **G2** to detect structural communities using the **Leiden algorithm**.

For each community, the LLM is invoked to generate a **community summary** using all semantic units within that community.  
If a community contains only one semantic unit, summarization is skipped.  
These summaries form the content for **High-level Element (H) nodes**.

From each community summary, an additional LLM call extracts **keywords** and **titles**.  
These results serve as the content for **High-level Overview (O) nodes**.

The resulting communities are also saved for future processing.

In [1]:
import os
dir_path = os.getcwd()
print("The directory of this script is:", dir_path)
root_path = os.path.dirname(dir_path)
print("The root directory is:", root_path)

The directory of this script is: d:\Documents\GitHub\NodeRAG\graphs
The root directory is: d:\Documents\GitHub\NodeRAG

In [2]:
import sys
sys.path.append(root_path)
from graphs.Node import Node

In [3]:
import pickle
with open(f"{root_path}/graphs/data/graphs/G2_medical_attribute_enriched_graph.pkl", "rb") as f:
    medical_g2 = pickle.load(f)

In [4]:
import igraph as ig
from leidenalg import find_partition, ModularityVertexPartition
from collections import defaultdict

def leiden_community_detection(node_dict):
    id_to_idx = {nid: i for i, nid in enumerate(node_dict.keys())}
    idx_to_id = {v: k for k, v in id_to_idx.items()}

    edge_weights = defaultdict(float)
    for nid, node in node_dict.items():
        for neighbor, weight in node.edges.items():
            a, b = id_to_idx[nid], id_to_idx[neighbor]
            if a < b:
                edge_weights[(a, b)] += weight

    edges = list(edge_weights.keys())
    weights = list(edge_weights.values())

    g = ig.Graph(n=len(node_dict), edges=edges, directed=False)
    g.es["weight"] = weights

    partition = find_partition(g, ModularityVertexPartition, weights="weight")
    membership = partition.membership
    communities = {idx_to_id[i]: membership[i] for i in range(len(node_dict))}
    return communities

In [5]:
from collections import Counter
medical_communities = leiden_community_detection(medical_g2)
medical_communities_counts = Counter(medical_communities.values())
s1 = 0
for val in medical_communities_counts.values():
    if val==1:
        s1+=val
print("Medical single-node communities:", s1)

Medical single-node communities: 187

In [6]:
medical_communities_counts

Counter({0: 2428,
         1: 2195,
         2: 2177,
         3: 2130,
         4: 1894,
         5: 1886,
         6: 1876,
         7: 1475,
         8: 1403,
         9: 1381,
         10: 1371,
         11: 1363,
         12: 1362,
         13: 1322,
         14: 1299,
         15: 1186,
         16: 1178,
         17: 1082,
         18: 1077,
         19: 1068,
         20: 1064,
         21: 1054,
         22: 996,
         23: 982,
         24: 936,
         25: 918,
         26: 862,
         27: 817,
         28: 677,
         29: 521,
         30: 407,
         31: 353,
         32: 349,
         33: 249,
         34: 228,
         35: 211,
         36: 190,
         37: 190,
         38: 155,
         39: 45,
         40: 29,
         41: 8,
         42: 5,
         43: 4,
         44: 4,
         45: 3,
         46: 1,
         47: 1,
         48: 1,
         49: 1,
         50: 1,
         51: 1,
         52: 1,
         53: 1,
         54: 1,
         55: 1,
         56: 1,
         57: 1,
         58: 1,
         59: 1,
         60: 1,
         61: 1,
         62: 1,
         63: 1,
         64: 1,
         65: 1,
         66: 1,
         67: 1,
         68: 1,
         69: 1,
         70: 1,
         71: 1,
         72: 1,
         73: 1,
         74: 1,
         75: 1,
         76: 1,
         77: 1,
         78: 1,
         79: 1,
         80: 1,
         81: 1,
         82: 1,
         83: 1,
         84: 1,
         85: 1,
         86: 1,
         87: 1,
         88: 1,
         89: 1,
         90: 1,
         91: 1,
         92: 1,
         93: 1,
         94: 1,
         95: 1,
         96: 1,
         97: 1,
         98: 1,
         99: 1,
         100: 1,
         101: 1,
         102: 1,
         103: 1,
         104: 1,
         105: 1,
         106: 1,
         107: 1,
         108: 1,
         109: 1,
         110: 1,
         111: 1,
         112: 1,
         113: 1,
         114: 1,
         115: 1,
         116: 1,
         117: 1,
         118: 1,
         119: 1,
         120: 1,
         121: 1,
         122: 1,
         123: 1,
         124: 1,
         125: 1,
         126: 1,
         127: 1,
         128: 1,
         129: 1,
         130: 1,
         131: 1,
         132: 1,
         133: 1,
         134: 1,
         135: 1,
         136: 1,
         137: 1,
         138: 1,
         139: 1,
         140: 1,
         141: 1,
         142: 1,
         143: 1,
         144: 1,
         145: 1,
         146: 1,
         147: 1,
         148: 1,
         149: 1,
         150: 1,
         151: 1,
         152: 1,
         153: 1,
         154: 1,
         155: 1,
         156: 1,
         157: 1,
         158: 1,
         159: 1,
         160: 1,
         161: 1,
         162: 1,
         163: 1,
         164: 1,
         165: 1,
         166: 1,
         167: 1,
         168: 1,
         169: 1,
         170: 1,
         171: 1,
         172: 1,
         173: 1,
         174: 1,
         175: 1,
         176: 1,
         177: 1,
         178: 1,
         179: 1,
         180: 1,
         181: 1,
         182: 1,
         183: 1,
         184: 1,
         185: 1,
         186: 1,
         187: 1,
         188: 1,
         189: 1,
         190: 1,
         191: 1,
         192: 1,
         193: 1,
         194: 1,
         195: 1,
         196: 1,
         197: 1,
         198: 1,
         199: 1,
         200: 1,
         201: 1,
         202: 1,
         203: 1,
         204: 1,
         205: 1,
         206: 1,
         207: 1,
         208: 1,
         209: 1,
         210: 1,
         211: 1,
         212: 1,
         213: 1,
         214: 1,
         215: 1,
         216: 1,
         217: 1,
         218: 1,
         219: 1,
         220: 1,
         221: 1,
         222: 1,
         223: 1,
         224: 1,
         225: 1,
         226: 1,
         227: 1,
         228: 1,
         229: 1,
         230: 1,
         231: 1,
         232: 1})

In [7]:
communities_medical = defaultdict(list)
for node_id, community_id in medical_communities.items():
    #if medical_g2[node_id].node_type == "N":
    #    continue
    communities_medical[community_id].append(node_id)

In [8]:
communities_medical

defaultdict(list,
            {17: ['medical-0-S-0',
              'medical-0-S-0-R-0',
              'medical-0-S-0-R-1',
              'medical-0-S-0-R-2',
              'medical-0-S-0-R-3',
              'medical-0-S-0-R-4',
              'medical-0-S-1',
              'medical-0-S-1-R-0',
              'medical-0-S-1-R-1',
              'medical-0-S-1-R-2',
              'medical-0-S-1-R-3',
              'medical-0-S-1-R-4',
              'medical-0-S-1-R-5',
              'medical-0-S-1-R-6',
              'medical-0-S-1-R-7',
              'medical-0-S-1-R-8',
              'medical-0-S-1-R-9',
              'medical-0-S-1-R-10',
              'medical-0-S-1-R-11',
              'medical-0-S-1-R-12',
              'medical-0-S-2-R-1',
              'medical-0-S-2-R-2',
              'medical-0-S-3',
              'medical-0-S-3-R-0',
              'medical-0-S-3-R-1',
              'medical-0-S-3-R-2',
              'medical-0-S-3-R-3',
              'medical-0-S-3-R-4',
              'medical-0-S-3-R-5',
              'medical-0-S-3-R-6',
              'medical-0-S-3-R-7',
              'medical-0-S-3-R-8',
              'medical-0-S-3-R-9',
              'medical-0-S-3-R-10',
              'medical-0-S-3-R-11',
              'medical-0-S-3-R-12',
              'medical-0-S-3-R-13',
              'medical-0-S-3-R-14',
              'medical-0-S-3-R-15',
              'medical-0-S-3-R-16',
              'medical-0-S-3-R-17',
              'medical-0-S-3-R-18',
              'medical-0-S-3-R-19',
              'medical-0-S-3-R-20',
              'medical-0-S-3-R-21',
              'medical-0-S-3-R-22',
              'medical-0-S-3-R-23',
              'medical-0-S-3-R-24',
              'medical-0-S-3-R-25',
              'medical-0-S-3-R-26',
              'medical-0-S-3-R-27',
              'medical-1-S-0',
              'medical-1-S-0-R-1',
              'medical-1-S-0-R-2',
              'medical-1-S-0-R-3',
              'medical-1-S-0-R-4',
              'medical-1-S-0-R-5',
              'medical-1-S-0-R-6',
              'medical-1-S-0-R-7',
              'medical-1-S-0-R-8',
              'medical-1-S-0-R-9',
              'medical-1-S-0-R-10',
              'medical-1-S-1',
              'medical-1-S-1-R-0',
              'medical-1-S-2',
              'medical-1-S-2-R-0',
              'medical-1-S-2-R-1',
              'medical-1-S-2-R-2',
              'medical-1-S-2-R-3',
              'medical-1-S-2-R-4',
              'medical-1-S-2-R-5',
              'medical-1-S-2-R-6',
              'medical-1-S-2-R-7',
              'medical-1-S-2-R-8',
              'medical-1-S-2-R-9',
              'medical-1-S-2-R-10',
              'medical-1-S-2-R-11',
              'medical-1-S-2-R-12',
              'medical-1-S-2-R-13',
              'medical-1-S-2-R-14',
              'medical-1-S-2-R-15',
              'medical-1-S-2-R-16',
              'medical-1-S-2-R-17',
              'medical-1-S-3',
              'medical-1-S-3-R-0',
              'medical-1-S-3-R-1',
              'medical-1-S-3-R-2',
              'medical-1-S-4',
              'medical-1-S-4-R-0',
              'medical-1-S-4-R-1',
              'medical-1-S-4-R-2',
              'medical-1-S-4-R-3',
              'medical-1-S-4-R-6',
              'medical-1-S-4-R-7',
              'medical-2-S-0',
              'medical-2-S-0-R-0',
              'medical-2-S-0-R-1',
              'medical-2-S-0-R-2',
              'medical-2-S-0-R-3',
              'medical-2-S-0-R-4',
              'medical-2-S-0-R-8',
              'medical-2-S-0-R-9',
              'medical-2-S-0-R-10',
              'medical-2-S-0-R-11',
              'medical-2-S-0-R-12',
              'medical-2-S-0-R-13',
              'medical-2-S-0-R-14',
              'medical-2-S-0-R-15',
              'medical-2-S-0-R-17',
              'medical-2-S-0-R-18',
              'medical-2-S-0-R-19',
              'medical-2-S-0-R-20',
              'medical-2-S-0-R-21',
              'medical-2-S-1',
              'medical-2-S-1-R-0',
              'medical-2-S-1-R-1',
              'medical-2-S-1-R-2',
              'medical-2-S-1-R-4',
              'medical-2-S-1-R-5',
              'medical-2-S-1-R-6',
              'medical-2-S-1-R-7',
              'medical-2-S-1-R-8',
              'medical-2-S-1-R-11',
              'medical-2-S-1-R-12',
              'medical-2-S-1-R-14',
              'medical-3-S-0',
              'medical-3-S-0-R-0',
              'medical-3-S-0-R-1',
              'medical-3-S-0-R-2',
              'medical-3-S-0-R-3',
              'medical-3-S-0-R-4',
              'medical-3-S-3',
              'medical-3-S-3-R-1',
              'medical-3-S-3-R-2',
              'medical-3-S-3-R-3',
              'medical-3-S-3-R-4',
              'medical-3-S-3-R-5',
              'medical-3-S-3-R-6',
              'medical-3-S-3-R-7',
              'medical-4-S-0-R-1',
              'medical-4-S-0-R-2',
              'medical-4-S-0-R-4',
              'medical-4-S-0-R-5',
              'medical-4-S-0-R-6',
              'medical-10-S-0-R-6',
              'medical-13-S-0',
              'medical-13-S-0-R-0',
              'medical-13-S-0-R-1',
              'medical-13-S-0-R-2',
              'medical-13-S-0-R-3',
              'medical-13-S-0-R-4',
              'medical-13-S-0-R-5',
              'medical-13-S-0-R-6',
              'medical-13-S-0-R-7',
              'medical-13-S-0-R-8',
              'medical-13-S-0-R-9',
              'medical-13-S-0-R-10',
              'medical-13-S-0-R-11',
              'medical-13-S-0-R-12',
              'medical-13-S-0-R-13',
              'medical-13-S-0-R-14',
              'medical-13-S-1',
              'medical-13-S-1-R-0',
              'medical-13-S-1-R-1',
              'medical-13-S-1-R-2',
              'medical-13-S-1-R-6',
              'medical-13-S-1-R-7',
              'medical-13-S-1-R-8',
              'medical-13-S-2',
              'medical-13-S-2-R-0',
              'medical-13-S-2-R-1',
              'medical-13-S-2-R-2',
              'medical-13-S-2-R-3',
              'medical-13-S-2-R-4',
              'medical-13-S-2-R-5',
              'medical-13-S-3',
              'medical-13-S-3-R-0',
              'medical-13-S-3-R-1',
              'medical-13-S-3-R-2',
              'medical-13-S-3-R-3',
              'medical-13-S-3-R-4',
              'medical-13-S-3-R-5',
              'medical-13-S-3-R-6',
              'medical-13-S-3-R-7',
              'medical-13-S-3-R-8',
              'medical-13-S-3-R-9',
              'medical-13-S-3-R-10',
              'medical-13-S-3-R-11',
              'medical-13-S-3-R-12',
              'medical-13-S-3-R-13',
              'medical-13-S-3-R-14',
              'medical-13-S-3-R-15',
              'medical-13-S-3-R-16',
              'medical-13-S-4',
              'medical-13-S-4-R-0',
              'medical-13-S-4-R-1',
              'medical-13-S-4-R-2',
              'medical-13-S-4-R-3',
              'medical-13-S-4-R-4',
              'medical-13-S-4-R-5',
              'medical-13-S-4-R-6',
              'medical-13-S-4-R-7',
              'medical-13-S-4-R-8',
              'medical-13-S-4-R-9',
              'medical-13-S-4-R-10',
              'medical-13-S-4-R-11',
              'medical-13-S-4-R-12',
              'medical-13-S-4-R-13',
              'medical-13-S-4-R-14',
              'medical-13-S-4-R-15',
              'medical-13-S-4-R-16',
              'medical-13-S-4-R-17',
              'medical-14-S-0',
              'medical-14-S-0-R-0',
              'medical-14-S-0-R-1',
              'medical-14-S-0-R-2',
              'medical-14-S-0-R-3',
              'medical-14-S-0-R-4',
              'medical-14-S-0-R-5',
              'medical-14-S-0-R-6',
              'medical-14-S-0-R-7',
              'medical-14-S-0-R-8',
              'medical-14-S-0-R-9',
              'medical-14-S-0-R-10',
              'medical-14-S-0-R-11',
              'medical-14-S-0-R-12',
              'medical-14-S-0-R-13',
              'medical-14-S-0-R-14',
              'medical-14-S-0-R-15',
              'medical-14-S-0-R-16',
              'medical-14-S-1-R-2',
              'medical-14-S-2',
              'medical-14-S-2-R-0',
              'medical-14-S-2-R-1',
              'medical-14-S-2-R-2',
              'medical-14-S-2-R-3',
              'medical-14-S-2-R-4',
              'medical-14-S-2-R-5',
              'medical-14-S-2-R-6',
              'medical-14-S-2-R-7',
              'medical-14-S-2-R-8',
              'medical-14-S-3',
              'medical-14-S-3-R-0',
              'medical-14-S-3-R-1',
              'medical-14-S-3-R-2',
              'medical-14-S-3-R-3',
              'medical-14-S-5',
              'medical-14-S-5-R-0',
              'medical-14-S-5-R-1',
              'medical-14-S-5-R-2',
              'medical-14-S-5-R-3',
              'medical-14-S-5-R-4',
              'medical-14-S-5-R-5',
              'medical-14-S-5-R-6',
              'medical-15-S-0',
              'medical-15-S-0-R-0',
              'medical-15-S-0-R-1',
              'medical-15-S-0-R-2',
              'medical-15-S-2',
              'medical-15-S-2-R-0',
              'medical-15-S-2-R-1',
              'medical-15-S-2-R-2',
              'medical-15-S-2-R-3',
              'medical-15-S-2-R-4',
              'medical-15-S-3',
              'medical-15-S-3-R-0',
              'medical-15-S-3-R-1',
              'medical-15-S-3-R-2',
              'medical-15-S-3-R-3',
              'medical-15-S-3-R-4',
              'medical-15-S-3-R-5',
              'medical-15-S-3-R-6',
              'medical-15-S-3-R-7',
              'medical-15-S-3-R-8',
              'medical-15-S-3-R-9',
              'medical-15-S-3-R-10',
              'medical-15-S-3-R-12',
              'medical-15-S-3-R-13',
              'medical-15-S-3-R-14',
              'medical-15-S-3-R-15',
              'medical-15-S-3-R-16',
              'medical-15-S-3-R-17',
              'medical-15-S-3-R-18',
              'medical-15-S-3-R-19',
              'medical-15-S-3-R-20',
              'medical-15-S-3-R-21',
              'medical-15-S-4',
              'medical-15-S-4-R-0',
              'medical-15-S-4-R-1',
              'medical-15-S-4-R-2',
              'medical-15-S-4-R-3',
              'medical-15-S-4-R-4',
              'medical-15-S-4-R-5',
              'medical-15-S-4-R-6',
              'medical-15-S-4-R-7',
              'medical-15-S-4-R-8',
              'medical-15-S-4-R-9',
              'medical-15-S-4-R-10',
              'medical-15-S-4-R-11',
              'medical-15-S-4-R-12',
              'medical-15-S-4-R-13',
              'medical-15-S-4-R-14',
              'medical-15-S-4-R-15',
              'medical-15-S-4-R-16',
              'medical-15-S-4-R-17',
              'medical-15-S-4-R-18',
              'medical-16-S-0',
              'medical-16-S-0-R-2',
              'medical-16-S-0-R-3',
              'medical-16-S-0-R-4',
              'medical-16-S-0-R-5',
              'medical-16-S-0-R-6',
              'medical-16-S-0-R-8',
              'medical-16-S-0-R-9',
              'medical-16-S-0-R-10',
              'medical-16-S-0-R-11',
              'medical-16-S-0-R-12',
              'medical-16-S-0-R-13',
              'medical-16-S-1-R-15',
              'medical-16-S-1-R-16',
              'medical-16-S-1-R-17',
              'medical-16-S-1-R-18',
              'medical-16-S-2',
              'medical-16-S-2-R-0',
              'medical-16-S-2-R-1',
              'medical-16-S-2-R-2',
              'medical-16-S-2-R-3',
              'medical-16-S-2-R-4',
              'medical-16-S-2-R-5',
              'medical-16-S-2-R-6',
              'medical-16-S-2-R-7',
              'medical-16-S-3-R-0',
              'medical-16-S-3-R-1',
              'medical-16-S-3-R-3',
              'medical-16-S-3-R-4',
              'medical-16-S-3-R-10',
              'medical-17-S-0-R-1',
              'medical-17-S-0-R-3',
              'medical-17-S-0-R-4',
              'medical-17-S-0-R-5',
              'medical-17-S-0-R-7',
              'medical-17-S-1-R-0',
              'medical-17-S-2',
              'medical-17-S-2-R-0',
              'medical-17-S-2-R-1',
              'medical-17-S-2-R-2',
              'medical-17-S-2-R-3',
              'medical-17-S-2-R-4',
              'medical-17-S-2-R-5',
              'medical-17-S-2-R-6',
              'medical-17-S-2-R-7',
              'medical-17-S-2-R-8',
              'medical-17-S-4',
              'medical-17-S-4-R-0',
              'medical-19-S-2-R-0',
              'medical-19-S-3-R-1',
              'medical-19-S-3-R-2',
              'medical-20-S-1',
              'medical-20-S-1-R-0',
              'medical-20-S-1-R-1',
              'medical-20-S-1-R-2',
              'medical-20-S-1-R-3',
              'medical-20-S-1-R-4',
              'medical-20-S-1-R-5',
              'medical-20-S-1-R-6',
              'medical-20-S-1-R-7',
              'medical-20-S-1-R-9',
              'medical-20-S-1-R-10',
              'medical-20-S-1-R-11',
              'medical-20-S-1-R-12',
              'medical-20-S-1-R-13',
              'medical-20-S-2',
              'medical-20-S-2-R-1',
              'medical-20-S-2-R-2',
              'medical-20-S-2-R-3',
              'medical-20-S-2-R-4',
              'medical-20-S-3',
              'medical-20-S-3-R-0',
              'medical-20-S-3-R-5',
              'medical-20-S-3-R-7',
              'medical-21-S-0',
              'medical-21-S-0-R-2',
              'medical-21-S-0-R-3',
              'medical-21-S-0-R-5',
              'medical-21-S-0-R-6',
              'medical-21-S-0-R-7',
              'medical-21-S-0-R-10',
              'medical-21-S-1-R-0',
              'medical-21-S-2',
              'medical-21-S-2-R-0',
              'medical-21-S-2-R-1',
              'medical-21-S-2-R-2',
              'medical-21-S-2-R-3',
              'medical-21-S-2-R-4',
              'medical-21-S-2-R-5',
              'medical-22-S-7',
              'medical-22-S-7-R-0',
              'medical-22-S-7-R-1',
              'medical-22-S-7-R-2',
              'medical-22-S-7-R-3',
              'medical-22-S-7-R-4',
              'medical-22-S-7-R-5',
              'medical-22-S-9-R-1',
              'medical-22-S-9-R-3',
              'medical-23-S-1',
              'medical-23-S-1-R-0',
              'medical-23-S-1-R-1',
              'medical-23-S-1-R-2',
              'medical-23-S-1-R-3',
              'medical-23-S-1-R-4',
              'medical-23-S-1-R-5',
              'medical-23-S-1-R-6',
              'medical-23-S-1-R-7',
              'medical-23-S-2',
              'medical-23-S-2-R-0',
              'medical-23-S-2-R-1',
              'medical-23-S-2-R-2',
              'medical-23-S-2-R-3',
              'medical-23-S-2-R-4',
              'medical-23-S-2-R-5',
              'medical-23-S-2-R-6',
              'medical-23-S-2-R-7',
              'medical-23-S-2-R-8',
              'medical-23-S-3',
              'medical-23-S-3-R-0',
              'medical-23-S-3-R-1',
              'medical-23-S-3-R-2',
              'medical-23-S-3-R-4',
              'medical-23-S-3-R-5',
              'medical-23-S-3-R-6',
              'medical-23-S-3-R-7',
              'medical-23-S-3-R-9',
              'medical-23-S-4',
              'medical-23-S-4-R-0',
              'medical-23-S-4-R-1',
              'medical-23-S-4-R-3',
              'medical-23-S-4-R-4',
              'medical-23-S-5',
              'medical-23-S-5-R-0',
              'medical-23-S-5-R-1',
              'medical-23-S-5-R-2',
              'medical-23-S-5-R-3',
              'medical-23-S-5-R-4',
              'medical-23-S-5-R-5',
              'medical-23-S-5-R-9',
              'medical-23-S-5-R-10',
              'medical-23-S-5-R-11',
              'medical-23-S-5-R-12',
              'medical-23-S-6',
              'medical-23-S-6-R-0',
              'medical-23-S-6-R-4',
              'medical-23-S-6-R-5',
              'medical-23-S-6-R-6',
              'medical-23-S-6-R-7',
              'medical-23-S-6-R-9',
              'medical-23-S-6-R-10',
              'medical-23-S-6-R-11',
              'medical-23-S-6-R-12',
              'medical-23-S-6-R-13',
              'medical-23-S-6-R-14',
              'medical-23-S-6-R-15',
              'medical-23-S-6-R-16',
              'medical-23-S-6-R-17',
              'medical-24-S-1',
              'medical-24-S-1-R-0',
              'medical-24-S-1-R-1',
              'medical-24-S-1-R-2',
              'medical-24-S-2',
              'medical-24-S-2-R-0',
              'medical-24-S-2-R-1',
              'medical-24-S-2-R-2',
              'medical-24-S-2-R-3',
              'medical-24-S-2-R-4',
              'medical-24-S-2-R-5',
              'medical-24-S-2-R-6',
              'medical-24-S-2-R-7',
              'medical-24-S-2-R-8',
              'medical-24-S-2-R-9',
              'medical-24-S-2-R-10',
              'medical-24-S-2-R-11',
              'medical-24-S-4-R-9',
              'medical-24-S-4-R-10',
              'medical-24-S-4-R-11',
              'medical-26-S-2-R-18',
              'medical-27-S-2',
              'medical-27-S-2-R-0',
              'medical-27-S-2-R-1',
              'medical-27-S-2-R-2',
              'medical-27-S-2-R-3',
              'medical-27-S-2-R-4',
              'medical-27-S-2-R-5',
              'medical-27-S-2-R-6',
              'medical-27-S-2-R-7',
              'medical-27-S-2-R-8',
              'medical-27-S-2-R-9',
              'medical-28-S-4-R-7',
              'medical-28-S-4-R-8',
              'medical-28-S-4-R-9',
              'medical-29-S-0',
              'medical-29-S-0-R-0',
              'medical-29-S-0-R-1',
              'medical-29-S-0-R-2',
              'medical-29-S-0-R-3',
              'medical-29-S-0-R-5',
              'medical-29-S-2-R-4',
              'medical-29-S-4-R-6',
              'medical-29-S-5-R-0',
              'medical-32-S-3',
              'medical-32-S-3-R-0',
              'medical-32-S-3-R-1',
              'medical-32-S-3-R-2',
              'medical-32-S-3-R-3',
              'medical-32-S-3-R-4',
              'medical-32-S-3-R-5',
              'medical-33-S-1-R-0',
              'medical-33-S-3',
              'medical-33-S-3-R-0',
              'medical-33-S-3-R-1',
              'medical-33-S-3-R-2',
              'medical-33-S-3-R-3',
              'medical-33-S-3-R-4',
              'medical-33-S-4',
              'medical-33-S-4-R-0',
              'medical-34-S-4',
              'medical-34-S-4-R-0',
              'medical-34-S-4-R-1',
              'medical-34-S-4-R-5',
              'medical-35-S-2-R-3',
              'medical-38-S-1-R-0',
              'medical-38-S-1-R-5',
              'medical-38-S-1-R-6',
              'medical-39-S-2-R-0',
              'medical-39-S-3-R-1',
              'medical-41-S-1-R-4',
              'medical-41-S-1-R-5',
              'medical-42-S-0-R-3',
              'medical-42-S-0-R-6',
              'medical-42-S-2-R-0',
              'medical-42-S-3',
              'medical-42-S-3-R-0',
              'medical-42-S-3-R-1',
              'medical-42-S-3-R-2',
              'medical-42-S-4',
              'medical-42-S-4-R-0',
              'medical-42-S-4-R-1',
              'medical-42-S-4-R-2',
              'medical-42-S-4-R-3',
              'medical-42-S-4-R-4',
              'medical-42-S-4-R-5',
              'medical-42-S-4-R-7',
              'medical-42-S-4-R-9',
              'medical-43-S-0',
              'medical-43-S-0-R-0',
              'medical-43-S-0-R-1',
              'medical-43-S-0-R-3',
              'medical-43-S-0-R-4',
              'medical-43-S-0-R-5',
              'medical-43-S-0-R-6',
              'medical-43-S-0-R-7',
              'medical-43-S-0-R-8',
              'medical-43-S-0-R-9',

In [9]:
from google import genai

with open(f"{root_path}/API_KEY.txt", "r", encoding="utf-8") as f:
    API_KEY = f.read()
    
def call_gemini(text):
    client = genai.Client(api_key = API_KEY)
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=text,
    )
    return response.text

In [10]:
import time
from tqdm import tqdm

In [11]:
medical_communities_response = {}

In [12]:
from graphs.prompt.high_level_elements_generation_prompt import high_level_elements_generation_prompt

for c in tqdm(communities_medical):
    if f'medical-H-{c}' in medical_communities_response:
        continue
    semantic_count = 0
    nodes_id = communities_medical[c]
    content = []
    for nid in nodes_id:
        node = medical_g2[nid]
        if node.node_type == "S":
            semantic_count+=1
        if node.node_type in ["R", "N"]:
            continue
        content.append(node.content)
    if semantic_count < 2:
        continue
    else:
        content = "\n".join(content)
        response = call_gemini(high_level_elements_generation_prompt(content))
        medical_communities_response[f'medical-H-{c}'] = response
        time.sleep(2)

100%|██████████| 233/233 [17:04<00:00,  4.40s/it]

In [13]:
medical_communities_overview = {}

In [14]:
from graphs.prompt.high_level_overview_generation_prompt import high_level_overview_prompt
for element_id, element in tqdm(medical_communities_response.items()):
    overview_id = f"{element_id}-O-0"
    if overview_id in medical_communities_overview:
        continue
    overview = call_gemini(high_level_overview_prompt(element))
    medical_communities_overview[overview_id] = overview

100%|██████████| 41/41 [04:27<00:00,  6.53s/it]

In [15]:
import pandas as pd
medical_df = pd.DataFrame(list(medical_communities_response.items()), columns=["node_id", "community_summary"])
medical_df.to_parquet("data//nodes/community/medical_communities_summary.parquet")
medical_df = pd.read_parquet("data/nodes/community/medical_communities_summary.parquet")
medical_df

         node_id                                  community_summary
0   medical-H-17  Here are distinct categories of high-level inf...
1   medical-H-11  Here are five distinct categories of high-leve...
2   medical-H-20  Here are the distinct categories of high-level...
3    medical-H-7  Here are distinct categories of high-level inf...
4   medical-H-27  Here are distinct categories of high-level inf...
5    medical-H-1  Here are distinct categories of high-level inf...
6   medical-H-23  Here are distinct categories of high-level inf...
7   medical-H-22  Here are distinct categories of high-level inf...
8    medical-H-4  Here are distinct categories of high-level inf...
9    medical-H-6  Here are distinct categories of high-level inf...
10   medical-H-5  The clustered text data provides a comprehensi...
11  medical-H-25  Here are the distinct categories of high-level...
12  medical-H-36  Here are distinct categories of high-level inf...
13   medical-H-3  Here are the distinct categories of high-level...
14  medical-H-26  Here are distinct categories of high-level inf...
15  medical-H-19  Here are distinct categories of high-level inf...
16  medical-H-21  Here are distinct categories of high-level inf...
17  medical-H-24  Here are distinct categories of high-level inf...
18  medical-H-14  Here are distinct categories of high-level inf...
19   medical-H-8  Here are the distinct categories of high-level...
20  medical-H-15  The provided text cluster primarily focuses on...
21   medical-H-9  Here are distinct categories of high-level inf...
22  medical-H-28  Here are distinct categories of high-level inf...
23  medical-H-18  Here are the distinct categories of high-level...
24  medical-H-12  Here are the distinct categories of high-level...
25   medical-H-0  The provided text cluster describes various as...
26  medical-H-30  Here are the distinct categories of high-level...
27  medical-H-13  Here are distinct categories of high-level inf...
28   medical-H-2  Here are distinct categories of high-level inf...
29  medical-H-10  Here are the distinct categories of high-level...
30  medical-H-16  Here are the distinct categories of high-level...
31  medical-H-31  Here are distinct categories of high-level inf...
32  medical-H-29  Here are distinct categories of high-level inf...
33  medical-H-35  Here are the distinct categories of high-level...
34  medical-H-33  Here are the distinct categories of high-level...
35  medical-H-37  Here are distinct categories of high-level inf...
36  medical-H-32  Here are distinct categories of high-level inf...
37  medical-H-38  Here are the distinct categories of high-level...
38  medical-H-34  Here are the distinct categories of high-level...
39  medical-H-39  Here are the distinct categories of high-level...
40  medical-H-40  Here are the distinct categories of high-level...

In [16]:
medical_overview = pd.DataFrame(list(medical_communities_overview.items()), columns=["node_id", "community_overview"])
medical_overview.to_parquet("data/nodes/community/medical_communities_overview.parquet")
medical_overview = pd.read_parquet("data/nodes/community/medical_communities_overview.parquet")
medical_overview

             node_id                                 community_overview
0   medical-H-17-O-0  Skin Cancer: Basal Cell Carcinoma, Squamous Ce...
1   medical-H-11-O-0  Head and Neck Cancer: Anatomy, Diagnosis, Trea...
2   medical-H-20-O-0  Cancer Management: Surgical Treatment, Staging...
3    medical-H-7-O-0  Lymphatic System, Cancer Metastasis, Breast Ca...
4   medical-H-27-O-0  NCCN Guidelines: Cancer Patient Empowerment, P...
5    medical-H-1-O-0  Cancer Genetics, Mutations, Genomic Testing, a...
6   medical-H-23-O-0  Cancer: Risk Factors, Pathogenesis, Staging, S...
7   medical-H-22-O-0  HPV-Related Cancers, Biomarkers, Treatment Sid...
8    medical-H-4-O-0       Patient Health Management, Advocacy, Support
9    medical-H-6-O-0  Cancer Care: Diagnostics, Personalized Treatme...
10   medical-H-5-O-0  Cancer Diagnostics, Staging, Treatment, Progno...
11  medical-H-25-O-0  Adrenal Glands, Hormones, Tumors, Breast Cance...
12  medical-H-36-O-0  Kidney Cancer: Types, Subtypes, Sarcomatoid Fe...
13   medical-H-3-O-0  Medical Imaging Modalities, Cancer Management,...
14  medical-H-26-O-0  Thyroid Gland, Thyroid Cancer, Diagnosis, Trea...
15  medical-H-19-O-0  Colorectal & Pelvic Cancers: Etiology, Anatomy...
16  medical-H-21-O-0  Patient Care Elements: Symptoms, Medical Histo...
17  medical-H-24-O-0  Cancer Tumors: Definition, TNM Staging, Invasi...
18  medical-H-14-O-0  Cancer Biopsy: Procedures, Analysis, and Clini...
19   medical-H-8-O-0  Cancer Care: Emotional Support, Fertility, Tre...
20  medical-H-15-O-0  Prostate Cancer: Disease, Risk Factors, Diagno...
21   medical-H-9-O-0  Digestive System: GI Organ Anatomy, Function, ...
22  medical-H-28-O-0  Personalized Cancer Management: Treatment, Sur...
23  medical-H-18-O-0         Cancer Diagnostics, Biology, and Treatment
24  medical-H-12-O-0  Central Nervous System Cancers: Spectrum, Diag...
25   medical-H-0-O-0  Blood, Bone Marrow, Immune System: Cancers, Di...
26  medical-H-30-O-0  Bone Cancer: Diagnosis, Staging, Treatment, Bo...
27  medical-H-13-O-0  Female Reproductive System: Gynecological Canc...
28   medical-H-2-O-0  Multimodal Cancer Therapies, Precision Oncolog...
29  medical-H-10-O-0  Bladder Cancer: Urinary System Anatomy, Etiolo...
30  medical-H-16-O-0  Cancer Clinical Trials: Purpose, Phases, Patie...
31  medical-H-31-O-0  Cancer Care: Smoking, Vaping, Lifestyle, Thera...
32  medical-H-29-O-0  Oncology Grading, Lymphoma Biology, and Therap...
33  medical-H-35-O-0  CML and Ewing Sarcoma: Genetic Basis, Chromoso...
34  medical-H-33-O-0  Acute Lymphoblastic Leukemia Subtypes, Lymphob...
35  medical-H-37-O-0  Personalized Patient Care, Quality of Life, Cl...
36  medical-H-32-O-0  Integrated Patient Care: Teams, Professionals,...
37  medical-H-38-O-0  Pre-treatment Diagnostics, Integrated Supporti...
38  medical-H-34-O-0  AML Chemotherapy and Targeted Therapies: Anthr...
39  medical-H-39-O-0  Rare Ovarian Cancers (LCOCs) Nomenclature, Cel...
40  medical-H-40-O-0  Cancer Biomarker Identification, Diagnosis, Pe...

In [17]:
with open(f"{root_path}/graphs/data/nodes/community/medical_communities.pkl", "wb") as f:
    pickle.dump(communities_medical, f)
with open(f"{root_path}/graphs/data/nodes/community/medical_communities.pkl", "rb") as f:
    communities_medical_loaded = pickle.load(f)

In [18]:
communities_medical_loaded

defaultdict(list,
            {17: ['medical-0-S-0',
              'medical-0-S-0-R-0',
              'medical-0-S-0-R-1',
              'medical-0-S-0-R-2',
              'medical-0-S-0-R-3',
              'medical-0-S-0-R-4',
              'medical-0-S-1',
              'medical-0-S-1-R-0',
              'medical-0-S-1-R-1',
              'medical-0-S-1-R-2',
              'medical-0-S-1-R-3',
              'medical-0-S-1-R-4',
              'medical-0-S-1-R-5',
              'medical-0-S-1-R-6',
              'medical-0-S-1-R-7',
              'medical-0-S-1-R-8',
              'medical-0-S-1-R-9',
              'medical-0-S-1-R-10',
              'medical-0-S-1-R-11',
              'medical-0-S-1-R-12',
              'medical-0-S-2-R-1',
              'medical-0-S-2-R-2',
              'medical-0-S-3',
              'medical-0-S-3-R-0',
              'medical-0-S-3-R-1',
              'medical-0-S-3-R-2',
              'medical-0-S-3-R-3',
              'medical-0-S-3-R-4',
              'medical-0-S-3-R-5',
              'medical-0-S-3-R-6',
              'medical-0-S-3-R-7',
              'medical-0-S-3-R-8',
              'medical-0-S-3-R-9',
              'medical-0-S-3-R-10',
              'medical-0-S-3-R-11',
              'medical-0-S-3-R-12',
              'medical-0-S-3-R-13',
              'medical-0-S-3-R-14',
              'medical-0-S-3-R-15',
              'medical-0-S-3-R-16',
              'medical-0-S-3-R-17',
              'medical-0-S-3-R-18',
              'medical-0-S-3-R-19',
              'medical-0-S-3-R-20',
              'medical-0-S-3-R-21',
              'medical-0-S-3-R-22',
              'medical-0-S-3-R-23',
              'medical-0-S-3-R-24',
              'medical-0-S-3-R-25',
              'medical-0-S-3-R-26',
              'medical-0-S-3-R-27',
              'medical-1-S-0',
              'medical-1-S-0-R-1',
              'medical-1-S-0-R-2',
              'medical-1-S-0-R-3',
              'medical-1-S-0-R-4',
              'medical-1-S-0-R-5',
              'medical-1-S-0-R-6',
              'medical-1-S-0-R-7',
              'medical-1-S-0-R-8',
              'medical-1-S-0-R-9',
              'medical-1-S-0-R-10',
              'medical-1-S-1',
              'medical-1-S-1-R-0',
              'medical-1-S-2',
              'medical-1-S-2-R-0',
              'medical-1-S-2-R-1',
              'medical-1-S-2-R-2',
              'medical-1-S-2-R-3',
              'medical-1-S-2-R-4',
              'medical-1-S-2-R-5',
              'medical-1-S-2-R-6',
              'medical-1-S-2-R-7',
              'medical-1-S-2-R-8',
              'medical-1-S-2-R-9',
              'medical-1-S-2-R-10',
              'medical-1-S-2-R-11',
              'medical-1-S-2-R-12',
              'medical-1-S-2-R-13',
              'medical-1-S-2-R-14',
              'medical-1-S-2-R-15',
              'medical-1-S-2-R-16',
              'medical-1-S-2-R-17',
              'medical-1-S-3',
              'medical-1-S-3-R-0',
              'medical-1-S-3-R-1',
              'medical-1-S-3-R-2',
              'medical-1-S-4',
              'medical-1-S-4-R-0',
              'medical-1-S-4-R-1',
              'medical-1-S-4-R-2',
              'medical-1-S-4-R-3',
              'medical-1-S-4-R-6',
              'medical-1-S-4-R-7',
              'medical-2-S-0',
              'medical-2-S-0-R-0',
              'medical-2-S-0-R-1',
              'medical-2-S-0-R-2',
              'medical-2-S-0-R-3',
              'medical-2-S-0-R-4',
              'medical-2-S-0-R-8',
              'medical-2-S-0-R-9',
              'medical-2-S-0-R-10',
              'medical-2-S-0-R-11',
              'medical-2-S-0-R-12',
              'medical-2-S-0-R-13',
              'medical-2-S-0-R-14',
              'medical-2-S-0-R-15',
              'medical-2-S-0-R-17',
              'medical-2-S-0-R-18',
              'medical-2-S-0-R-19',
              'medical-2-S-0-R-20',
              'medical-2-S-0-R-21',
              'medical-2-S-1',
              'medical-2-S-1-R-0',
              'medical-2-S-1-R-1',
              'medical-2-S-1-R-2',
              'medical-2-S-1-R-4',
              'medical-2-S-1-R-5',
              'medical-2-S-1-R-6',
              'medical-2-S-1-R-7',
              'medical-2-S-1-R-8',
              'medical-2-S-1-R-11',
              'medical-2-S-1-R-12',
              'medical-2-S-1-R-14',
              'medical-3-S-0',
              'medical-3-S-0-R-0',
              'medical-3-S-0-R-1',
              'medical-3-S-0-R-2',
              'medical-3-S-0-R-3',
              'medical-3-S-0-R-4',
              'medical-3-S-3',
              'medical-3-S-3-R-1',
              'medical-3-S-3-R-2',
              'medical-3-S-3-R-3',
              'medical-3-S-3-R-4',
              'medical-3-S-3-R-5',
              'medical-3-S-3-R-6',
              'medical-3-S-3-R-7',
              'medical-4-S-0-R-1',
              'medical-4-S-0-R-2',
              'medical-4-S-0-R-4',
              'medical-4-S-0-R-5',
              'medical-4-S-0-R-6',
              'medical-10-S-0-R-6',
              'medical-13-S-0',
              'medical-13-S-0-R-0',
              'medical-13-S-0-R-1',
              'medical-13-S-0-R-2',
              'medical-13-S-0-R-3',
              'medical-13-S-0-R-4',
              'medical-13-S-0-R-5',
              'medical-13-S-0-R-6',
              'medical-13-S-0-R-7',
              'medical-13-S-0-R-8',
              'medical-13-S-0-R-9',
              'medical-13-S-0-R-10',
              'medical-13-S-0-R-11',
              'medical-13-S-0-R-12',
              'medical-13-S-0-R-13',
              'medical-13-S-0-R-14',
              'medical-13-S-1',
              'medical-13-S-1-R-0',
              'medical-13-S-1-R-1',
              'medical-13-S-1-R-2',
              'medical-13-S-1-R-6',
              'medical-13-S-1-R-7',
              'medical-13-S-1-R-8',
              'medical-13-S-2',
              'medical-13-S-2-R-0',
              'medical-13-S-2-R-1',
              'medical-13-S-2-R-2',
              'medical-13-S-2-R-3',
              'medical-13-S-2-R-4',
              'medical-13-S-2-R-5',
              'medical-13-S-3',
              'medical-13-S-3-R-0',
              'medical-13-S-3-R-1',
              'medical-13-S-3-R-2',
              'medical-13-S-3-R-3',
              'medical-13-S-3-R-4',
              'medical-13-S-3-R-5',
              'medical-13-S-3-R-6',
              'medical-13-S-3-R-7',
              'medical-13-S-3-R-8',
              'medical-13-S-3-R-9',
              'medical-13-S-3-R-10',
              'medical-13-S-3-R-11',
              'medical-13-S-3-R-12',
              'medical-13-S-3-R-13',
              'medical-13-S-3-R-14',
              'medical-13-S-3-R-15',
              'medical-13-S-3-R-16',
              'medical-13-S-4',
              'medical-13-S-4-R-0',
              'medical-13-S-4-R-1',
              'medical-13-S-4-R-2',
              'medical-13-S-4-R-3',
              'medical-13-S-4-R-4',
              'medical-13-S-4-R-5',
              'medical-13-S-4-R-6',
              'medical-13-S-4-R-7',
              'medical-13-S-4-R-8',
              'medical-13-S-4-R-9',
              'medical-13-S-4-R-10',
              'medical-13-S-4-R-11',
              'medical-13-S-4-R-12',
              'medical-13-S-4-R-13',
              'medical-13-S-4-R-14',
              'medical-13-S-4-R-15',
              'medical-13-S-4-R-16',
              'medical-13-S-4-R-17',
              'medical-14-S-0',
              'medical-14-S-0-R-0',
              'medical-14-S-0-R-1',
              'medical-14-S-0-R-2',
              'medical-14-S-0-R-3',
              'medical-14-S-0-R-4',
              'medical-14-S-0-R-5',
              'medical-14-S-0-R-6',
              'medical-14-S-0-R-7',
              'medical-14-S-0-R-8',
              'medical-14-S-0-R-9',
              'medical-14-S-0-R-10',
              'medical-14-S-0-R-11',
              'medical-14-S-0-R-12',
              'medical-14-S-0-R-13',
              'medical-14-S-0-R-14',
              'medical-14-S-0-R-15',
              'medical-14-S-0-R-16',
              'medical-14-S-1-R-2',
              'medical-14-S-2',
              'medical-14-S-2-R-0',
              'medical-14-S-2-R-1',
              'medical-14-S-2-R-2',
              'medical-14-S-2-R-3',
              'medical-14-S-2-R-4',
              'medical-14-S-2-R-5',
              'medical-14-S-2-R-6',
              'medical-14-S-2-R-7',
              'medical-14-S-2-R-8',
              'medical-14-S-3',
              'medical-14-S-3-R-0',
              'medical-14-S-3-R-1',
              'medical-14-S-3-R-2',
              'medical-14-S-3-R-3',
              'medical-14-S-5',
              'medical-14-S-5-R-0',
              'medical-14-S-5-R-1',
              'medical-14-S-5-R-2',
              'medical-14-S-5-R-3',
              'medical-14-S-5-R-4',
              'medical-14-S-5-R-5',
              'medical-14-S-5-R-6',
              'medical-15-S-0',
              'medical-15-S-0-R-0',
              'medical-15-S-0-R-1',
              'medical-15-S-0-R-2',
              'medical-15-S-2',
              'medical-15-S-2-R-0',
              'medical-15-S-2-R-1',
              'medical-15-S-2-R-2',
              'medical-15-S-2-R-3',
              'medical-15-S-2-R-4',
              'medical-15-S-3',
              'medical-15-S-3-R-0',
              'medical-15-S-3-R-1',
              'medical-15-S-3-R-2',
              'medical-15-S-3-R-3',
              'medical-15-S-3-R-4',
              'medical-15-S-3-R-5',
              'medical-15-S-3-R-6',
              'medical-15-S-3-R-7',
              'medical-15-S-3-R-8',
              'medical-15-S-3-R-9',
              'medical-15-S-3-R-10',
              'medical-15-S-3-R-12',
              'medical-15-S-3-R-13',
              'medical-15-S-3-R-14',
              'medical-15-S-3-R-15',
              'medical-15-S-3-R-16',
              'medical-15-S-3-R-17',
              'medical-15-S-3-R-18',
              'medical-15-S-3-R-19',
              'medical-15-S-3-R-20',
              'medical-15-S-3-R-21',
              'medical-15-S-4',
              'medical-15-S-4-R-0',
              'medical-15-S-4-R-1',
              'medical-15-S-4-R-2',
              'medical-15-S-4-R-3',
              'medical-15-S-4-R-4',
              'medical-15-S-4-R-5',
              'medical-15-S-4-R-6',
              'medical-15-S-4-R-7',
              'medical-15-S-4-R-8',
              'medical-15-S-4-R-9',
              'medical-15-S-4-R-10',
              'medical-15-S-4-R-11',
              'medical-15-S-4-R-12',
              'medical-15-S-4-R-13',
              'medical-15-S-4-R-14',
              'medical-15-S-4-R-15',
              'medical-15-S-4-R-16',
              'medical-15-S-4-R-17',
              'medical-15-S-4-R-18',
              'medical-16-S-0',
              'medical-16-S-0-R-2',
              'medical-16-S-0-R-3',
              'medical-16-S-0-R-4',
              'medical-16-S-0-R-5',
              'medical-16-S-0-R-6',
              'medical-16-S-0-R-8',
              'medical-16-S-0-R-9',
              'medical-16-S-0-R-10',
              'medical-16-S-0-R-11',
              'medical-16-S-0-R-12',
              'medical-16-S-0-R-13',
              'medical-16-S-1-R-15',
              'medical-16-S-1-R-16',
              'medical-16-S-1-R-17',
              'medical-16-S-1-R-18',
              'medical-16-S-2',
              'medical-16-S-2-R-0',
              'medical-16-S-2-R-1',
              'medical-16-S-2-R-2',
              'medical-16-S-2-R-3',
              'medical-16-S-2-R-4',
              'medical-16-S-2-R-5',
              'medical-16-S-2-R-6',
              'medical-16-S-2-R-7',
              'medical-16-S-3-R-0',
              'medical-16-S-3-R-1',
              'medical-16-S-3-R-3',
              'medical-16-S-3-R-4',
              'medical-16-S-3-R-10',
              'medical-17-S-0-R-1',
              'medical-17-S-0-R-3',
              'medical-17-S-0-R-4',
              'medical-17-S-0-R-5',
              'medical-17-S-0-R-7',
              'medical-17-S-1-R-0',
              'medical-17-S-2',
              'medical-17-S-2-R-0',
              'medical-17-S-2-R-1',
              'medical-17-S-2-R-2',
              'medical-17-S-2-R-3',
              'medical-17-S-2-R-4',
              'medical-17-S-2-R-5',
              'medical-17-S-2-R-6',
              'medical-17-S-2-R-7',
              'medical-17-S-2-R-8',
              'medical-17-S-4',
              'medical-17-S-4-R-0',
              'medical-19-S-2-R-0',
              'medical-19-S-3-R-1',
              'medical-19-S-3-R-2',
              'medical-20-S-1',
              'medical-20-S-1-R-0',
              'medical-20-S-1-R-1',
              'medical-20-S-1-R-2',
              'medical-20-S-1-R-3',
              'medical-20-S-1-R-4',
              'medical-20-S-1-R-5',
              'medical-20-S-1-R-6',
              'medical-20-S-1-R-7',
              'medical-20-S-1-R-9',
              'medical-20-S-1-R-10',
              'medical-20-S-1-R-11',
              'medical-20-S-1-R-12',
              'medical-20-S-1-R-13',
              'medical-20-S-2',
              'medical-20-S-2-R-1',
              'medical-20-S-2-R-2',
              'medical-20-S-2-R-3',
              'medical-20-S-2-R-4',
              'medical-20-S-3',
              'medical-20-S-3-R-0',
              'medical-20-S-3-R-5',
              'medical-20-S-3-R-7',
              'medical-21-S-0',
              'medical-21-S-0-R-2',
              'medical-21-S-0-R-3',
              'medical-21-S-0-R-5',
              'medical-21-S-0-R-6',
              'medical-21-S-0-R-7',
              'medical-21-S-0-R-10',
              'medical-21-S-1-R-0',
              'medical-21-S-2',
              'medical-21-S-2-R-0',
              'medical-21-S-2-R-1',
              'medical-21-S-2-R-2',
              'medical-21-S-2-R-3',
              'medical-21-S-2-R-4',
              'medical-21-S-2-R-5',
              'medical-22-S-7',
              'medical-22-S-7-R-0',
              'medical-22-S-7-R-1',
              'medical-22-S-7-R-2',
              'medical-22-S-7-R-3',
              'medical-22-S-7-R-4',
              'medical-22-S-7-R-5',
              'medical-22-S-9-R-1',
              'medical-22-S-9-R-3',
              'medical-23-S-1',
              'medical-23-S-1-R-0',
              'medical-23-S-1-R-1',
              'medical-23-S-1-R-2',
              'medical-23-S-1-R-3',
              'medical-23-S-1-R-4',
              'medical-23-S-1-R-5',
              'medical-23-S-1-R-6',
              'medical-23-S-1-R-7',
              'medical-23-S-2',
              'medical-23-S-2-R-0',
              'medical-23-S-2-R-1',
              'medical-23-S-2-R-2',
              'medical-23-S-2-R-3',
              'medical-23-S-2-R-4',
              'medical-23-S-2-R-5',
              'medical-23-S-2-R-6',
              'medical-23-S-2-R-7',
              'medical-23-S-2-R-8',
              'medical-23-S-3',
              'medical-23-S-3-R-0',
              'medical-23-S-3-R-1',
              'medical-23-S-3-R-2',
              'medical-23-S-3-R-4',
              'medical-23-S-3-R-5',
              'medical-23-S-3-R-6',
              'medical-23-S-3-R-7',
              'medical-23-S-3-R-9',
              'medical-23-S-4',
              'medical-23-S-4-R-0',
              'medical-23-S-4-R-1',
              'medical-23-S-4-R-3',
              'medical-23-S-4-R-4',
              'medical-23-S-5',
              'medical-23-S-5-R-0',
              'medical-23-S-5-R-1',
              'medical-23-S-5-R-2',
              'medical-23-S-5-R-3',
              'medical-23-S-5-R-4',
              'medical-23-S-5-R-5',
              'medical-23-S-5-R-9',
              'medical-23-S-5-R-10',
              'medical-23-S-5-R-11',
              'medical-23-S-5-R-12',
              'medical-23-S-6',
              'medical-23-S-6-R-0',
              'medical-23-S-6-R-4',
              'medical-23-S-6-R-5',
              'medical-23-S-6-R-6',
              'medical-23-S-6-R-7',
              'medical-23-S-6-R-9',
              'medical-23-S-6-R-10',
              'medical-23-S-6-R-11',
              'medical-23-S-6-R-12',
              'medical-23-S-6-R-13',
              'medical-23-S-6-R-14',
              'medical-23-S-6-R-15',
              'medical-23-S-6-R-16',
              'medical-23-S-6-R-17',
              'medical-24-S-1',
              'medical-24-S-1-R-0',
              'medical-24-S-1-R-1',
              'medical-24-S-1-R-2',
              'medical-24-S-2',
              'medical-24-S-2-R-0',
              'medical-24-S-2-R-1',
              'medical-24-S-2-R-2',
              'medical-24-S-2-R-3',
              'medical-24-S-2-R-4',
              'medical-24-S-2-R-5',
              'medical-24-S-2-R-6',
              'medical-24-S-2-R-7',
              'medical-24-S-2-R-8',
              'medical-24-S-2-R-9',
              'medical-24-S-2-R-10',
              'medical-24-S-2-R-11',
              'medical-24-S-4-R-9',
              'medical-24-S-4-R-10',
              'medical-24-S-4-R-11',
              'medical-26-S-2-R-18',
              'medical-27-S-2',
              'medical-27-S-2-R-0',
              'medical-27-S-2-R-1',
              'medical-27-S-2-R-2',
              'medical-27-S-2-R-3',
              'medical-27-S-2-R-4',
              'medical-27-S-2-R-5',
              'medical-27-S-2-R-6',
              'medical-27-S-2-R-7',
              'medical-27-S-2-R-8',
              'medical-27-S-2-R-9',
              'medical-28-S-4-R-7',
              'medical-28-S-4-R-8',
              'medical-28-S-4-R-9',
              'medical-29-S-0',
              'medical-29-S-0-R-0',
              'medical-29-S-0-R-1',
              'medical-29-S-0-R-2',
              'medical-29-S-0-R-3',
              'medical-29-S-0-R-5',
              'medical-29-S-2-R-4',
              'medical-29-S-4-R-6',
              'medical-29-S-5-R-0',
              'medical-32-S-3',
              'medical-32-S-3-R-0',
              'medical-32-S-3-R-1',
              'medical-32-S-3-R-2',
              'medical-32-S-3-R-3',
              'medical-32-S-3-R-4',
              'medical-32-S-3-R-5',
              'medical-33-S-1-R-0',
              'medical-33-S-3',
              'medical-33-S-3-R-0',
              'medical-33-S-3-R-1',
              'medical-33-S-3-R-2',
              'medical-33-S-3-R-3',
              'medical-33-S-3-R-4',
              'medical-33-S-4',
              'medical-33-S-4-R-0',
              'medical-34-S-4',
              'medical-34-S-4-R-0',
              'medical-34-S-4-R-1',
              'medical-34-S-4-R-5',
              'medical-35-S-2-R-3',
              'medical-38-S-1-R-0',
              'medical-38-S-1-R-5',
              'medical-38-S-1-R-6',
              'medical-39-S-2-R-0',
              'medical-39-S-3-R-1',
              'medical-41-S-1-R-4',
              'medical-41-S-1-R-5',
              'medical-42-S-0-R-3',
              'medical-42-S-0-R-6',
              'medical-42-S-2-R-0',
              'medical-42-S-3',
              'medical-42-S-3-R-0',
              'medical-42-S-3-R-1',
              'medical-42-S-3-R-2',
              'medical-42-S-4',
              'medical-42-S-4-R-0',
              'medical-42-S-4-R-1',
              'medical-42-S-4-R-2',
              'medical-42-S-4-R-3',
              'medical-42-S-4-R-4',
              'medical-42-S-4-R-5',
              'medical-42-S-4-R-7',
              'medical-42-S-4-R-9',
              'medical-43-S-0',
              'medical-43-S-0-R-0',
              'medical-43-S-0-R-1',
              'medical-43-S-0-R-3',
              'medical-43-S-0-R-4',
              'medical-43-S-0-R-5',
              'medical-43-S-0-R-6',
              'medical-43-S-0-R-7',
              'medical-43-S-0-R-8',
              'medical-43-S-0-R-9',