# Notebook 7: H, O, T Nodes Insertion

This notebook integrates all generated **H**, **O**, and **T** nodes into the G2 graph, using the previously detected structural communities.

---

### 1. K-means Clustering of S and A Embeddings  
We apply the **K-means** algorithm to the embeddings of all **S** and **A** nodes to form  
**k = √(number of S and A nodes)** clusters.

For each **H** node, we then identify the **top 5 closest semantic clusters** based on centroid similarity.

---

### 2. Linking S/A Nodes to H Nodes  
Within each community:

If an **S** or **A** node belongs to one of the **top 5 semantic clusters** associated with an **H** node, that node is linked to the corresponding **H** node.

---

### 3. O Nodes Insertion  
We insert all **O** nodes (High-level Overview nodes) and link each **O** node to the **H** node from which its summary was produced.

The updated graph is saved as **G3 — community augmented graph**.

---

### 4. T Nodes Insertion  
We insert all **T** nodes (original text chunks) and connect each one to its child **S** nodes using the `source_id` attribute.  
This preserves the original textual meaning that may have been abstracted away during LLM-based semantic decomposition.

The final graph is saved as **G4 — text inserted graph**.

In [1]:
import os
dir_path = os.getcwd()
print("The directory of this script is:", dir_path)
root_path = os.path.dirname(dir_path)
print("The root directory is:", root_path)

The directory of this script is: c:\Users\HP\Desktop\Projects\NodeRAG\graphs
The root directory is: c:\Users\HP\Desktop\Projects\NodeRAG

In [2]:
import sys
sys.path.append(root_path)
from graphs.Node import Node

In [3]:
import pandas as pd
#H nodes
medical_summary = pd.read_parquet("data/nodes/community/medical_communities_summary.parquet")
medical_summary

         node_id                                  community_summary
0   medical-H-17  Here are distinct categories of high-level inf...
1   medical-H-11  Here are five distinct categories of high-leve...
2   medical-H-20  Here are the distinct categories of high-level...
3    medical-H-7  Here are distinct categories of high-level inf...
4   medical-H-27  Here are distinct categories of high-level inf...
5    medical-H-1  Here are distinct categories of high-level inf...
6   medical-H-23  Here are distinct categories of high-level inf...
7   medical-H-22  Here are distinct categories of high-level inf...
8    medical-H-4  Here are distinct categories of high-level inf...
9    medical-H-6  Here are distinct categories of high-level inf...
10   medical-H-5  The clustered text data provides a comprehensi...
11  medical-H-25  Here are the distinct categories of high-level...
12  medical-H-36  Here are distinct categories of high-level inf...
13   medical-H-3  Here are the distinct categories of high-level...
14  medical-H-26  Here are distinct categories of high-level inf...
15  medical-H-19  Here are distinct categories of high-level inf...
16  medical-H-21  Here are distinct categories of high-level inf...
17  medical-H-24  Here are distinct categories of high-level inf...
18  medical-H-14  Here are distinct categories of high-level inf...
19   medical-H-8  Here are the distinct categories of high-level...
20  medical-H-15  The provided text cluster primarily focuses on...
21   medical-H-9  Here are distinct categories of high-level inf...
22  medical-H-28  Here are distinct categories of high-level inf...
23  medical-H-18  Here are the distinct categories of high-level...
24  medical-H-12  Here are the distinct categories of high-level...
25   medical-H-0  The provided text cluster describes various as...
26  medical-H-30  Here are the distinct categories of high-level...
27  medical-H-13  Here are distinct categories of high-level inf...
28   medical-H-2  Here are distinct categories of high-level inf...
29  medical-H-10  Here are the distinct categories of high-level...
30  medical-H-16  Here are the distinct categories of high-level...
31  medical-H-31  Here are distinct categories of high-level inf...
32  medical-H-29  Here are distinct categories of high-level inf...
33  medical-H-35  Here are the distinct categories of high-level...
34  medical-H-33  Here are the distinct categories of high-level...
35  medical-H-37  Here are distinct categories of high-level inf...
36  medical-H-32  Here are distinct categories of high-level inf...
37  medical-H-38  Here are the distinct categories of high-level...
38  medical-H-34  Here are the distinct categories of high-level...
39  medical-H-39  Here are the distinct categories of high-level...
40  medical-H-40  Here are the distinct categories of high-level...

In [4]:
#O nodes
medical_overview = pd.read_parquet("data/nodes/community/medical_communities_overview.parquet")
medical_overview

             node_id                                 community_overview
0   medical-H-17-O-0  Skin Cancer: Basal Cell Carcinoma, Squamous Ce...
1   medical-H-11-O-0  Head and Neck Cancer: Anatomy, Diagnosis, Trea...
2   medical-H-20-O-0  Cancer Management: Surgical Treatment, Staging...
3    medical-H-7-O-0  Lymphatic System, Cancer Metastasis, Breast Ca...
4   medical-H-27-O-0  NCCN Guidelines: Cancer Patient Empowerment, P...
5    medical-H-1-O-0  Cancer Genetics, Mutations, Genomic Testing, a...
6   medical-H-23-O-0  Cancer: Risk Factors, Pathogenesis, Staging, S...
7   medical-H-22-O-0  HPV-Related Cancers, Biomarkers, Treatment Sid...
8    medical-H-4-O-0       Patient Health Management, Advocacy, Support
9    medical-H-6-O-0  Cancer Care: Diagnostics, Personalized Treatme...
10   medical-H-5-O-0  Cancer Diagnostics, Staging, Treatment, Progno...
11  medical-H-25-O-0  Adrenal Glands, Hormones, Tumors, Breast Cance...
12  medical-H-36-O-0  Kidney Cancer: Types, Subtypes, Sarcomatoid Fe...
13   medical-H-3-O-0  Medical Imaging Modalities, Cancer Management,...
14  medical-H-26-O-0  Thyroid Gland, Thyroid Cancer, Diagnosis, Trea...
15  medical-H-19-O-0  Colorectal & Pelvic Cancers: Etiology, Anatomy...
16  medical-H-21-O-0  Patient Care Elements: Symptoms, Medical Histo...
17  medical-H-24-O-0  Cancer Tumors: Definition, TNM Staging, Invasi...
18  medical-H-14-O-0  Cancer Biopsy: Procedures, Analysis, and Clini...
19   medical-H-8-O-0  Cancer Care: Emotional Support, Fertility, Tre...
20  medical-H-15-O-0  Prostate Cancer: Disease, Risk Factors, Diagno...
21   medical-H-9-O-0  Digestive System: GI Organ Anatomy, Function, ...
22  medical-H-28-O-0  Personalized Cancer Management: Treatment, Sur...
23  medical-H-18-O-0         Cancer Diagnostics, Biology, and Treatment
24  medical-H-12-O-0  Central Nervous System Cancers: Spectrum, Diag...
25   medical-H-0-O-0  Blood, Bone Marrow, Immune System: Cancers, Di...
26  medical-H-30-O-0  Bone Cancer: Diagnosis, Staging, Treatment, Bo...
27  medical-H-13-O-0  Female Reproductive System: Gynecological Canc...
28   medical-H-2-O-0  Multimodal Cancer Therapies, Precision Oncolog...
29  medical-H-10-O-0  Bladder Cancer: Urinary System Anatomy, Etiolo...
30  medical-H-16-O-0  Cancer Clinical Trials: Purpose, Phases, Patie...
31  medical-H-31-O-0  Cancer Care: Smoking, Vaping, Lifestyle, Thera...
32  medical-H-29-O-0  Oncology Grading, Lymphoma Biology, and Therap...
33  medical-H-35-O-0  CML and Ewing Sarcoma: Genetic Basis, Chromoso...
34  medical-H-33-O-0  Acute Lymphoblastic Leukemia Subtypes, Lymphob...
35  medical-H-37-O-0  Personalized Patient Care, Quality of Life, Cl...
36  medical-H-32-O-0  Integrated Patient Care: Teams, Professionals,...
37  medical-H-38-O-0  Pre-treatment Diagnostics, Integrated Supporti...
38  medical-H-34-O-0  AML Chemotherapy and Targeted Therapies: Anthr...
39  medical-H-39-O-0  Rare Ovarian Cancers (LCOCs) Nomenclature, Cel...
40  medical-H-40-O-0  Cancer Biomarker Identification, Diagnosis, Pe...

In [5]:
import pickle
#communities
with open(f"{root_path}/graphs/data//nodes/community/medical_communities.pkl", "rb") as f:
    communities_medical = pickle.load(f)
communities_medical

defaultdict(list,
            {17: ['medical-0-S-0',
              'medical-0-S-0-R-0',
              'medical-0-S-0-R-1',
              'medical-0-S-0-R-2',
              'medical-0-S-0-R-3',
              'medical-0-S-0-R-4',
              'medical-0-S-1',
              'medical-0-S-1-R-0',
              'medical-0-S-1-R-1',
              'medical-0-S-1-R-2',
              'medical-0-S-1-R-3',
              'medical-0-S-1-R-4',
              'medical-0-S-1-R-5',
              'medical-0-S-1-R-6',
              'medical-0-S-1-R-7',
              'medical-0-S-1-R-8',
              'medical-0-S-1-R-9',
              'medical-0-S-1-R-10',
              'medical-0-S-1-R-11',
              'medical-0-S-1-R-12',
              'medical-0-S-2-R-1',
              'medical-0-S-2-R-2',
              'medical-0-S-3',
              'medical-0-S-3-R-0',
              'medical-0-S-3-R-1',
              'medical-0-S-3-R-2',
              'medical-0-S-3-R-3',
              'medical-0-S-3-R-4',
              'medical-0-S-3-R-5',
              'medical-0-S-3-R-6',
              'medical-0-S-3-R-7',
              'medical-0-S-3-R-8',
              'medical-0-S-3-R-9',
              'medical-0-S-3-R-10',
              'medical-0-S-3-R-11',
              'medical-0-S-3-R-12',
              'medical-0-S-3-R-13',
              'medical-0-S-3-R-14',
              'medical-0-S-3-R-15',
              'medical-0-S-3-R-16',
              'medical-0-S-3-R-17',
              'medical-0-S-3-R-18',
              'medical-0-S-3-R-19',
              'medical-0-S-3-R-20',
              'medical-0-S-3-R-21',
              'medical-0-S-3-R-22',
              'medical-0-S-3-R-23',
              'medical-0-S-3-R-24',
              'medical-0-S-3-R-25',
              'medical-0-S-3-R-26',
              'medical-0-S-3-R-27',
              'medical-1-S-0',
              'medical-1-S-0-R-1',
              'medical-1-S-0-R-2',
              'medical-1-S-0-R-3',
              'medical-1-S-0-R-4',
              'medical-1-S-0-R-5',
              'medical-1-S-0-R-6',
              'medical-1-S-0-R-7',
              'medical-1-S-0-R-8',
              'medical-1-S-0-R-9',
              'medical-1-S-0-R-10',
              'medical-1-S-1',
              'medical-1-S-1-R-0',
              'medical-1-S-2',
              'medical-1-S-2-R-0',
              'medical-1-S-2-R-1',
              'medical-1-S-2-R-2',
              'medical-1-S-2-R-3',
              'medical-1-S-2-R-4',
              'medical-1-S-2-R-5',
              'medical-1-S-2-R-6',
              'medical-1-S-2-R-7',
              'medical-1-S-2-R-8',
              'medical-1-S-2-R-9',
              'medical-1-S-2-R-10',
              'medical-1-S-2-R-11',
              'medical-1-S-2-R-12',
              'medical-1-S-2-R-13',
              'medical-1-S-2-R-14',
              'medical-1-S-2-R-15',
              'medical-1-S-2-R-16',
              'medical-1-S-2-R-17',
              'medical-1-S-3',
              'medical-1-S-3-R-0',
              'medical-1-S-3-R-1',
              'medical-1-S-3-R-2',
              'medical-1-S-4',
              'medical-1-S-4-R-0',
              'medical-1-S-4-R-1',
              'medical-1-S-4-R-2',
              'medical-1-S-4-R-3',
              'medical-1-S-4-R-6',
              'medical-1-S-4-R-7',
              'medical-2-S-0',
              'medical-2-S-0-R-0',
              'medical-2-S-0-R-1',
              'medical-2-S-0-R-2',
              'medical-2-S-0-R-3',
              'medical-2-S-0-R-4',
              'medical-2-S-0-R-8',
              'medical-2-S-0-R-9',
              'medical-2-S-0-R-10',
              'medical-2-S-0-R-11',
              'medical-2-S-0-R-12',
              'medical-2-S-0-R-13',
              'medical-2-S-0-R-14',
              'medical-2-S-0-R-15',
              'medical-2-S-0-R-17',
              'medical-2-S-0-R-18',
              'medical-2-S-0-R-19',
              'medical-2-S-0-R-20',
              'medical-2-S-0-R-21',
              'medical-2-S-1',
              'medical-2-S-1-R-0',
              'medical-2-S-1-R-1',
              'medical-2-S-1-R-2',
              'medical-2-S-1-R-4',
              'medical-2-S-1-R-5',
              'medical-2-S-1-R-6',
              'medical-2-S-1-R-7',
              'medical-2-S-1-R-8',
              'medical-2-S-1-R-11',
              'medical-2-S-1-R-12',
              'medical-2-S-1-R-14',
              'medical-3-S-0',
              'medical-3-S-0-R-0',
              'medical-3-S-0-R-1',
              'medical-3-S-0-R-2',
              'medical-3-S-0-R-3',
              'medical-3-S-0-R-4',
              'medical-3-S-3',
              'medical-3-S-3-R-1',
              'medical-3-S-3-R-2',
              'medical-3-S-3-R-3',
              'medical-3-S-3-R-4',
              'medical-3-S-3-R-5',
              'medical-3-S-3-R-6',
              'medical-3-S-3-R-7',
              'medical-4-S-0-R-1',
              'medical-4-S-0-R-2',
              'medical-4-S-0-R-4',
              'medical-4-S-0-R-5',
              'medical-4-S-0-R-6',
              'medical-10-S-0-R-6',
              'medical-13-S-0',
              'medical-13-S-0-R-0',
              'medical-13-S-0-R-1',
              'medical-13-S-0-R-2',
              'medical-13-S-0-R-3',
              'medical-13-S-0-R-4',
              'medical-13-S-0-R-5',
              'medical-13-S-0-R-6',
              'medical-13-S-0-R-7',
              'medical-13-S-0-R-8',
              'medical-13-S-0-R-9',
              'medical-13-S-0-R-10',
              'medical-13-S-0-R-11',
              'medical-13-S-0-R-12',
              'medical-13-S-0-R-13',
              'medical-13-S-0-R-14',
              'medical-13-S-1',
              'medical-13-S-1-R-0',
              'medical-13-S-1-R-1',
              'medical-13-S-1-R-2',
              'medical-13-S-1-R-6',
              'medical-13-S-1-R-7',
              'medical-13-S-1-R-8',
              'medical-13-S-2',
              'medical-13-S-2-R-0',
              'medical-13-S-2-R-1',
              'medical-13-S-2-R-2',
              'medical-13-S-2-R-3',
              'medical-13-S-2-R-4',
              'medical-13-S-2-R-5',
              'medical-13-S-3',
              'medical-13-S-3-R-0',
              'medical-13-S-3-R-1',
              'medical-13-S-3-R-2',
              'medical-13-S-3-R-3',
              'medical-13-S-3-R-4',
              'medical-13-S-3-R-5',
              'medical-13-S-3-R-6',
              'medical-13-S-3-R-7',
              'medical-13-S-3-R-8',
              'medical-13-S-3-R-9',
              'medical-13-S-3-R-10',
              'medical-13-S-3-R-11',
              'medical-13-S-3-R-12',
              'medical-13-S-3-R-13',
              'medical-13-S-3-R-14',
              'medical-13-S-3-R-15',
              'medical-13-S-3-R-16',
              'medical-13-S-4',
              'medical-13-S-4-R-0',
              'medical-13-S-4-R-1',
              'medical-13-S-4-R-2',
              'medical-13-S-4-R-3',
              'medical-13-S-4-R-4',
              'medical-13-S-4-R-5',
              'medical-13-S-4-R-6',
              'medical-13-S-4-R-7',
              'medical-13-S-4-R-8',
              'medical-13-S-4-R-9',
              'medical-13-S-4-R-10',
              'medical-13-S-4-R-11',
              'medical-13-S-4-R-12',
              'medical-13-S-4-R-13',
              'medical-13-S-4-R-14',
              'medical-13-S-4-R-15',
              'medical-13-S-4-R-16',
              'medical-13-S-4-R-17',
              'medical-14-S-0',
              'medical-14-S-0-R-0',
              'medical-14-S-0-R-1',
              'medical-14-S-0-R-2',
              'medical-14-S-0-R-3',
              'medical-14-S-0-R-4',
              'medical-14-S-0-R-5',
              'medical-14-S-0-R-6',
              'medical-14-S-0-R-7',
              'medical-14-S-0-R-8',
              'medical-14-S-0-R-9',
              'medical-14-S-0-R-10',
              'medical-14-S-0-R-11',
              'medical-14-S-0-R-12',
              'medical-14-S-0-R-13',
              'medical-14-S-0-R-14',
              'medical-14-S-0-R-15',
              'medical-14-S-0-R-16',
              'medical-14-S-1-R-2',
              'medical-14-S-2',
              'medical-14-S-2-R-0',
              'medical-14-S-2-R-1',
              'medical-14-S-2-R-2',
              'medical-14-S-2-R-3',
              'medical-14-S-2-R-4',
              'medical-14-S-2-R-5',
              'medical-14-S-2-R-6',
              'medical-14-S-2-R-7',
              'medical-14-S-2-R-8',
              'medical-14-S-3',
              'medical-14-S-3-R-0',
              'medical-14-S-3-R-1',
              'medical-14-S-3-R-2',
              'medical-14-S-3-R-3',
              'medical-14-S-5',
              'medical-14-S-5-R-0',
              'medical-14-S-5-R-1',
              'medical-14-S-5-R-2',
              'medical-14-S-5-R-3',
              'medical-14-S-5-R-4',
              'medical-14-S-5-R-5',
              'medical-14-S-5-R-6',
              'medical-15-S-0',
              'medical-15-S-0-R-0',
              'medical-15-S-0-R-1',
              'medical-15-S-0-R-2',
              'medical-15-S-2',
              'medical-15-S-2-R-0',
              'medical-15-S-2-R-1',
              'medical-15-S-2-R-2',
              'medical-15-S-2-R-3',
              'medical-15-S-2-R-4',
              'medical-15-S-3',
              'medical-15-S-3-R-0',
              'medical-15-S-3-R-1',
              'medical-15-S-3-R-2',
              'medical-15-S-3-R-3',
              'medical-15-S-3-R-4',
              'medical-15-S-3-R-5',
              'medical-15-S-3-R-6',
              'medical-15-S-3-R-7',
              'medical-15-S-3-R-8',
              'medical-15-S-3-R-9',
              'medical-15-S-3-R-10',
              'medical-15-S-3-R-12',
              'medical-15-S-3-R-13',
              'medical-15-S-3-R-14',
              'medical-15-S-3-R-15',
              'medical-15-S-3-R-16',
              'medical-15-S-3-R-17',
              'medical-15-S-3-R-18',
              'medical-15-S-3-R-19',
              'medical-15-S-3-R-20',
              'medical-15-S-3-R-21',
              'medical-15-S-4',
              'medical-15-S-4-R-0',
              'medical-15-S-4-R-1',
              'medical-15-S-4-R-2',
              'medical-15-S-4-R-3',
              'medical-15-S-4-R-4',
              'medical-15-S-4-R-5',
              'medical-15-S-4-R-6',
              'medical-15-S-4-R-7',
              'medical-15-S-4-R-8',
              'medical-15-S-4-R-9',
              'medical-15-S-4-R-10',
              'medical-15-S-4-R-11',
              'medical-15-S-4-R-12',
              'medical-15-S-4-R-13',
              'medical-15-S-4-R-14',
              'medical-15-S-4-R-15',
              'medical-15-S-4-R-16',
              'medical-15-S-4-R-17',
              'medical-15-S-4-R-18',
              'medical-16-S-0',
              'medical-16-S-0-R-2',
              'medical-16-S-0-R-3',
              'medical-16-S-0-R-4',
              'medical-16-S-0-R-5',
              'medical-16-S-0-R-6',
              'medical-16-S-0-R-8',
              'medical-16-S-0-R-9',
              'medical-16-S-0-R-10',
              'medical-16-S-0-R-11',
              'medical-16-S-0-R-12',
              'medical-16-S-0-R-13',
              'medical-16-S-1-R-15',
              'medical-16-S-1-R-16',
              'medical-16-S-1-R-17',
              'medical-16-S-1-R-18',
              'medical-16-S-2',
              'medical-16-S-2-R-0',
              'medical-16-S-2-R-1',
              'medical-16-S-2-R-2',
              'medical-16-S-2-R-3',
              'medical-16-S-2-R-4',
              'medical-16-S-2-R-5',
              'medical-16-S-2-R-6',
              'medical-16-S-2-R-7',
              'medical-16-S-3-R-0',
              'medical-16-S-3-R-1',
              'medical-16-S-3-R-3',
              'medical-16-S-3-R-4',
              'medical-16-S-3-R-10',
              'medical-17-S-0-R-1',
              'medical-17-S-0-R-3',
              'medical-17-S-0-R-4',
              'medical-17-S-0-R-5',
              'medical-17-S-0-R-7',
              'medical-17-S-1-R-0',
              'medical-17-S-2',
              'medical-17-S-2-R-0',
              'medical-17-S-2-R-1',
              'medical-17-S-2-R-2',
              'medical-17-S-2-R-3',
              'medical-17-S-2-R-4',
              'medical-17-S-2-R-5',
              'medical-17-S-2-R-6',
              'medical-17-S-2-R-7',
              'medical-17-S-2-R-8',
              'medical-17-S-4',
              'medical-17-S-4-R-0',
              'medical-19-S-2-R-0',
              'medical-19-S-3-R-1',
              'medical-19-S-3-R-2',
              'medical-20-S-1',
              'medical-20-S-1-R-0',
              'medical-20-S-1-R-1',
              'medical-20-S-1-R-2',
              'medical-20-S-1-R-3',
              'medical-20-S-1-R-4',
              'medical-20-S-1-R-5',
              'medical-20-S-1-R-6',
              'medical-20-S-1-R-7',
              'medical-20-S-1-R-9',
              'medical-20-S-1-R-10',
              'medical-20-S-1-R-11',
              'medical-20-S-1-R-12',
              'medical-20-S-1-R-13',
              'medical-20-S-2',
              'medical-20-S-2-R-1',
              'medical-20-S-2-R-2',
              'medical-20-S-2-R-3',
              'medical-20-S-2-R-4',
              'medical-20-S-3',
              'medical-20-S-3-R-0',
              'medical-20-S-3-R-5',
              'medical-20-S-3-R-7',
              'medical-21-S-0',
              'medical-21-S-0-R-2',
              'medical-21-S-0-R-3',
              'medical-21-S-0-R-5',
              'medical-21-S-0-R-6',
              'medical-21-S-0-R-7',
              'medical-21-S-0-R-10',
              'medical-21-S-1-R-0',
              'medical-21-S-2',
              'medical-21-S-2-R-0',
              'medical-21-S-2-R-1',
              'medical-21-S-2-R-2',
              'medical-21-S-2-R-3',
              'medical-21-S-2-R-4',
              'medical-21-S-2-R-5',
              'medical-22-S-7',
              'medical-22-S-7-R-0',
              'medical-22-S-7-R-1',
              'medical-22-S-7-R-2',
              'medical-22-S-7-R-3',
              'medical-22-S-7-R-4',
              'medical-22-S-7-R-5',
              'medical-22-S-9-R-1',
              'medical-22-S-9-R-3',
              'medical-23-S-1',
              'medical-23-S-1-R-0',
              'medical-23-S-1-R-1',
              'medical-23-S-1-R-2',
              'medical-23-S-1-R-3',
              'medical-23-S-1-R-4',
              'medical-23-S-1-R-5',
              'medical-23-S-1-R-6',
              'medical-23-S-1-R-7',
              'medical-23-S-2',
              'medical-23-S-2-R-0',
              'medical-23-S-2-R-1',
              'medical-23-S-2-R-2',
              'medical-23-S-2-R-3',
              'medical-23-S-2-R-4',
              'medical-23-S-2-R-5',
              'medical-23-S-2-R-6',
              'medical-23-S-2-R-7',
              'medical-23-S-2-R-8',
              'medical-23-S-3',
              'medical-23-S-3-R-0',
              'medical-23-S-3-R-1',
              'medical-23-S-3-R-2',
              'medical-23-S-3-R-4',
              'medical-23-S-3-R-5',
              'medical-23-S-3-R-6',
              'medical-23-S-3-R-7',
              'medical-23-S-3-R-9',
              'medical-23-S-4',
              'medical-23-S-4-R-0',
              'medical-23-S-4-R-1',
              'medical-23-S-4-R-3',
              'medical-23-S-4-R-4',
              'medical-23-S-5',
              'medical-23-S-5-R-0',
              'medical-23-S-5-R-1',
              'medical-23-S-5-R-2',
              'medical-23-S-5-R-3',
              'medical-23-S-5-R-4',
              'medical-23-S-5-R-5',
              'medical-23-S-5-R-9',
              'medical-23-S-5-R-10',
              'medical-23-S-5-R-11',
              'medical-23-S-5-R-12',
              'medical-23-S-6',
              'medical-23-S-6-R-0',
              'medical-23-S-6-R-4',
              'medical-23-S-6-R-5',
              'medical-23-S-6-R-6',
              'medical-23-S-6-R-7',
              'medical-23-S-6-R-9',
              'medical-23-S-6-R-10',
              'medical-23-S-6-R-11',
              'medical-23-S-6-R-12',
              'medical-23-S-6-R-13',
              'medical-23-S-6-R-14',
              'medical-23-S-6-R-15',
              'medical-23-S-6-R-16',
              'medical-23-S-6-R-17',
              'medical-24-S-1',
              'medical-24-S-1-R-0',
              'medical-24-S-1-R-1',
              'medical-24-S-1-R-2',
              'medical-24-S-2',
              'medical-24-S-2-R-0',
              'medical-24-S-2-R-1',
              'medical-24-S-2-R-2',
              'medical-24-S-2-R-3',
              'medical-24-S-2-R-4',
              'medical-24-S-2-R-5',
              'medical-24-S-2-R-6',
              'medical-24-S-2-R-7',
              'medical-24-S-2-R-8',
              'medical-24-S-2-R-9',
              'medical-24-S-2-R-10',
              'medical-24-S-2-R-11',
              'medical-24-S-4-R-9',
              'medical-24-S-4-R-10',
              'medical-24-S-4-R-11',
              'medical-26-S-2-R-18',
              'medical-27-S-2',
              'medical-27-S-2-R-0',
              'medical-27-S-2-R-1',
              'medical-27-S-2-R-2',
              'medical-27-S-2-R-3',
              'medical-27-S-2-R-4',
              'medical-27-S-2-R-5',
              'medical-27-S-2-R-6',
              'medical-27-S-2-R-7',
              'medical-27-S-2-R-8',
              'medical-27-S-2-R-9',
              'medical-28-S-4-R-7',
              'medical-28-S-4-R-8',
              'medical-28-S-4-R-9',
              'medical-29-S-0',
              'medical-29-S-0-R-0',
              'medical-29-S-0-R-1',
              'medical-29-S-0-R-2',
              'medical-29-S-0-R-3',
              'medical-29-S-0-R-5',
              'medical-29-S-2-R-4',
              'medical-29-S-4-R-6',
              'medical-29-S-5-R-0',
              'medical-32-S-3',
              'medical-32-S-3-R-0',
              'medical-32-S-3-R-1',
              'medical-32-S-3-R-2',
              'medical-32-S-3-R-3',
              'medical-32-S-3-R-4',
              'medical-32-S-3-R-5',
              'medical-33-S-1-R-0',
              'medical-33-S-3',
              'medical-33-S-3-R-0',
              'medical-33-S-3-R-1',
              'medical-33-S-3-R-2',
              'medical-33-S-3-R-3',
              'medical-33-S-3-R-4',
              'medical-33-S-4',
              'medical-33-S-4-R-0',
              'medical-34-S-4',
              'medical-34-S-4-R-0',
              'medical-34-S-4-R-1',
              'medical-34-S-4-R-5',
              'medical-35-S-2-R-3',
              'medical-38-S-1-R-0',
              'medical-38-S-1-R-5',
              'medical-38-S-1-R-6',
              'medical-39-S-2-R-0',
              'medical-39-S-3-R-1',
              'medical-41-S-1-R-4',
              'medical-41-S-1-R-5',
              'medical-42-S-0-R-3',
              'medical-42-S-0-R-6',
              'medical-42-S-2-R-0',
              'medical-42-S-3',
              'medical-42-S-3-R-0',
              'medical-42-S-3-R-1',
              'medical-42-S-3-R-2',
              'medical-42-S-4',
              'medical-42-S-4-R-0',
              'medical-42-S-4-R-1',
              'medical-42-S-4-R-2',
              'medical-42-S-4-R-3',
              'medical-42-S-4-R-4',
              'medical-42-S-4-R-5',
              'medical-42-S-4-R-7',
              'medical-42-S-4-R-9',
              'medical-43-S-0',
              'medical-43-S-0-R-0',
              'medical-43-S-0-R-1',
              'medical-43-S-0-R-3',
              'medical-43-S-0-R-4',
              'medical-43-S-0-R-5',
              'medical-43-S-0-R-6',
              'medical-43-S-0-R-7',
              'medical-43-S-0-R-8',
              'medical-43-S-0-R-9',

In [6]:
#T nodes
medical_chunks = pd.read_parquet(f"{root_path}/chunking/medical_chunks.parquet")
medical_chunks['node_id'] = "medical-" + medical_chunks.index.astype(str)
medical_chunks[["node_id","chunk"]]

         node_id                                              chunk
0      medical-0  About basal cell skin cancer What is basal cel...
1      medical-1  Hypodermis – The deepest tissue layer is made ...
2      medical-2  Causes and risk factors Basal cell skin cancer...
3      medical-3  Recurrence is when basal cell skin cancer retu...
4      medical-4  2 Testing for basal cell skin cancer 10 Genera...
..           ...                                                ...
549  medical-549  Is there a portal where I can get copies of my...
550  medical-550  Is home care after treatment needed? If yes, w...
551  medical-551  What will you target? What if I’ve already had...
552  medical-552  What are the chances the cancer will return or...
553  medical-553  clinical trial A research study using investig...

[554 rows x 2 columns]

In [7]:
#S,N,R,A nodes
#G2 - graph
with open(f"{root_path}/graphs/data/graphs/G2_medical_attribute_enriched_graph.pkl", "rb") as f:
    medical_g2 = pickle.load(f)
medical_g2

{'medical-0-S-0': <graphs.Node.Node at 0x2087ec40910>,
 'medical-0-S-0-R-0': <graphs.Node.Node at 0x2087ec40e80>,
 'medical-0-S-0-R-1': <graphs.Node.Node at 0x2087ec40e50>,
 'medical-0-S-0-R-2': <graphs.Node.Node at 0x2081708b070>,
 'medical-0-S-0-R-3': <graphs.Node.Node at 0x2081708a3e0>,
 'medical-0-S-0-R-4': <graphs.Node.Node at 0x2081708b850>,
 'medical-0-S-1': <graphs.Node.Node at 0x2081708aa10>,
 'medical-0-S-1-R-0': <graphs.Node.Node at 0x2081708bbb0>,
 'medical-0-S-1-R-1': <graphs.Node.Node at 0x2081708abf0>,
 'medical-0-S-1-R-2': <graphs.Node.Node at 0x2081708b8b0>,
 'medical-0-S-1-R-3': <graphs.Node.Node at 0x2081708bcd0>,
 'medical-0-S-1-R-4': <graphs.Node.Node at 0x2081708b0d0>,
 'medical-0-S-1-R-5': <graphs.Node.Node at 0x2081708ae90>,
 'medical-0-S-1-R-6': <graphs.Node.Node at 0x2081708a980>,
 'medical-0-S-1-R-7': <graphs.Node.Node at 0x2081708b970>,
 'medical-0-S-1-R-8': <graphs.Node.Node at 0x2081708b9a0>,
 'medical-0-S-1-R-9': <graphs.Node.Node at 0x2081708bb80>,
 'medical-0-S-1-R-10': <graphs.Node.Node at 0x2081708a9b0>,
 'medical-0-S-1-R-11': <graphs.Node.Node at 0x2081708ab90>,
 'medical-0-S-1-R-12': <graphs.Node.Node at 0x2081708b4f0>,
 'medical-0-S-2': <graphs.Node.Node at 0x2081708b100>,
 'medical-0-S-2-R-0': <graphs.Node.Node at 0x2081708b3a0>,
 'medical-0-S-2-R-1': <graphs.Node.Node at 0x2081708b010>,
 'medical-0-S-2-R-2': <graphs.Node.Node at 0x2081708bdf0>,
 'medical-0-S-2-R-3': <graphs.Node.Node at 0x2081708b9d0>,
 'medical-0-S-3': <graphs.Node.Node at 0x2081708a2f0>,
 'medical-0-S-3-R-0': <graphs.Node.Node at 0x2081708be50>,
 'medical-0-S-3-R-1': <graphs.Node.Node at 0x2081708a920>,
 'medical-0-S-3-R-2': <graphs.Node.Node at 0x2081708b130>,
 'medical-0-S-3-R-3': <graphs.Node.Node at 0x2081708bfd0>,
 'medical-0-S-3-R-4': <graphs.Node.Node at 0x2081708b910>,
 'medical-0-S-3-R-5': <graphs.Node.Node at 0x2081708be20>,
 'medical-0-S-3-R-6': <graphs.Node.Node at 0x2081708b250>,
 'medical-0-S-3-R-7': <graphs.Node.Node at 0x2081708be80>,
 'medical-0-S-3-R-8': <graphs.Node.Node at 0x2081708bf70>,
 'medical-0-S-3-R-9': <graphs.Node.Node at 0x20817670070>,
 'medical-0-S-3-R-10': <graphs.Node.Node at 0x20817670040>,
 'medical-0-S-3-R-11': <graphs.Node.Node at 0x20817670160>,
 'medical-0-S-3-R-12': <graphs.Node.Node at 0x20817670100>,
 'medical-0-S-3-R-13': <graphs.Node.Node at 0x20817670130>,
 'medical-0-S-3-R-14': <graphs.Node.Node at 0x208176700a0>,
 'medical-0-S-3-R-15': <graphs.Node.Node at 0x20817670190>,
 'medical-0-S-3-R-16': <graphs.Node.Node at 0x208176701c0>,
 'medical-0-S-3-R-17': <graphs.Node.Node at 0x208176701f0>,
 'medical-0-S-3-R-18': <graphs.Node.Node at 0x20817670220>,
 'medical-0-S-3-R-19': <graphs.Node.Node at 0x20817670250>,
 'medical-0-S-3-R-20': <graphs.Node.Node at 0x20817670280>,
 'medical-0-S-3-R-21': <graphs.Node.Node at 0x208176702b0>,
 'medical-0-S-3-R-22': <graphs.Node.Node at 0x208176702e0>,
 'medical-0-S-3-R-23': <graphs.Node.Node at 0x20817670310>,
 'medical-0-S-3-R-24': <graphs.Node.Node at 0x20817670340>,
 'medical-0-S-3-R-25': <graphs.Node.Node at 0x20817670370>,
 'medical-0-S-3-R-26': <graphs.Node.Node at 0x208176703a0>,
 'medical-0-S-3-R-27': <graphs.Node.Node at 0x208176703d0>,
 'medical-1-S-0': <graphs.Node.Node at 0x20817670400>,
 'medical-1-S-0-R-0': <graphs.Node.Node at 0x20817670430>,
 'medical-1-S-0-R-1': <graphs.Node.Node at 0x20817670460>,
 'medical-1-S-0-R-2': <graphs.Node.Node at 0x20817670490>,
 'medical-1-S-0-R-3': <graphs.Node.Node at 0x208176704c0>,
 'medical-1-S-0-R-4': <graphs.Node.Node at 0x208176704f0>,
 'medical-1-S-0-R-5': <graphs.Node.Node at 0x20817670520>,
 'medical-1-S-0-R-6': <graphs.Node.Node at 0x20817670550>,
 'medical-1-S-0-R-7': <graphs.Node.Node at 0x20817670580>,
 'medical-1-S-0-R-8': <graphs.Node.Node at 0x208176705b0>,
 'medical-1-S-0-R-9': <graphs.Node.Node at 0x208176705e0>,
 'medical-1-S-0-R-10': <graphs.Node.Node at 0x20817670610>,
 'medical-1-S-1': <graphs.Node.Node at 0x20817670640>,
 'medical-1-S-1-R-0': <graphs.Node.Node at 0x20817670670>,
 'medical-1-S-1-R-1': <graphs.Node.Node at 0x208176706a0>,
 'medical-1-S-1-R-2': <graphs.Node.Node at 0x208176706d0>,
 'medical-1-S-1-R-3': <graphs.Node.Node at 0x20817670700>,
 'medical-1-S-1-R-4': <graphs.Node.Node at 0x20817670730>,
 'medical-1-S-2': <graphs.Node.Node at 0x20817670760>,
 'medical-1-S-2-R-0': <graphs.Node.Node at 0x20817670790>,
 'medical-1-S-2-R-1': <graphs.Node.Node at 0x208176707c0>,
 'medical-1-S-2-R-2': <graphs.Node.Node at 0x208176707f0>,
 'medical-1-S-2-R-3': <graphs.Node.Node at 0x20817670820>,
 'medical-1-S-2-R-4': <graphs.Node.Node at 0x20817670850>,
 'medical-1-S-2-R-5': <graphs.Node.Node at 0x20817670880>,
 'medical-1-S-2-R-6': <graphs.Node.Node at 0x208176708b0>,
 'medical-1-S-2-R-7': <graphs.Node.Node at 0x208176708e0>,
 'medical-1-S-2-R-8': <graphs.Node.Node at 0x20817670910>,
 'medical-1-S-2-R-9': <graphs.Node.Node at 0x20817670940>,
 'medical-1-S-2-R-10': <graphs.Node.Node at 0x20817670970>,
 'medical-1-S-2-R-11': <graphs.Node.Node at 0x208176709a0>,
 'medical-1-S-2-R-12': <graphs.Node.Node at 0x208176709d0>,
 'medical-1-S-2-R-13': <graphs.Node.Node at 0x20817670a00>,
 'medical-1-S-2-R-14': <graphs.Node.Node at 0x20817670a30>,
 'medical-1-S-2-R-15': <graphs.Node.Node at 0x20817670a60>,
 'medical-1-S-2-R-16': <graphs.Node.Node at 0x20817670a90>,
 'medical-1-S-2-R-17': <graphs.Node.Node at 0x20817670ac0>,
 'medical-1-S-3': <graphs.Node.Node at 0x20817670af0>,
 'medical-1-S-3-R-0': <graphs.Node.Node at 0x20817670b20>,
 'medical-1-S-3-R-1': <graphs.Node.Node at 0x20817670b50>,
 'medical-1-S-3-R-2': <graphs.Node.Node at 0x20817670b80>,
 'medical-1-S-4': <graphs.Node.Node at 0x20817670bb0>,
 'medical-1-S-4-R-0': <graphs.Node.Node at 0x20817670be0>,
 'medical-1-S-4-R-1': <graphs.Node.Node at 0x20817670c10>,
 'medical-1-S-4-R-2': <graphs.Node.Node at 0x20817670c40>,
 'medical-1-S-4-R-3': <graphs.Node.Node at 0x20817670c70>,
 'medical-1-S-4-R-4': <graphs.Node.Node at 0x20817670ca0>,
 'medical-1-S-4-R-5': <graphs.Node.Node at 0x20817670cd0>,
 'medical-1-S-4-R-6': <graphs.Node.Node at 0x20817670d00>,
 'medical-1-S-4-R-7': <graphs.Node.Node at 0x20817670d30>,
 'medical-2-S-0': <graphs.Node.Node at 0x20817670d60>,
 'medical-2-S-0-R-0': <graphs.Node.Node at 0x20817670d90>,
 'medical-2-S-0-R-1': <graphs.Node.Node at 0x20817670dc0>,
 'medical-2-S-0-R-2': <graphs.Node.Node at 0x20817670df0>,
 'medical-2-S-0-R-3': <graphs.Node.Node at 0x20817670e20>,
 'medical-2-S-0-R-4': <graphs.Node.Node at 0x20817670e50>,
 'medical-2-S-0-R-5': <graphs.Node.Node at 0x20817670e80>,
 'medical-2-S-0-R-6': <graphs.Node.Node at 0x20817670eb0>,
 'medical-2-S-0-R-7': <graphs.Node.Node at 0x20817670ee0>,
 'medical-2-S-0-R-8': <graphs.Node.Node at 0x20817670f10>,
 'medical-2-S-0-R-9': <graphs.Node.Node at 0x20817670f40>,
 'medical-2-S-0-R-10': <graphs.Node.Node at 0x20817670f70>,
 'medical-2-S-0-R-11': <graphs.Node.Node at 0x20817670fa0>,
 'medical-2-S-0-R-12': <graphs.Node.Node at 0x20817670fd0>,
 'medical-2-S-0-R-13': <graphs.Node.Node at 0x20817671000>,
 'medical-2-S-0-R-14': <graphs.Node.Node at 0x20817671030>,
 'medical-2-S-0-R-15': <graphs.Node.Node at 0x20817671060>,
 'medical-2-S-0-R-16': <graphs.Node.Node at 0x20817671090>,
 'medical-2-S-0-R-17': <graphs.Node.Node at 0x208176710c0>,
 'medical-2-S-0-R-18': <graphs.Node.Node at 0x208176710f0>,
 'medical-2-S-0-R-19': <graphs.Node.Node at 0x20817671120>,
 'medical-2-S-0-R-20': <graphs.Node.Node at 0x20817671150>,
 'medical-2-S-0-R-21': <graphs.Node.Node at 0x20817671180>,
 'medical-2-S-1': <graphs.Node.Node at 0x208176711b0>,
 'medical-2-S-1-R-0': <graphs.Node.Node at 0x208176711e0>,
 'medical-2-S-1-R-1': <graphs.Node.Node at 0x20817671210>,
 'medical-2-S-1-R-2': <graphs.Node.Node at 0x20817671240>,
 'medical-2-S-1-R-3': <graphs.Node.Node at 0x20817671270>,
 'medical-2-S-1-R-4': <graphs.Node.Node at 0x208176712a0>,
 'medical-2-S-1-R-5': <graphs.Node.Node at 0x208176712d0>,
 'medical-2-S-1-R-6': <graphs.Node.Node at 0x20817671300>,
 'medical-2-S-1-R-7': <graphs.Node.Node at 0x20817671330>,
 'medical-2-S-1-R-8': <graphs.Node.Node at 0x20817671360>,
 'medical-2-S-1-R-9': <graphs.Node.Node at 0x20817671390>,
 'medical-2-S-1-R-10': <graphs.Node.Node at 0x208176713c0>,
 'medical-2-S-1-R-11': <graphs.Node.Node at 0x208176713f0>,
 'medical-2-S-1-R-12': <graphs.Node.Node at 0x20817671420>,
 'medical-2-S-1-R-13': <graphs.Node.Node at 0x20817671450>,
 'medical-2-S-1-R-14': <graphs.Node.Node at 0x20817671480>,
 'medical-2-S-1-R-15': <graphs.Node.Node at 0x208176714b0>,
 'medical-2-S-2': <graphs.Node.Node at 0x208176714e0>,
 'medical-2-S-2-R-0': <graphs.Node.Node at 0x20817671510>,
 'medical-2-S-2-R-1': <graphs.Node.Node at 0x20817671540>,
 'medical-2-S-2-R-2': <graphs.Node.Node at 0x20817671570>,
 'medical-2-S-2-R-3': <graphs.Node.Node at 0x208176715a0>,
 'medical-2-S-2-R-4': <graphs.Node.Node at 0x208176715d0>,
 'medical-3-S-0': <graphs.Node.Node at 0x20817671600>,
 'medical-3-S-0-R-0': <graphs.Node.Node at 0x20817671630>,
 'medical-3-S-0-R-1': <graphs.Node.Node at 0x20817671660>,
 'medical-3-S-0-R-2': <graphs.Node.Node at 0x20817671690>,
 'medical-3-S-0-R-3': <graphs.Node.Node at 0x208176716c0>,
 'medical-3-S-0-R-4': <graphs.Node.Node at 0x208176716f0>,
 'medical-3-S-1': <graphs.Node.Node at 0x20817671720>,
 'medical-3-S-1-R-0': <graphs.Node.Node at 0x20817671750>,
 'medical-3-S-1-R-1': <graphs.Node.Node at 0x20817671780>,
 'medical-3-S-1-R-2': <graphs.Node.Node at 0x208176717b0>,
 'medical-3-S-1-R-3': <graphs.Node.Node at 0x208176717e0>,
 'medical-3-S-2': <graphs.Node.Node at 0x20817671810>,
 'medical-3-S-2-R-0': <graphs.Node.Node at 0x20817671840>,
 'medical-3-S-2-R-1': <graphs.Node.Node at 0x20817671870>,
 'medical-3-S-2-R-2': <graphs.Node.Node at 0x208176718a0>,
 'medical-3-S-2-R-3': <graphs.Node.Node at 0x208176718d0>,
 'medical-3-S-2-R-4': <graphs.Node.Node at 0x20817671900>,
 'medical-3-S-2-R-5': <graphs.Node.Node at 0x20817671930>,
 'medical-3-S-2-R-6': <graphs.Node.Node at 0x20817671960>,
 'medical-3-S-2-R-7': <graphs.Node.Node at 0x20817671990>,
 'medical-3-S-2-R-8': <graphs.Node.Node at 0x208176719c0>,
 'medical-3-S-3': <graphs.Node.Node at 0x208176719f0>,
 'medical-3-S-3-R-0': <graphs.Node.Node at 0x20817671a20>,
 'medical-3-S-3-R-1': <graphs.Node.Node at 0x20817671a50>,
 'medical-3-S-3-R-2': <graphs.Node.Node at 0x20817671a80>,
 'medical-3-S-3-R-3': <graphs.Node.Node at 0x20817671ab0>,
 'medical-3-S-3-R-4': <graphs.Node.Node at 0x20817671ae0>,
 'medical-3-S-3-R-5': <graphs.Node.Node at 0x20817671b10>,
 'medical-3-S-3-R-6': <graphs.Node.Node at 0x20817671b40>,
 'medical-3-S-3-R-7': <graphs.Node.Node at 0x20817671b70>,
 'medical-4-S-0': <graphs.Node.Node at 0x20817671ba0>,
 'medical-4-S-0-R-0': <graphs.Node.Node at 0x20817671bd0>,
 'medical-4-S-0-R-1': <graphs.Node.Node at 0x20817671c00>,
 'medical-4-S-0-R-2': <graphs.Node.Node at 0x20817671c30>,
 'medical-4-S-0-R-3': <graphs.Node.Node at 0x20817671c60>,
 'medical-4-S-0-R-4': <graphs.Node.Node at 0x20817671c90>,
 'medical-4-S-0-R-5': <graphs.Node.Node at 0x20817671cc0>,
 'medical-4-S-0-R-6': <graphs.Node.Node at 0x20817671cf0>,
 'medical-4-S-1': <graphs.Node.Node at 0x20817671d20>,
 'medical-4-S-1-R-0': <graphs.Node.Node at 0x20817671d50>,
 'medical-4-S-1-R-1': <graphs.Node.Node at 0x20817671d80>,
 'medical-4-S-1-R-2': <graphs.Node.Node at 0x20817671db0>,
 'medical-5-S-0': <graphs.Node.Node at 0x20817671de0>,
 'medical-5-S-0-R-0': <graphs.Node.Node at 0x20817671e10>,
 'medical-5-S-0-R-1': <graphs.Node.Node at 0x20817671e40>,
 'medical-5-S-0-R-2': <graphs.Node.Node at 0x20817671e70>,
 'medical-5-S-0-R-3': <graphs.Node.Node at 0x20817671ea0>,
 'medical-5-S-0-R-4': <graphs.Node.Node at 0x20817671ed0>,
 'medical-5-S-0-R-5': <graphs.Node.Node at 0x20817671f00>,
 'medical-5-S-0-R-6': <graphs.Node.Node at 0x20817671f30>,
 'medical-5-S-1': <graphs.Node.Node at 0x20817671f60>,
 'medical-5-S-1-R-0': <graphs.Node.Node at 0x20817671f90>,
 'medical-5-S-1-R-1': <graphs.Node.Node at 0x20817671fc0>,
 'medical-5-S-1-R-2': <graphs.Node.Node at 0x20817671ff0>,
 'medical-5-S-1-R-3': <graphs.Node.Node at 0x20817672020>,
 'medical-5-S-1-R-4': <graphs.Node.Node at 0x20817672050>,
 'medical-5-S-1-R-5': <graphs.Node.Node at 0x20817672080>,
 'medical-5-S-1-R-6': <graphs.Node.Node at 0x208176720b0>,
 'medical-5-S-1-R-7': <graphs.Node.Node at 0x208176720e0>,
 'medical-5-S-1-R-8': <graphs.Node.Node at 0x20817672110>,
 'medical-5-S-1-R-9': <graphs.Node.Node at 0x20817672140>,
 'medical-5-S-2': <graphs.Node.Node at 0x20817672170>,
 'medical-5-S-2-R-0': <graphs.Node.Node at 0x208176721a0>,
 'medical-5-S-2-R-1': <graphs.Node.Node at 0x208176721d0>,
 'medical-5-S-2-R-2': <graphs.Node.Node at 0x20817672200>,
 'medical-5-S-2-R-3': <graphs.Node.Node at 0x20817672230>,
 'medical-5-S-2-R-4': <graphs.Node.Node at 0x20817672260>,
 'medical-5-S-2-R-5': <graphs.Node.Node at 0x20817672290>,
 'medical-5-S-2-R-6': <graphs.Node.Node at 0x208176722c0>,
 'medical-5-S-2-R-7': <graphs.Node.Node at 0x208176722f0>,
 'medical-5-S-2-R-8': <graphs.Node.Node at 0x20817672320>,
 'medical-5-S-2-R-9': <graphs.Node.Node at 0x20817672350>,
 'medical-5-S-2-R-10': <graphs.Node.Node at 0x20817672380>,
 'medical-5-S-2-R-11': <graphs.Node.Node at 0x208176723b0>,
 'medical-5-S-2-R-12': <graphs.Node.Node at 0x208176723e0>,
 'medical-5-S-2-R-13': <graphs.Node.Node at 0x20817672410>,
 'medical-5-S-2-R-14': <graphs.Node.Node at 0x20817672440>,
 'medical-5-S-2-R-15': <graphs.Node.Node at 0x20817672470>,
 'medical-5-S-2-R-16': <graphs.Node.Node at 0x208176724a0>,
 'medical-5-S-2-R-17': <graphs.Node.Node at 0x208176724d0>,
 'medical-5-S-2-R-18': <graphs.Node.Node at 0x20817672500>,
 'medical-5-S-2-R-19': <graphs.Node.Node at 0x20817672530>,
 'medical-5-S-2-R-20': <graphs.Node.Node at 0x20817672560>,
 'medical-5-S-2-R-21': <graphs.Node.Node at 0x20817672590>,
 'medical-5-S-2-R-22': <graphs.Node.Node at 0x208176725c0>,
 'medical-5-S-2-R-23': <graphs.Node.Node at 0x208176725f0>,
 'medical-5-S-2-R-24': <graphs.Node.Node at 0x20817672620>,
 'medical-5-S-3': <graphs.Node.Node at 0x20817672650>,
 'medical-5-S-3-R-0': <graphs.Node.Node at 0x20817672680>,
 'medical-5-S-3-R-1': <graphs.Node.Node at 0x208176726b0>,
 'medical-5-S-3-R-2': <graphs.Node.Node at 0x208176726e0>,
 'medical-5-S-3-R-3': <graphs.Node.Node at 0x20817672710>,
 'medical-5-S-3-R-4': <graphs.Node.Node at 0x20817672740>,
 'medical-5-S-3-R-5': <graphs.Node.Node at 0x20817672770>,
 'medical-5-S-4': <graphs.Node.Node at 0x208176727a0>,
 'medical-5-S-4-R-0': <graphs.Node.Node at 0x208176727d0>,
 'medical-5-S-4-R-1': <graphs.Node.Node at 0x20817672800>,
 'medical-5-S-4-R-2': <graphs.Node.Node at 0x20817672830>,
 'medical-5-S-4-R-3': <graphs.Node.Node at 0x20817672860>,
 'medical-5-S-4-R-4': <graphs.Node.Node at 0x20817672890>,
 'medical-5-S-4-R-5': <graphs.Node.Node at 0x208176728c0>,
 'medical-5-S-4-R-6': <graphs.Node.Node at 0x208176728f0>,
 'medical-5-S-5': <graphs.Node.Node at 0x20817672920>,
 'medical-5-S-5-R-0': <graphs.Node.Node at 0x20817672950>,
 'medical-5-S-5-R-1': <graphs.Node.Node at 0x20817672980>,
 'medical-5-S-5-R-2': <graphs.Node.Node at 0x208176729b0>,
 'medical-5-S-5-R-3': <graphs.Node.Node at 0x208176729e0>,
 'medical-5-S-5-R-4': <graphs.Node.Node at 0x20817672a10>,
 'medical-5-S-5-R-5': <graphs.Node.Node at 0x20817672a40>,
 'medical-5-S-5-R-6': <graphs.Node.Node at 0x20817672a70>,
 'medical-5-S-5-R-7': <graphs.Node.Node at 0x20817672aa0>,
 'medical-5-S-5-R-8': <graphs.Node.Node at 0x20817672ad0>,
 'medical-5-S-5-R-9': <graphs.Node.Node at 0x20817672b00>,
 'medical-5-S-6': <graphs.Node.Node at 0x20817672b30>,
 'medical-5-S-6-R-0': <graphs.Node.Node at 0x20817672b60>,
 'medical-5-S-6-R-1': <graphs.Node.Node at 0x20817672b90>,
 'medical-5-S-6-R-2': <graphs.Node.Node at 0x20817672bc0>,
 'medical-5-S-6-R-3': <graphs.Node.Node at 0x20817672bf0>,
 'medical-6-S-0': <graphs.Node.Node at 0x20817672c20>,
 'medical-6-S-0-R-0': <graphs.Node.Node at 0x20817672c50>,
 'medical-6-S-0-R-1': <graphs.Node.Node at 0x20817672c80>,
 'medical-6-S-0-R-2': <graphs.Node.Node at 0x20817672cb0>,
 'medical-6-S-0-R-3': <graphs.Node.Node at 0x20817672ce0>,
 'medical-6-S-0-R-4': <graphs.Node.Node at 0x20817672d10>,
 'medical-6-S-0-R-5': <graphs.Node.Node at 0x20817672d40>,
 'medical-6-S-0-R-6': <graphs.Node.Node at 0x20817672d70>,
 'medical-6-S-0-R-7': <graphs.Node.Node at 0x20817672da0>,
 'medical-6-S-0-R-8': <graphs.Node.Node at 0x20817672dd0>,
 'medical-6-S-0-R-9': <graphs.Node.Node at 0x20817672e00>,
 'medical-6-S-0-R-10': <graphs.Node.Node at 0x20817672e30>,
 'medical-6-S-0-R-11': <graphs.Node.Node at 0x20817672e60>,
 'medical-6-S-0-R-12': <graphs.Node.Node at 0x20817672e90>,
 'medical-6-S-0-R-13': <graphs.Node.Node at 0x20817672ec0>,
 'medical-6-S-0-R-14': <graphs.Node.Node at 0x20817672ef0>,
 'medical-6-S-1': <graphs.Node.Node at 0x20817672f20>,
 'medical-6-S-1-R-0': <graphs.Node.Node at 0x20817672f50>,
 'medical-6-S-1-R-1': <graphs.Node.Node at 0x20817672f80>,
 'medical-6-S-1-R-2': <graphs.Node.Node at 0x20817672fb0>,
 'medical-6-S-1-R-3': <graphs.Node.Node at 0x20817672fe0>,
 'medical-6-S-1-R-4': <graphs.Node.Node at 0x20817673010>,
 'medical-6-S-1-R-5': <graphs.Node.Node at 0x20817673040>,
 'medical-6-S-1-R-6': <graphs.Node.Node at 0x20817673070>,
 'medical-6-S-1-R-7': <graphs.Node.Node at 0x208176730a0>,
 'medical-6-S-1-R-8': <graphs.Node.Node at 0x208176730d0>,
 'medical-6-S-1-R-9': <graphs.Node.Node at 0x20817673100>,
 'medical-6-S-1-R-10': <graphs.Node.Node at 0x20817673130>,
 'medical-6-S-1-R-11': <graphs.Node.Node at 0x20817673160>,
 'medical-6-S-1-R-12': <graphs.Node.Node at 0x20817673190>,
 'medical-6-S-1-R-13': <graphs.Node.Node at 0x208176731c0>,
 'medical-6-S-1-R-14': <graphs.Node.Node at 0x208176731f0>,
 'medical-6-S-1-R-15': <graphs.Node.Node at 0x20817673220>,
 'medical-6-S-1-R-16': <graphs.Node.Node at 0x20817673250>,
 'medical-6-S-2': <graphs.Node.Node at 0x20817673280>,
 'medical-6-S-2-R-0': <graphs.Node.Node at 0x208176732b0>,
 'medical-6-S-2-R-1': <graphs.Node.Node at 0x208176732e0>,
 'medical-6-S-2-R-2': <graphs.Node.Node at 0x20817673310>,
 'medical-6-S-2-R-3': <graphs.Node.Node at 0x20817673340>,
 'medical-6-S-2-R-4': <graphs.Node.Node at 0x20817673370>,
 'medical-6-S-2-R-5': <graphs.Node.Node at 0x208176733a0>,
 'medical-6-S-3': <graphs.Node.Node at 0x208176733d0>,
 'medical-6-S-3-R-0': <graphs.Node.Node at 0x20817673400>,
 'medical-6-S-3-R-1': <graphs.Node.Node at 0x20817673430>,
 'medical-6-S-3-R-2': <graphs.Node.Node at 0x20817673460>,
 'medical-6-S-3-R-3': <graphs.Node.Node at 0x20817673490>,
 'medical-6-S-3-R-4': <graphs.Node.Node at 0x208176734c0>,
 'medical-6-S-3-R-5': <graphs.Node.Node at 0x208176734f0>,
 'medical-6-S-3-R-6': <graphs.Node.Node at 0x20817673520>,
 'medical-6-S-3-R-7': <graphs.Node.Node at 0x20817673550>,
 'medical-6-S-4': <graphs.Node.Node at 0x20817673580>,
 'medical-6-S-4-R-0': <graphs.Node.Node at 0x208176735b0>,
 'medical-6-S-4-R-1': <graphs.Node.Node at 0x208176735e0>,
 'medical-6-S-4-R-2': <graphs.Node.Node at 0x20817673610>,
 'medical-6-S-4-R-3': <graphs.Node.Node at 0x20817673640>,
 'medical-6-S-4-R-4': <graphs.Node.Node at 0x20817673670>,
 'medical-6-S-4-R-5': <graphs.Node.Node at 0x208176736a0>,
 'medical-6-S-4-R-6': <graphs.Node.Node at 0x208176736d0>,
 'medical-6-S-4-R-7': <graphs.Node.Node at 0x20817673700>,
 'medical-6-S-4-R-8': <graphs.Node.Node at 0x20817673730>,
 'medical-6-S-4-R-9': <graphs.Node.Node at 0x20817673760>,
 'medical-6-S-4-R-10': <graphs.Node.Node at 0x20817673790>,
 'medical-7-S-0': <graphs.Node.Node at 0x208176737c0>,
 'medical-7-S-0-R-0': <graphs.Node.Node at 0x208176737f0>,
 'medical-7-S-0-R-1': <graphs.Node.Node at 0x20817673820>,
 'medical-7-S-0-R-2': <graphs.Node.Node at 0x20817673850>,
 'medical-7-S-0-R-3': <graphs.Node.Node at 0x20817673880>,
 'medical-7-S-0-R-4': <graphs.Node.Node at 0x208176738b0>,
 'medical-7-S-0-R-5': <graphs.Node.Node at 0x208176738e0>,
 'medical-7-S-0-R-6': <graphs.Node.Node at 0x20817673910>,
 'medical-7-S-1': <graphs.Node.Node at 0x20817673940>,

In [8]:
import json
import faiss
import numpy as np
#embeddings of S,A,H,T nodes

#load faiss index file
index = faiss.read_index("data/embedding/medical_index.faiss")
with open("data/embedding/medical_ids.json", "r") as f:
    medical_embedding_ids = json.load(f)
index.ntotal, len(medical_embedding_ids)

#reconstruct vectors from faiss index
num_vectors = index.ntotal
dimension = index.d
embeddings = np.zeros((num_vectors, dimension), dtype='float32')
for i in range(num_vectors):
    embeddings[i] = index.reconstruct(i)

print("Embeddings shape:", embeddings.shape)
embeddings

Embeddings shape: (4426, 768)

array([[-0.06428347, -0.05439772, -0.04260492, ..., -0.0463121 ,
        -0.03141087,  0.0049261 ],
       [-0.04751787, -0.05777418, -0.02587977, ..., -0.04238609,
        -0.00359848,  0.0272001 ],
       [-0.06036756, -0.067439  , -0.05656344, ..., -0.06152818,
        -0.01679316,  0.01591949],
       ...,
       [ 0.04048249, -0.0287718 , -0.03389297, ..., -0.00295302,
         0.0417009 ,  0.00099732],
       [ 0.00630154, -0.0139234 , -0.01267361, ..., -0.09236696,
         0.01060561, -0.01778929],
       [ 0.01245843, -0.01854508, -0.01106029, ..., -0.08220403,
         0.01130273,  0.05532239]], dtype=float32)

In [9]:
import re
#separate T nodes, H nodes, S-A nodes
#id pattern
medical_T_id_pattern = re.compile(r"^medical-\d+$")
medical_H_id_pattern = re.compile(r"^medical-H-\d+$")
#id lists
medical_embedding_T_ids = []
medical_embedding_H_ids = []
medical_embedding_SA_ids = []
#index
medical_embedding_H_index = []
medical_embedding_SA_index = []


for i in range(num_vectors):
    current_id = medical_embedding_ids[i]
    if medical_T_id_pattern.match(current_id):
        medical_embedding_T_ids.append(current_id)
    elif medical_H_id_pattern.match(current_id):
        medical_embedding_H_ids.append(current_id)
        medical_embedding_H_index.append(i)
    else:
        medical_embedding_SA_ids.append(current_id)
        medical_embedding_SA_index.append(i)

H_embeddings = embeddings[medical_embedding_H_index]
SA_embeddings = embeddings[medical_embedding_SA_index]
SA_embeddings.shape, H_embeddings.shape

((3831, 768), (41, 768))

In [10]:
import math
#k means on embeddings
#hyperparameters
k = math.floor(math.sqrt(SA_embeddings.shape[0]))
niter = 1000

#init model and train
kmeans = faiss.Kmeans(d=index.d,k=k,niter=niter,verbose=True,spherical=True,gpu=False)
kmeans.cp.metric_type = faiss.METRIC_INNER_PRODUCT
kmeans.train(SA_embeddings)

#get centroids and assign
centroids = kmeans.centroids
_, SA_assignments = kmeans.index.search(SA_embeddings, 1)
SA_assignments = SA_assignments.reshape(-1)

#cluster->SA nodes mapping
clusters = {i: [] for i in range(k)}
for idx, cid in enumerate(SA_assignments):
    clusters[cid].append(medical_embedding_SA_ids[idx])

print("Number of clusters:",len(clusters))
clusters

Number of clusters: 61

{0: ['medical-115-S-1',
  'medical-115-S-2',
  'medical-172-S-4',
  'medical-172-S-5',
  'medical-172-S-7',
  'medical-228-S-0',
  'medical-249-S-7',
  'medical-250-S-1',
  'medical-348-S-2',
  'medical-348-S-3',
  'medical-348-S-4',
  'medical-372-S-1',
  'medical-380-S-4',
  'medical-380-S-5',
  'medical-381-S-1',
  'medical-553-S-4',
  'medical-553-S-7',
  'medical-N-1559-A-0',
  'medical-N-2126-A-0',
  'medical-N-2133-A-0',
  'medical-N-2134-A-0',
  'medical-N-2893-A-0',
  'medical-N-2894-A-0',
  'medical-N-2895-A-0',
  'medical-N-2898-A-0',
  'medical-N-3546-A-0',
  'medical-N-3861-A-0',
  'medical-N-4379-A-0',
  'medical-N-2889-A-0',
  'medical-N-3864-A-0'],
 1: ['medical-181-S-1',
  'medical-485-S-0',
  'medical-485-S-1',
  'medical-485-S-3',
  'medical-485-S-4',
  'medical-486-S-0',
  'medical-486-S-1',
  'medical-486-S-2',
  'medical-486-S-3',
  'medical-487-S-0',
  'medical-487-S-1',
  'medical-487-S-2',
  'medical-487-S-3',
  'medical-487-S-5',
  'medical-487-S-6',
  'medical-487-S-7',
  'medical-488-S-0',
  'medical-488-S-1',
  'medical-488-S-2',
  'medical-489-S-0',
  'medical-489-S-1',
  'medical-489-S-2',
  'medical-489-S-3',
  'medical-490-S-0',
  'medical-490-S-1',
  'medical-490-S-2',
  'medical-490-S-3',
  'medical-492-S-2',
  'medical-493-S-2',
  'medical-493-S-3',
  'medical-494-S-0',
  'medical-495-S-0',
  'medical-496-S-0',
  'medical-499-S-2',
  'medical-499-S-3',
  'medical-499-S-4',
  'medical-500-S-0',
  'medical-501-S-0',
  'medical-501-S-2',
  'medical-501-S-3',
  'medical-501-S-4',
  'medical-501-S-5',
  'medical-502-S-1',
  'medical-502-S-2',
  'medical-502-S-3',
  'medical-502-S-4',
  'medical-503-S-2',
  'medical-503-S-3',
  'medical-504-S-0',
  'medical-504-S-1',
  'medical-504-S-2',
  'medical-504-S-4',
  'medical-505-S-0',
  'medical-505-S-1',
  'medical-505-S-2',
  'medical-506-S-0',
  'medical-506-S-1',
  'medical-506-S-2',
  'medical-506-S-3',
  'medical-507-S-0',
  'medical-507-S-1',
  'medical-509-S-1',
  'medical-509-S-2',
  'medical-509-S-3',
  'medical-510-S-0',
  'medical-510-S-1',
  'medical-510-S-2',
  'medical-511-S-0',
  'medical-511-S-1',
  'medical-511-S-3',
  'medical-511-S-4',
  'medical-512-S-0',
  'medical-512-S-1',
  'medical-512-S-2',
  'medical-513-S-0',
  'medical-513-S-1',
  'medical-513-S-4',
  'medical-515-S-5',
  'medical-516-S-0',
  'medical-516-S-1',
  'medical-516-S-3',
  'medical-517-S-2',
  'medical-517-S-3',
  'medical-517-S-6',
  'medical-517-S-7',
  'medical-N-2193-A-0',
  'medical-N-4028-A-0',
  'medical-N-4549-A-0',
  'medical-N-8113-A-0',
  'medical-N-8132-A-0',
  'medical-N-8169-A-0',
  'medical-N-8352-A-0',
  'medical-N-8360-A-0',
  'medical-N-8385-A-0'],
 2: ['medical-24-S-1',
  'medical-27-S-3',
  'medical-27-S-4',
  'medical-28-S-0',
  'medical-28-S-5',
  'medical-28-S-6',
  'medical-29-S-1',
  'medical-29-S-2',
  'medical-111-S-1',
  'medical-111-S-3',
  'medical-112-S-1',
  'medical-112-S-2',
  'medical-131-S-3',
  'medical-133-S-8',
  'medical-133-S-11',
  'medical-134-S-3',
  'medical-135-S-0',
  'medical-207-S-2',
  'medical-207-S-4',
  'medical-208-S-1',
  'medical-208-S-2',
  'medical-218-S-3',
  'medical-309-S-3',
  'medical-310-S-2',
  'medical-310-S-4',
  'medical-311-S-0',
  'medical-311-S-2',
  'medical-311-S-4',
  'medical-312-S-0',
  'medical-312-S-2',
  'medical-313-S-5',
  'medical-332-S-2',
  'medical-333-S-0',
  'medical-334-S-4',
  'medical-335-S-0',
  'medical-336-S-4',
  'medical-337-S-2',
  'medical-338-S-2',
  'medical-341-S-3',
  'medical-341-S-8',
  'medical-353-S-2',
  'medical-387-S-4',
  'medical-388-S-1',
  'medical-388-S-2',
  'medical-388-S-3',
  'medical-389-S-2',
  'medical-389-S-3',
  'medical-389-S-4',
  'medical-390-S-0',
  'medical-390-S-1',
  'medical-390-S-3',
  'medical-391-S-1',
  'medical-391-S-3',
  'medical-394-S-6',
  'medical-395-S-1',
  'medical-395-S-3',
  'medical-405-S-4',
  'medical-406-S-0',
  'medical-415-S-6',
  'medical-416-S-2',
  'medical-417-S-1',
  'medical-417-S-3',
  'medical-511-S-2',
  'medical-513-S-2',
  'medical-517-S-4',
  'medical-517-S-5',
  'medical-528-S-4',
  'medical-528-S-5',
  'medical-528-S-7',
  'medical-528-S-8',
  'medical-529-S-0',
  'medical-529-S-1',
  'medical-530-S-2',
  'medical-530-S-4',
  'medical-530-S-5',
  'medical-531-S-0',
  'medical-531-S-1',
  'medical-537-S-8',
  'medical-553-S-9',
  'medical-N-98-A-0',
  'medical-N-716-A-0',
  'medical-N-846-A-0',
  'medical-N-1331-A-0',
  'medical-N-2812-A-0',
  'medical-N-3986-A-0',
  'medical-N-5559-A-0',
  'medical-N-6586-A-0'],
 3: ['medical-87-S-3',
  'medical-88-S-3',
  'medical-106-S-2',
  'medical-106-S-3',
  'medical-122-S-2',
  'medical-122-S-3',
  'medical-123-S-0',
  'medical-123-S-1',
  'medical-123-S-2',
  'medical-125-S-1',
  'medical-125-S-2',
  'medical-125-S-3',
  'medical-125-S-4',
  'medical-126-S-0',
  'medical-126-S-1',
  'medical-126-S-2',
  'medical-126-S-3',
  'medical-126-S-5',
  'medical-126-S-6',
  'medical-127-S-0',
  'medical-138-S-1',
  'medical-155-S-2',
  'medical-156-S-4',
  'medical-156-S-5',
  'medical-157-S-0',
  'medical-169-S-3',
  'medical-170-S-0',
  'medical-170-S-2',
  'medical-201-S-4',
  'medical-202-S-0',
  'medical-202-S-2',
  'medical-202-S-3',
  'medical-228-S-4',
  'medical-240-S-4',
  'medical-241-S-1',
  'medical-241-S-2',
  'medical-242-S-0',
  'medical-242-S-1',
  'medical-242-S-2',
  'medical-242-S-3',
  'medical-242-S-4',
  'medical-250-S-3',
  'medical-262-S-4',
  'medical-262-S-5',
  'medical-263-S-0',
  'medical-263-S-1',
  'medical-264-S-0',
  'medical-264-S-1',
  'medical-296-S-4',
  'medical-297-S-1',
  'medical-297-S-2',
  'medical-297-S-3',
  'medical-297-S-4',
  'medical-298-S-2',
  'medical-298-S-5',
  'medical-298-S-7',
  'medical-299-S-0',
  'medical-299-S-2',
  'medical-299-S-3',
  'medical-299-S-4',
  'medical-301-S-11',
  'medical-302-S-0',
  'medical-345-S-2',
  'medical-345-S-6',
  'medical-346-S-2',
  'medical-347-S-0',
  'medical-348-S-6',
  'medical-365-S-3',
  'medical-367-S-2',
  'medical-402-S-3',
  'medical-402-S-5',
  'medical-402-S-7',
  'medical-403-S-0',
  'medical-426-S-4',
  'medical-437-S-1',
  'medical-437-S-2',
  'medical-438-S-0',
  'medical-438-S-4',
  'medical-439-S-1',
  'medical-439-S-3',
  'medical-439-S-4',
  'medical-478-S-8',
  'medical-478-S-9',
  'medical-479-S-0',
  'medical-494-S-1',
  'medical-498-S-3',
  'medical-499-S-0',
  'medical-499-S-1',
  'medical-N-263-A-0',
  'medical-N-329-A-0',
  'medical-N-498-A-0',
  'medical-N-1636-A-0',
  'medical-N-2018-A-0',
  'medical-N-2257-A-0',
  'medical-N-2259-A-0',
  'medical-N-2260-A-0',
  'medical-N-2263-A-0',
  'medical-N-2299-A-0',
  'medical-N-2703-A-0',
  'medical-N-3095-A-0',
  'medical-N-4585-A-0',
  'medical-N-4590-A-0',
  'medical-N-4591-A-0',
  'medical-N-4592-A-0',
  'medical-N-4852-A-0',
  'medical-N-2262-A-0',
  'medical-N-2662-A-0',
  'medical-N-2706-A-0'],
 4: ['medical-N-11-A-0',
  'medical-N-19-A-0',
  'medical-N-29-A-0',
  'medical-N-30-A-0',
  'medical-N-32-A-0',
  'medical-N-73-A-0',
  'medical-N-107-A-0',
  'medical-N-132-A-0',
  'medical-N-133-A-0',
  'medical-N-134-A-0',
  'medical-N-145-A-0',
  'medical-N-148-A-0',
  'medical-N-149-A-0',
  'medical-N-151-A-0',
  'medical-N-200-A-0',
  'medical-N-202-A-0',
  'medical-N-258-A-0',
  'medical-N-264-A-0',
  'medical-N-307-A-0',
  'medical-N-317-A-0',
  'medical-N-318-A-0',
  'medical-N-377-A-0',
  'medical-N-393-A-0',
  'medical-N-434-A-0',
  'medical-N-440-A-0',
  'medical-N-531-A-0',
  'medical-N-532-A-0',
  'medical-N-533-A-0',
  'medical-N-534-A-0',
  'medical-N-536-A-0',
  'medical-N-576-A-0',
  'medical-N-579-A-0',
  'medical-N-592-A-0',
  'medical-N-606-A-0',
  'medical-N-652-A-0',
  'medical-N-658-A-0',
  'medical-N-687-A-0',
  'medical-N-732-A-0',
  'medical-N-803-A-0',
  'medical-N-806-A-0',
  'medical-N-905-A-0',
  'medical-N-941-A-0',
  'medical-N-1058-A-0',
  'medical-N-1067-A-0',
  'medical-N-1143-A-0',
  'medical-N-1407-A-0',
  'medical-N-1431-A-0',
  'medical-N-1464-A-0',
  'medical-N-1472-A-0',
  'medical-N-1517-A-0',
  'medical-N-1523-A-0',
  'medical-N-1621-A-0',
  'medical-N-1738-A-0',
  'medical-N-1739-A-0',
  'medical-N-1794-A-0',
  'medical-N-1878-A-0',
  'medical-N-1880-A-0',
  'medical-N-2066-A-0',
  'medical-N-2169-A-0',
  'medical-N-2225-A-0',
  'medical-N-2235-A-0',
  'medical-N-2253-A-0',
  'medical-N-2414-A-0',
  'medical-N-2435-A-0',
  'medical-N-2521-A-0',
  'medical-N-2589-A-0',
  'medical-N-2611-A-0',
  'medical-N-2614-A-0',
  'medical-N-2639-A-0',
  'medical-N-2645-A-0',
  'medical-N-2709-A-0',
  'medical-N-2807-A-0',
  'medical-N-2811-A-0',
  'medical-N-3084-A-0',
  'medical-N-4452-A-0',
  'medical-N-4627-A-0',
  'medical-N-557-A-0',
  'medical-N-588-A-0',
  'medical-N-1111-A-0',
  'medical-N-1388-A-0',
  'medical-N-2786-A-0'],
 5: ['medical-27-S-5',
  'medical-28-S-2',
  'medical-30-S-0',
  'medical-36-S-4',
  'medical-37-S-0',
  'medical-37-S-2',
  'medical-37-S-3',
  'medical-38-S-0',
  'medical-40-S-1',
  'medical-40-S-2',
  'medical-41-S-0',
  'medical-49-S-4',
  'medical-50-S-0',
  'medical-111-S-2',
  'medical-112-S-0',
  'medical-126-S-7',
  'medical-126-S-8',
  'medical-127-S-1',
  'medical-130-S-8',
  'medical-130-S-9',
  'medical-130-S-10',
  'medical-131-S-0',
  'medical-131-S-1',
  'medical-131-S-4',
  'medical-133-S-9',
  'medical-134-S-1',
  'medical-134-S-2',
  'medical-135-S-6',
  'medical-136-S-1',
  'medical-136-S-5',
  'medical-136-S-6',
  'medical-137-S-0',
  'medical-137-S-1',
  'medical-137-S-2',
  'medical-138-S-2',
  'medical-138-S-3',
  'medical-139-S-0',
  'medical-139-S-1',
  'medical-139-S-3',
  'medical-175-S-2',
  'medical-176-S-1',
  'medical-178-S-2',
  'medical-207-S-3',
  'medical-208-S-0',
  'medical-218-S-5',
  'medical-222-S-2',
  'medical-223-S-0',
  'medical-306-S-6',
  'medical-307-S-1',
  'medical-308-S-10',
  'medical-309-S-1',
  'medical-352-S-8',
  'medical-353-S-1',
  'medical-391-S-4',
  'medical-392-S-0',
  'medical-392-S-1',
  'medical-395-S-2',
  'medical-395-S-5',
  'medical-396-S-6',
  'medical-397-S-1',
  'medical-398-S-2',
  'medical-399-S-2',
  'medical-400-S-1',
  'medical-402-S-8',
  'medical-403-S-1',
  'medical-403-S-2',
  'medical-405-S-3',
  'medical-405-S-5',
  'medical-406-S-1',
  'medical-406-S-3',
  'medical-406-S-5',
  'medical-419-S-5',
  'medical-426-S-5',
  'medical-426-S-6',
  'medical-426-S-7',
  'medical-427-S-0',
  'medical-427-S-2',
  'medical-430-S-5',
  'medical-430-S-6',
  'medical-430-S-7',
  'medical-430-S-8',
  'medical-430-S-9',
  'medical-473-S-0',
  'medical-487-S-4',
  'medical-504-S-5',
  'medical-513-S-3',
  'medical-531-S-2',
  'medical-536-S-2',
  'medical-536-S-3',
  'medical-536-S-4',
  'medical-537-S-0',
  'medical-537-S-1',
  'medical-537-S-9',
  'medical-538-S-0',
  'medical-538-S-1',
  'medical-538-S-4',
  'medical-539-S-0',
  'medical-550-S-3',
  'medical-N-3132-A-0'],
 6: ['medical-12-S-3',
  'medical-98-S-5',
  'medical-99-S-1',
  'medical-99-S-2',
  'medical-100-S-7',
  'medical-101-S-1',
  'medical-103-S-2',
  'medical-124-S-2',
  'medical-169-S-2',
  'medical-194-S-4',
  'medical-195-S-1',
  'medical-195-S-2',
  'medical-195-S-3',
  'medical-196-S-7',
  'medical-197-S-1',
  'medical-199-S-2',
  'medical-234-S-5',
  'medical-288-S-2',
  'medical-288-S-4',
  'medical-288-S-5',
  'medical-301-S-7',
  'medical-327-S-5',
  'medical-327-S-6',
  'medical-345-S-4',
  'medical-345-S-5',
  'medical-346-S-0',
  'medical-346-S-1',
  'medical-377-S-2',
  'medical-378-S-0',
  'medical-378-S-1',
  'medical-378-S-2',
  'medical-401-S-6',
  'medical-433-S-2',
  'medical-433-S-4',
  'medical-433-S-5',
  'medical-471-S-5',
  'medical-472-S-1',
  'medical-477-S-6',
  'medical-478-S-2',
  'medical-478-S-3',
  'medical-478-S-4',
  'medical-491-S-3',
  'medical-492-S-1',
  'medical-493-S-1',
  'medical-N-128-A-0',
  'medical-N-262-A-0',
  'medical-N-765-A-0',
  'medical-N-2571-A-0'],
 7: ['medical-63-S-6',
  'medical-80-S-1',
  'medical-80-S-2',
  'medical-88-S-4',
  'medical-98-S-2',
  'medical-108-S-2',
  'medical-118-S-2',
  'medical-144-S-3',
  'medical-144-S-5',
  'medical-145-S-1',
  'medical-145-S-5',
  'medical-146-S-1',
  'medical-147-S-6',
  'medical-165-S-4',
  'medical-166-S-1',
  'medical-184-S-0',
  'medical-189-S-4',
  'medical-194-S-2',
  'medical-204-S-3',
  'medical-205-S-2',
  'medical-218-S-2',
  'medical-218-S-12',
  'medical-219-S-1',
  'medical-244-S-2',
  'medical-256-S-0',
  'medical-280-S-2',
  'medical-286-S-2',
  'medical-301-S-5',
  'medical-322-S-0',
  'medical-359-S-0',
  'medical-359-S-3',
  'medical-359-S-4',
  'medical-360-S-6',
  'medical-361-S-1',
  'medical-432-S-1',
  'medical-451-S-2',
  'medical-477-S-4',
  'medical-478-S-0',
  'medical-484-S-2',
  'medical-492-S-0',
  'medical-522-S-7',
  'medical-N-316-A-0',
  'medical-N-2023-A-0'],
 8: ['medical-59-S-0',
  'medical-59-S-2',
  'medical-59-S-4',
  'medical-60-S-0',
  'medical-60-S-1',
  'medical-61-S-2',
  'medical-62-S-1',
  'medical-75-S-3',
  'medical-76-S-0',
  'medical-140-S-0',
  'medical-140-S-1',
  'medical-140-S-2',
  'medical-140-S-3',
  'medical-141-S-0',
  'medical-141-S-1',
  'medical-355-S-1',
  'medical-355-S-2',
  'medical-372-S-2',
  'medical-373-S-0',
  'medical-375-S-7',
  'medical-376-S-0',
  'medical-453-S-1',
  'medical-453-S-2',
  'medical-453-S-3',
  'medical-454-S-0',
  'medical-455-S-4',
  'medical-456-S-0',
  'medical-N-38-A-0',
  'medical-N-416-A-0',
  'medical-N-639-A-0',
  'medical-N-1142-A-0',
  'medical-N-1286-A-0',
  'medical-N-1305-A-0',
  'medical-N-1519-A-0',
  'medical-N-1546-A-0',
  'medical-N-1549-A-0',
  'medical-N-1556-A-0',
  'medical-N-1566-A-0',
  'medical-N-1710-A-0',
  'medical-N-1713-A-0',
  'medical-N-1899-A-0',
  'medical-N-1901-A-0',
  'medical-N-1947-A-0',
  'medical-N-1951-A-0',
  'medical-N-1953-A-0',
  'medical-N-3451-A-0',
  'medical-N-3456-A-0',
  'medical-N-3943-A-0',
  'medical-N-6441-A-0',
  'medical-N-6445-A-0',
  'medical-N-1624-A-0',
  'medical-N-3474-A-0'],
 9: ['medical-99-S-3',
  'medical-100-S-0',
  'medical-100-S-1',
  'medical-179-S-0',
  'medical-179-S-1',
  'medical-179-S-2',
  'medical-179-S-3',
  'medical-179-S-4',
  'medical-180-S-0',
  'medical-180-S-1',
  'medical-180-S-2',
  'medical-183-S-1',
  'medical-195-S-4',
  'medical-196-S-0',
  'medical-196-S-1',
  'medical-485-S-2',
  'medical-N-146-A-0',
  'medical-N-168-A-0',
  'medical-N-360-A-0',
  'medical-N-1185-A-0',
  'medical-N-2111-A-0',
  'medical-N-2534-A-0',
  'medical-N-3996-A-0',
  'medical-N-4002-A-0',
  'medical-N-4003-A-0',
  'medical-N-6589-A-0'],
 10: ['medical-85-S-3',
  'medical-86-S-0',
  'medical-108-S-4',
  'medical-109-S-1',
  'medical-119-S-2',
  'medical-119-S-3',
  'medical-119-S-4',
  'medical-124-S-1',
  'medical-151-S-4',
  'medical-152-S-1',
  'medical-152-S-4',
  'medical-152-S-5',
  'medical-153-S-0',
  'medical-153-S-1',
  'medical-153-S-2',
  'medical-153-S-3',
  'medical-153-S-4',
  'medical-153-S-5',
  'medical-153-S-6',
  'medical-154-S-0',
  'medical-154-S-1',
  'medical-171-S-2',
  'medical-171-S-4',
  'medical-172-S-1',
  'medical-204-S-5',
  'medical-205-S-1',
  'medical-234-S-0',
  'medical-234-S-1',
  'medical-239-S-5',
  'medical-239-S-6',
  'medical-239-S-7',
  'medical-240-S-0',
  'medical-259-S-3',
  'medical-259-S-5',
  'medical-260-S-3',
  'medical-261-S-2',
  'medical-292-S-4',
  'medical-293-S-0',
  'medical-364-S-3',
  'medical-365-S-0',
  'medical-379-S-3',
  'medical-380-S-1',
  'medical-381-S-2',
  'medical-412-S-0',
  'medical-494-S-2',
  'medical-494-S-3',
  'medical-495-S-1',
  'medical-495-S-2',
  'medical-495-S-6',
  'medical-497-S-4',
  'medical-497-S-5',
  'medical-498-S-0',
  'medical-N-2207-A-0',
  'medical-N-2220-A-0',
  'medical-N-6588-A-0',
  'medical-N-2763-A-0',
  'medical-N-8234-A-0'],
 11: ['medical-167-S-3',
  'medical-167-S-4',
  'medical-168-S-0',
  'medical-169-S-1',
  'medical-173-S-4',
  'medical-174-S-0',
  'medical-174-S-1',
  'medical-174-S-2',
  'medical-174-S-3',
  'medical-176-S-0',
  'medical-343-S-0',
  'medical-343-S-2',
  'medical-343-S-3',
  'medical-343-S-4',
  'medical-344-S-0',
  'medical-344-S-2',
  'medical-344-S-4',
  'medical-345-S-0',
  'medical-345-S-1',
  'medical-346-S-3',
  'medical-346-S-4',
  'medical-348-S-7',
  'medical-349-S-3',
  'medical-349-S-4',
  'medical-349-S-5',
  'medical-349-S-6',
  'medical-349-S-7',
  'medical-350-S-0',
  'medical-350-S-1',
  'medical-350-S-2',
  'medical-350-S-3',
  'medical-350-S-4',
  'medical-351-S-3',
  'medical-352-S-0',
  'medical-352-S-1',
  'medical-352-S-3',
  'medical-352-S-4',
  'medical-353-S-3',
  'medical-354-S-0',
  'medical-354-S-2',
  'medical-354-S-4',
  'medical-N-857-A-0',
  'medical-N-1527-A-0',
  'medical-N-3085-A-0',
  'medical-N-3783-A-0',
  'medical-N-3784-A-0',
  'medical-N-3788-A-0',
  'medical-N-3795-A-0',
  'medical-N-6203-A-0',
  'medical-N-6224-A-0'],
 12: ['medical-128-S-0',
  'medical-396-S-1',
  'medical-409-S-0',
  'medical-413-S-2',
  'medical-413-S-3',
  'medical-413-S-4',
  'medical-413-S-5',
  'medical-413-S-6',
  'medical-414-S-0',
  'medical-420-S-2',
  'medical-421-S-2',
  'medical-421-S-3',
  'medical-421-S-4',
  'medical-422-S-0',
  'medical-422-S-1',
  'medical-422-S-2',
  'medical-423-S-1',
  'medical-423-S-2',
  'medical-423-S-3',
  'medical-424-S-1',
  'medical-424-S-3',
  'medical-425-S-0',
  'medical-425-S-4',
  'medical-425-S-5',
  'medical-426-S-0',
  'medical-522-S-2',
  'medical-532-S-5',
  'medical-533-S-0',
  'medical-N-7122-A-0',
  'medical-N-7128-A-0'],
 13: ['medical-87-S-4',
  'medical-88-S-0',
  'medical-105-S-0',
  'medical-155-S-4',
  'medical-156-S-0',
  'medical-168-S-2',
  'medical-168-S-3',
  'medical-169-S-0',
  'medical-172-S-9',
  'medical-200-S-2',
  'medical-201-S-0',
  'medical-262-S-1',
  'medical-262-S-2',
  'medical-297-S-5',
  'medical-298-S-1',
  'medical-298-S-3',
  'medical-344-S-3',
  'medical-366-S-2',
  'medical-438-S-1',
  'medical-438-S-2',
  'medical-N-71-A-0',
  'medical-N-234-A-0',
  'medical-N-237-A-0',
  'medical-N-245-A-0',
  'medical-N-1257-A-0',
  'medical-N-1642-A-0',
  'medical-N-2255-A-0',
  'medical-N-2271-A-0',
  'medical-N-2275-A-0',
  'medical-N-2452-A-0',
  'medical-N-2689-A-0',
  'medical-N-2280-A-0',
  'medical-N-3875-A-0'],
 14: ['medical-229-S-3',
  'medical-229-S-4',
  'medical-230-S-0',
  'medical-230-S-1',
  'medical-230-S-2',
  'medical-230-S-3',
  'medical-231-S-0',
  'medical-231-S-1',
  'medical-231-S-2',
  'medical-231-S-3',
  'medical-243-S-2',
  'medical-244-S-0',
  'medical-244-S-1',
  'medical-246-S-1',
  'medical-251-S-3',
  'medical-252-S-0',
  'medical-252-S-1',
  'medical-252-S-2',
  'medical-252-S-3',
  'medical-252-S-4',
  'medical-252-S-6',
  'medical-252-S-7',
  'medical-252-S-8',
  'medical-253-S-0',
  'medical-253-S-1',
  'medical-253-S-2',
  'medical-253-S-3',
  'medical-254-S-0',
  'medical-254-S-1',
  'medical-262-S-3',
  'medical-265-S-5',
  'medical-266-S-1',
  'medical-N-4374-A-0',
  'medical-N-4383-A-0',
  'medical-N-4434-A-0',
  'medical-N-4435-A-0',
  'medical-N-4438-A-0'],
 15: ['medical-89-S-4',
  'medical-147-S-0',
  'medical-157-S-4',
  'medical-274-S-1',
  'medical-348-S-11',
  'medical-349-S-2',
  'medical-367-S-9',
  'medical-400-S-2',
  'medical-422-S-3',
  'medical-504-S-3',
  'medical-552-S-2',
  'medical-N-3656-A-0'],
 16: ['medical-34-S-2',
  'medical-458-S-0',
  'medical-458-S-1',
  'medical-458-S-3',
  'medical-458-S-4',
  'medical-459-S-0',
  'medical-459-S-1',
  'medical-459-S-2',
  'medical-459-S-3',
  'medical-459-S-4',
  'medical-460-S-0',
  'medical-460-S-2',
  'medical-460-S-3',
  'medical-461-S-0',
  'medical-461-S-1',
  'medical-461-S-2',
  'medical-461-S-3',
  'medical-462-S-0',
  'medical-462-S-3',
  'medical-462-S-4',
  'medical-463-S-0',
  'medical-463-S-2',
  'medical-463-S-3',
  'medical-463-S-4',
  'medical-464-S-0',
  'medical-467-S-2',
  'medical-467-S-4',
  'medical-468-S-0',
  'medical-468-S-1',
  'medical-468-S-2',
  'medical-468-S-3',
  'medical-469-S-0',
  'medical-469-S-1',
  'medical-470-S-1',
  'medical-470-S-2',
  'medical-470-S-4',
  'medical-N-4119-A-0',

In [11]:
#H node->cluster mapping
#using top k to avoid disconnected H nodes
_, H_assignments = kmeans.index.search(H_embeddings, 5)
H_assignments, H_assignments.shape
H_node_clusters = {}
for i in range(H_assignments.shape[0]):
    H_node_clusters[medical_embedding_H_ids[i]] = H_assignments[i].tolist()

H_node_clusters

{'medical-H-17': [25, 57, 59, 19, 31],
 'medical-H-11': [31, 8, 19, 4, 58],
 'medical-H-20': [19, 60, 5, 4, 57],
 'medical-H-7': [4, 32, 19, 37, 49],
 'medical-H-27': [58, 19, 60, 5, 15],
 'medical-H-1': [13, 3, 19, 4, 48],
 'medical-H-23': [19, 31, 4, 37, 52],
 'medical-H-22': [19, 31, 4, 25, 30],
 'medical-H-4': [48, 19, 35, 58, 60],
 'medical-H-6': [19, 58, 4, 60, 43],
 'medical-H-5': [19, 18, 52, 4, 60],
 'medical-H-25': [29, 4, 53, 19, 48],
 'medical-H-36': [31, 37, 19, 9, 4],
 'medical-H-3': [51, 19, 28, 54, 4],
 'medical-H-26': [33, 12, 4, 19, 48],
 'medical-H-19': [11, 30, 19, 4, 31],
 'medical-H-21': [19, 48, 4, 60, 39],
 'medical-H-24': [52, 19, 37, 18, 4],
 'medical-H-14': [4, 21, 19, 47, 22],
 'medical-H-8': [19, 60, 58, 55, 45],
 'medical-H-15': [50, 14, 19, 4, 30],
 'medical-H-9': [4, 8, 49, 19, 48],
 'medical-H-28': [19, 60, 5, 53, 45],
 'medical-H-18': [19, 4, 47, 60, 54],
 'medical-H-12': [16, 17, 19, 40, 4],
 'medical-H-0': [56, 43, 4, 34, 19],
 'medical-H-30': [4, 19, 43, 21, 48],
 'medical-H-13': [44, 19, 36, 4, 0],
 'medical-H-2': [19, 45, 5, 2, 60],
 'medical-H-10': [1, 19, 4, 9, 50],
 'medical-H-16': [20, 19, 58, 60, 4],
 'medical-H-31': [19, 60, 58, 31, 4],
 'medical-H-29': [34, 19, 4, 17, 52],
 'medical-H-35': [43, 27, 34, 19, 4],
 'medical-H-33': [34, 43, 19, 58, 24],
 'medical-H-37': [4, 48, 19, 43, 58],
 'medical-H-32': [19, 60, 48, 58, 4],
 'medical-H-38': [19, 60, 47, 58, 31],
 'medical-H-34': [24, 53, 19, 43, 45],
 'medical-H-39': [31, 19, 36, 4, 58],
 'medical-H-40': [19, 4, 43, 47, 3]}

In [12]:
#create and link H and O nodes
for H_id in medical_summary["node_id"].tolist():
    #ids
    O_id = f"{H_id}-O-0"
    #data
    H_content = medical_summary[medical_summary["node_id"] == H_id]["community_summary"].iloc[0]
    O_content = medical_overview[medical_overview["node_id"] == O_id]["community_overview"].iloc[0]
    #node creation
    H_node = Node(
        id = H_id,
        node_type = "H",
        source = "",
        content = H_content
    )

    O_node = Node(
        id = O_id,
        node_type = "O",
        source = "",
        content = O_content
    )

    #link H and O node
    H_node.link(O_node)
    O_node.link(H_node)

    #link H node with S,A nodes in the same community and cluster
    current_cluster = set()
    for cluster_id in H_node_clusters[H_id]:
        current_cluster |= set(clusters[cluster_id])
    current_community = set(communities_medical[int(re.search(r"medical-H-(\d+)", H_id).group(1))])
    relevant_nodes = current_cluster&current_community
    for node_id in relevant_nodes:
        if node_id == H_id:
            continue
        relevant_node = medical_g2[node_id]
        relevant_node.link(H_node)
        H_node.link(relevant_node)
    
    #add to node list
    medical_g2[H_id] = H_node
    medical_g2[O_id] = O_node

In [13]:
for node_id in list(medical_g2.keys()):
    node = medical_g2[node_id]
    if node.node_type == "H" and len(node.edges) <= 1:
        print(node_id)
        medical_g2.pop(node_id, None)

In [14]:
with open(f"{root_path}/graphs/data/graphs/G3_medical_community_augmented_graph.pkl", "wb") as f:
    pickle.dump(medical_g2, f)
with open(f"{root_path}/graphs/data/graphs/G3_medical_community_augmented_graph.pkl", "rb") as f:
    medical_g3 = pickle.load(f)

In [15]:
#create and link T nodes
for node_id in list(medical_g3.keys()):
    node = medical_g3[node_id]
    if node.node_type != "S":
        continue
    source_id = node.source
    if source_id not in medical_g3:
        T_node = Node(
            id = source_id,
            node_type = "T",
            source = "",
            content = medical_chunks[medical_chunks["node_id"] == source_id]["chunk"].iloc[0]
        )
        medical_g3[source_id] = T_node
    T_node = medical_g3[source_id]
    T_node.link(node)
    node.link(T_node)

In [16]:
with open(f"{root_path}/graphs/data/graphs/G4_text_inserted_graph.pkl", "wb") as f:
    pickle.dump(medical_g3, f)
with open(f"{root_path}/graphs/data/graphs/G4_text_inserted_graph.pkl", "rb") as f:
    medical_g4 = pickle.load(f)
medical_g4

{'medical-0-S-0': <graphs.Node.Node at 0x2081aa1be20>,
 'medical-0-S-0-R-0': <graphs.Node.Node at 0x2081708b4c0>,
 'medical-0-S-0-R-1': <graphs.Node.Node at 0x208782df370>,
 'medical-0-S-0-R-2': <graphs.Node.Node at 0x208782df3a0>,
 'medical-0-S-0-R-3': <graphs.Node.Node at 0x208782df3d0>,
 'medical-0-S-0-R-4': <graphs.Node.Node at 0x208782df400>,
 'medical-0-S-1': <graphs.Node.Node at 0x208782df430>,
 'medical-0-S-1-R-0': <graphs.Node.Node at 0x208782df460>,
 'medical-0-S-1-R-1': <graphs.Node.Node at 0x208782df490>,
 'medical-0-S-1-R-2': <graphs.Node.Node at 0x208782df4c0>,
 'medical-0-S-1-R-3': <graphs.Node.Node at 0x208782df4f0>,
 'medical-0-S-1-R-4': <graphs.Node.Node at 0x208782df520>,
 'medical-0-S-1-R-5': <graphs.Node.Node at 0x208782df550>,
 'medical-0-S-1-R-6': <graphs.Node.Node at 0x208782df580>,
 'medical-0-S-1-R-7': <graphs.Node.Node at 0x208782df5b0>,
 'medical-0-S-1-R-8': <graphs.Node.Node at 0x208782df5e0>,
 'medical-0-S-1-R-9': <graphs.Node.Node at 0x208782df610>,
 'medical-0-S-1-R-10': <graphs.Node.Node at 0x208782df640>,
 'medical-0-S-1-R-11': <graphs.Node.Node at 0x208782df670>,
 'medical-0-S-1-R-12': <graphs.Node.Node at 0x208782df6a0>,
 'medical-0-S-2': <graphs.Node.Node at 0x208782df6d0>,
 'medical-0-S-2-R-0': <graphs.Node.Node at 0x208782df700>,
 'medical-0-S-2-R-1': <graphs.Node.Node at 0x208782df730>,
 'medical-0-S-2-R-2': <graphs.Node.Node at 0x208782df760>,
 'medical-0-S-2-R-3': <graphs.Node.Node at 0x208782df790>,
 'medical-0-S-3': <graphs.Node.Node at 0x208782df7c0>,
 'medical-0-S-3-R-0': <graphs.Node.Node at 0x208782df7f0>,
 'medical-0-S-3-R-1': <graphs.Node.Node at 0x208782df820>,
 'medical-0-S-3-R-2': <graphs.Node.Node at 0x208782df850>,
 'medical-0-S-3-R-3': <graphs.Node.Node at 0x208782df880>,
 'medical-0-S-3-R-4': <graphs.Node.Node at 0x208782df8b0>,
 'medical-0-S-3-R-5': <graphs.Node.Node at 0x208782df8e0>,
 'medical-0-S-3-R-6': <graphs.Node.Node at 0x208782df910>,
 'medical-0-S-3-R-7': <graphs.Node.Node at 0x208782df940>,
 'medical-0-S-3-R-8': <graphs.Node.Node at 0x208782df970>,
 'medical-0-S-3-R-9': <graphs.Node.Node at 0x208782df9a0>,
 'medical-0-S-3-R-10': <graphs.Node.Node at 0x208782df9d0>,
 'medical-0-S-3-R-11': <graphs.Node.Node at 0x208782dfa00>,
 'medical-0-S-3-R-12': <graphs.Node.Node at 0x208782dfa30>,
 'medical-0-S-3-R-13': <graphs.Node.Node at 0x208782dfa60>,
 'medical-0-S-3-R-14': <graphs.Node.Node at 0x208782dfa90>,
 'medical-0-S-3-R-15': <graphs.Node.Node at 0x208782dfac0>,
 'medical-0-S-3-R-16': <graphs.Node.Node at 0x208782dfaf0>,
 'medical-0-S-3-R-17': <graphs.Node.Node at 0x208782dfb20>,
 'medical-0-S-3-R-18': <graphs.Node.Node at 0x208782dfb50>,
 'medical-0-S-3-R-19': <graphs.Node.Node at 0x208782dfb80>,
 'medical-0-S-3-R-20': <graphs.Node.Node at 0x208782dfbb0>,
 'medical-0-S-3-R-21': <graphs.Node.Node at 0x208782dfbe0>,
 'medical-0-S-3-R-22': <graphs.Node.Node at 0x208782dfc10>,
 'medical-0-S-3-R-23': <graphs.Node.Node at 0x208782dfc40>,
 'medical-0-S-3-R-24': <graphs.Node.Node at 0x208782dfc70>,
 'medical-0-S-3-R-25': <graphs.Node.Node at 0x208782dfca0>,
 'medical-0-S-3-R-26': <graphs.Node.Node at 0x208782dfcd0>,
 'medical-0-S-3-R-27': <graphs.Node.Node at 0x208782dfd00>,
 'medical-1-S-0': <graphs.Node.Node at 0x208782dfd30>,
 'medical-1-S-0-R-0': <graphs.Node.Node at 0x208782dfd60>,
 'medical-1-S-0-R-1': <graphs.Node.Node at 0x208782dfd90>,
 'medical-1-S-0-R-2': <graphs.Node.Node at 0x208782dfdc0>,
 'medical-1-S-0-R-3': <graphs.Node.Node at 0x208782dfdf0>,
 'medical-1-S-0-R-4': <graphs.Node.Node at 0x208782dfe20>,
 'medical-1-S-0-R-5': <graphs.Node.Node at 0x208782dfe50>,
 'medical-1-S-0-R-6': <graphs.Node.Node at 0x208782dfe80>,
 'medical-1-S-0-R-7': <graphs.Node.Node at 0x208782dfeb0>,
 'medical-1-S-0-R-8': <graphs.Node.Node at 0x208782dfee0>,
 'medical-1-S-0-R-9': <graphs.Node.Node at 0x208782dff10>,
 'medical-1-S-0-R-10': <graphs.Node.Node at 0x208782dff40>,
 'medical-1-S-1': <graphs.Node.Node at 0x208782dff70>,
 'medical-1-S-1-R-0': <graphs.Node.Node at 0x208782dffa0>,
 'medical-1-S-1-R-1': <graphs.Node.Node at 0x208782dffd0>,
 'medical-1-S-1-R-2': <graphs.Node.Node at 0x2087831c040>,
 'medical-1-S-1-R-3': <graphs.Node.Node at 0x2087831c070>,
 'medical-1-S-1-R-4': <graphs.Node.Node at 0x2087831c0a0>,
 'medical-1-S-2': <graphs.Node.Node at 0x2087831c0d0>,
 'medical-1-S-2-R-0': <graphs.Node.Node at 0x2087831c100>,
 'medical-1-S-2-R-1': <graphs.Node.Node at 0x2087831c130>,
 'medical-1-S-2-R-2': <graphs.Node.Node at 0x2087831c160>,
 'medical-1-S-2-R-3': <graphs.Node.Node at 0x2087831c190>,
 'medical-1-S-2-R-4': <graphs.Node.Node at 0x2087831c1c0>,
 'medical-1-S-2-R-5': <graphs.Node.Node at 0x2087831c1f0>,
 'medical-1-S-2-R-6': <graphs.Node.Node at 0x2087831c220>,
 'medical-1-S-2-R-7': <graphs.Node.Node at 0x2087831c250>,
 'medical-1-S-2-R-8': <graphs.Node.Node at 0x2087831c280>,
 'medical-1-S-2-R-9': <graphs.Node.Node at 0x2087831c2b0>,
 'medical-1-S-2-R-10': <graphs.Node.Node at 0x2087831c2e0>,
 'medical-1-S-2-R-11': <graphs.Node.Node at 0x2087831c310>,
 'medical-1-S-2-R-12': <graphs.Node.Node at 0x2087831c340>,
 'medical-1-S-2-R-13': <graphs.Node.Node at 0x2087831c370>,
 'medical-1-S-2-R-14': <graphs.Node.Node at 0x2087831c3a0>,
 'medical-1-S-2-R-15': <graphs.Node.Node at 0x2087831c3d0>,
 'medical-1-S-2-R-16': <graphs.Node.Node at 0x2087831c400>,
 'medical-1-S-2-R-17': <graphs.Node.Node at 0x2087831c430>,
 'medical-1-S-3': <graphs.Node.Node at 0x2087831c460>,
 'medical-1-S-3-R-0': <graphs.Node.Node at 0x2087831c490>,
 'medical-1-S-3-R-1': <graphs.Node.Node at 0x2087831c4c0>,
 'medical-1-S-3-R-2': <graphs.Node.Node at 0x2087831c4f0>,
 'medical-1-S-4': <graphs.Node.Node at 0x2087831c520>,
 'medical-1-S-4-R-0': <graphs.Node.Node at 0x2087831c550>,
 'medical-1-S-4-R-1': <graphs.Node.Node at 0x2087831c580>,
 'medical-1-S-4-R-2': <graphs.Node.Node at 0x2087831c5b0>,
 'medical-1-S-4-R-3': <graphs.Node.Node at 0x2087831c5e0>,
 'medical-1-S-4-R-4': <graphs.Node.Node at 0x2087831c610>,
 'medical-1-S-4-R-5': <graphs.Node.Node at 0x2087831c640>,
 'medical-1-S-4-R-6': <graphs.Node.Node at 0x2087831c670>,
 'medical-1-S-4-R-7': <graphs.Node.Node at 0x2087831c6a0>,
 'medical-2-S-0': <graphs.Node.Node at 0x2087831c6d0>,
 'medical-2-S-0-R-0': <graphs.Node.Node at 0x2087831c700>,
 'medical-2-S-0-R-1': <graphs.Node.Node at 0x2087831c730>,
 'medical-2-S-0-R-2': <graphs.Node.Node at 0x2087831c760>,
 'medical-2-S-0-R-3': <graphs.Node.Node at 0x2087831c790>,
 'medical-2-S-0-R-4': <graphs.Node.Node at 0x2087831c7c0>,
 'medical-2-S-0-R-5': <graphs.Node.Node at 0x2087831c7f0>,
 'medical-2-S-0-R-6': <graphs.Node.Node at 0x2087831c820>,
 'medical-2-S-0-R-7': <graphs.Node.Node at 0x2087831c850>,
 'medical-2-S-0-R-8': <graphs.Node.Node at 0x2087831c880>,
 'medical-2-S-0-R-9': <graphs.Node.Node at 0x2087831c8b0>,
 'medical-2-S-0-R-10': <graphs.Node.Node at 0x2087831c8e0>,
 'medical-2-S-0-R-11': <graphs.Node.Node at 0x2087831c910>,
 'medical-2-S-0-R-12': <graphs.Node.Node at 0x2087831c940>,
 'medical-2-S-0-R-13': <graphs.Node.Node at 0x2087831c970>,
 'medical-2-S-0-R-14': <graphs.Node.Node at 0x2087831c9a0>,
 'medical-2-S-0-R-15': <graphs.Node.Node at 0x2087831c9d0>,
 'medical-2-S-0-R-16': <graphs.Node.Node at 0x2087831ca00>,
 'medical-2-S-0-R-17': <graphs.Node.Node at 0x2087831ca30>,
 'medical-2-S-0-R-18': <graphs.Node.Node at 0x2087831ca60>,
 'medical-2-S-0-R-19': <graphs.Node.Node at 0x2087831ca90>,
 'medical-2-S-0-R-20': <graphs.Node.Node at 0x2087831cac0>,
 'medical-2-S-0-R-21': <graphs.Node.Node at 0x2087831caf0>,
 'medical-2-S-1': <graphs.Node.Node at 0x2087831cb20>,
 'medical-2-S-1-R-0': <graphs.Node.Node at 0x2087831cb50>,
 'medical-2-S-1-R-1': <graphs.Node.Node at 0x2087831cb80>,
 'medical-2-S-1-R-2': <graphs.Node.Node at 0x2087831cbb0>,
 'medical-2-S-1-R-3': <graphs.Node.Node at 0x2087831cbe0>,
 'medical-2-S-1-R-4': <graphs.Node.Node at 0x2087831cc10>,
 'medical-2-S-1-R-5': <graphs.Node.Node at 0x2087831cc40>,
 'medical-2-S-1-R-6': <graphs.Node.Node at 0x2087831cc70>,
 'medical-2-S-1-R-7': <graphs.Node.Node at 0x2087831cca0>,
 'medical-2-S-1-R-8': <graphs.Node.Node at 0x2087831ccd0>,
 'medical-2-S-1-R-9': <graphs.Node.Node at 0x2087831cd00>,
 'medical-2-S-1-R-10': <graphs.Node.Node at 0x2087831cd30>,
 'medical-2-S-1-R-11': <graphs.Node.Node at 0x2087831cd60>,
 'medical-2-S-1-R-12': <graphs.Node.Node at 0x2087831cd90>,
 'medical-2-S-1-R-13': <graphs.Node.Node at 0x2087831cdc0>,
 'medical-2-S-1-R-14': <graphs.Node.Node at 0x2087831cdf0>,
 'medical-2-S-1-R-15': <graphs.Node.Node at 0x2087831ce20>,
 'medical-2-S-2': <graphs.Node.Node at 0x2087831ce50>,
 'medical-2-S-2-R-0': <graphs.Node.Node at 0x2087831ce80>,
 'medical-2-S-2-R-1': <graphs.Node.Node at 0x2087831ceb0>,
 'medical-2-S-2-R-2': <graphs.Node.Node at 0x2087831cee0>,
 'medical-2-S-2-R-3': <graphs.Node.Node at 0x2087831cf10>,
 'medical-2-S-2-R-4': <graphs.Node.Node at 0x2087831cf40>,
 'medical-3-S-0': <graphs.Node.Node at 0x2087831cf70>,
 'medical-3-S-0-R-0': <graphs.Node.Node at 0x2087831cfa0>,
 'medical-3-S-0-R-1': <graphs.Node.Node at 0x2087831cfd0>,
 'medical-3-S-0-R-2': <graphs.Node.Node at 0x2087831d000>,
 'medical-3-S-0-R-3': <graphs.Node.Node at 0x2087831d030>,
 'medical-3-S-0-R-4': <graphs.Node.Node at 0x2087831d060>,
 'medical-3-S-1': <graphs.Node.Node at 0x2087831d090>,
 'medical-3-S-1-R-0': <graphs.Node.Node at 0x2087831d0c0>,
 'medical-3-S-1-R-1': <graphs.Node.Node at 0x2087831d0f0>,
 'medical-3-S-1-R-2': <graphs.Node.Node at 0x2087831d120>,
 'medical-3-S-1-R-3': <graphs.Node.Node at 0x2087831d150>,
 'medical-3-S-2': <graphs.Node.Node at 0x2087831d180>,
 'medical-3-S-2-R-0': <graphs.Node.Node at 0x2087831d1b0>,
 'medical-3-S-2-R-1': <graphs.Node.Node at 0x2087831d1e0>,
 'medical-3-S-2-R-2': <graphs.Node.Node at 0x2087831d210>,
 'medical-3-S-2-R-3': <graphs.Node.Node at 0x2087831d240>,
 'medical-3-S-2-R-4': <graphs.Node.Node at 0x2087831d270>,
 'medical-3-S-2-R-5': <graphs.Node.Node at 0x2087831d2a0>,
 'medical-3-S-2-R-6': <graphs.Node.Node at 0x2087831d2d0>,
 'medical-3-S-2-R-7': <graphs.Node.Node at 0x2087831d300>,
 'medical-3-S-2-R-8': <graphs.Node.Node at 0x2087831d330>,
 'medical-3-S-3': <graphs.Node.Node at 0x2087831d360>,
 'medical-3-S-3-R-0': <graphs.Node.Node at 0x2087831d390>,
 'medical-3-S-3-R-1': <graphs.Node.Node at 0x2087831d3c0>,
 'medical-3-S-3-R-2': <graphs.Node.Node at 0x2087831d3f0>,
 'medical-3-S-3-R-3': <graphs.Node.Node at 0x2087831d420>,
 'medical-3-S-3-R-4': <graphs.Node.Node at 0x2087831d450>,
 'medical-3-S-3-R-5': <graphs.Node.Node at 0x2087831d480>,
 'medical-3-S-3-R-6': <graphs.Node.Node at 0x2087831d4b0>,
 'medical-3-S-3-R-7': <graphs.Node.Node at 0x2087831d4e0>,
 'medical-4-S-0': <graphs.Node.Node at 0x2087831d510>,
 'medical-4-S-0-R-0': <graphs.Node.Node at 0x2087831d540>,
 'medical-4-S-0-R-1': <graphs.Node.Node at 0x2087831d570>,
 'medical-4-S-0-R-2': <graphs.Node.Node at 0x2087831d5a0>,
 'medical-4-S-0-R-3': <graphs.Node.Node at 0x2087831d5d0>,
 'medical-4-S-0-R-4': <graphs.Node.Node at 0x2087831d600>,
 'medical-4-S-0-R-5': <graphs.Node.Node at 0x2087831d630>,
 'medical-4-S-0-R-6': <graphs.Node.Node at 0x2087831d660>,
 'medical-4-S-1': <graphs.Node.Node at 0x2087831d690>,
 'medical-4-S-1-R-0': <graphs.Node.Node at 0x2087831d6c0>,
 'medical-4-S-1-R-1': <graphs.Node.Node at 0x2087831d6f0>,
 'medical-4-S-1-R-2': <graphs.Node.Node at 0x2087831d720>,
 'medical-5-S-0': <graphs.Node.Node at 0x2087831d750>,
 'medical-5-S-0-R-0': <graphs.Node.Node at 0x2087831d780>,
 'medical-5-S-0-R-1': <graphs.Node.Node at 0x2087831d7b0>,
 'medical-5-S-0-R-2': <graphs.Node.Node at 0x2087831d7e0>,
 'medical-5-S-0-R-3': <graphs.Node.Node at 0x2087831d810>,
 'medical-5-S-0-R-4': <graphs.Node.Node at 0x2087831d840>,
 'medical-5-S-0-R-5': <graphs.Node.Node at 0x2087831d870>,
 'medical-5-S-0-R-6': <graphs.Node.Node at 0x2087831d8a0>,
 'medical-5-S-1': <graphs.Node.Node at 0x2087831d8d0>,
 'medical-5-S-1-R-0': <graphs.Node.Node at 0x2087831d900>,
 'medical-5-S-1-R-1': <graphs.Node.Node at 0x2087831d930>,
 'medical-5-S-1-R-2': <graphs.Node.Node at 0x2087831d960>,
 'medical-5-S-1-R-3': <graphs.Node.Node at 0x2087831d990>,
 'medical-5-S-1-R-4': <graphs.Node.Node at 0x2087831d9c0>,
 'medical-5-S-1-R-5': <graphs.Node.Node at 0x2087831d9f0>,
 'medical-5-S-1-R-6': <graphs.Node.Node at 0x2087831da20>,
 'medical-5-S-1-R-7': <graphs.Node.Node at 0x2087831da50>,
 'medical-5-S-1-R-8': <graphs.Node.Node at 0x2087831da80>,
 'medical-5-S-1-R-9': <graphs.Node.Node at 0x2087831dab0>,
 'medical-5-S-2': <graphs.Node.Node at 0x2087831dae0>,
 'medical-5-S-2-R-0': <graphs.Node.Node at 0x2087831db10>,
 'medical-5-S-2-R-1': <graphs.Node.Node at 0x2087831db40>,
 'medical-5-S-2-R-2': <graphs.Node.Node at 0x2087831db70>,
 'medical-5-S-2-R-3': <graphs.Node.Node at 0x2087831dba0>,
 'medical-5-S-2-R-4': <graphs.Node.Node at 0x2087831dbd0>,
 'medical-5-S-2-R-5': <graphs.Node.Node at 0x2087831dc00>,
 'medical-5-S-2-R-6': <graphs.Node.Node at 0x2087831dc30>,
 'medical-5-S-2-R-7': <graphs.Node.Node at 0x2087831dc60>,
 'medical-5-S-2-R-8': <graphs.Node.Node at 0x2087831dc90>,
 'medical-5-S-2-R-9': <graphs.Node.Node at 0x2087831dcc0>,
 'medical-5-S-2-R-10': <graphs.Node.Node at 0x2087831dcf0>,
 'medical-5-S-2-R-11': <graphs.Node.Node at 0x2087831dd20>,
 'medical-5-S-2-R-12': <graphs.Node.Node at 0x2087831dd50>,
 'medical-5-S-2-R-13': <graphs.Node.Node at 0x2087831dd80>,
 'medical-5-S-2-R-14': <graphs.Node.Node at 0x2087831ddb0>,
 'medical-5-S-2-R-15': <graphs.Node.Node at 0x2087831dde0>,
 'medical-5-S-2-R-16': <graphs.Node.Node at 0x2087831de10>,
 'medical-5-S-2-R-17': <graphs.Node.Node at 0x2087831de40>,
 'medical-5-S-2-R-18': <graphs.Node.Node at 0x2087831de70>,
 'medical-5-S-2-R-19': <graphs.Node.Node at 0x2087831dea0>,
 'medical-5-S-2-R-20': <graphs.Node.Node at 0x2087831ded0>,
 'medical-5-S-2-R-21': <graphs.Node.Node at 0x2087831df00>,
 'medical-5-S-2-R-22': <graphs.Node.Node at 0x2087831df30>,
 'medical-5-S-2-R-23': <graphs.Node.Node at 0x2087831df60>,
 'medical-5-S-2-R-24': <graphs.Node.Node at 0x2087831df90>,
 'medical-5-S-3': <graphs.Node.Node at 0x2087831dfc0>,
 'medical-5-S-3-R-0': <graphs.Node.Node at 0x2087831dff0>,
 'medical-5-S-3-R-1': <graphs.Node.Node at 0x2087831e020>,
 'medical-5-S-3-R-2': <graphs.Node.Node at 0x2087831e050>,
 'medical-5-S-3-R-3': <graphs.Node.Node at 0x2087831e080>,
 'medical-5-S-3-R-4': <graphs.Node.Node at 0x2087831e0b0>,
 'medical-5-S-3-R-5': <graphs.Node.Node at 0x2087831e0e0>,
 'medical-5-S-4': <graphs.Node.Node at 0x2087831e110>,
 'medical-5-S-4-R-0': <graphs.Node.Node at 0x2087831e140>,
 'medical-5-S-4-R-1': <graphs.Node.Node at 0x2087831e170>,
 'medical-5-S-4-R-2': <graphs.Node.Node at 0x2087831e1a0>,
 'medical-5-S-4-R-3': <graphs.Node.Node at 0x2087831e1d0>,
 'medical-5-S-4-R-4': <graphs.Node.Node at 0x2087831e200>,
 'medical-5-S-4-R-5': <graphs.Node.Node at 0x2087831e230>,
 'medical-5-S-4-R-6': <graphs.Node.Node at 0x2087831e260>,
 'medical-5-S-5': <graphs.Node.Node at 0x2087831e290>,
 'medical-5-S-5-R-0': <graphs.Node.Node at 0x2087831e2c0>,
 'medical-5-S-5-R-1': <graphs.Node.Node at 0x2087831e2f0>,
 'medical-5-S-5-R-2': <graphs.Node.Node at 0x2087831e320>,
 'medical-5-S-5-R-3': <graphs.Node.Node at 0x2087831e350>,
 'medical-5-S-5-R-4': <graphs.Node.Node at 0x2087831e380>,
 'medical-5-S-5-R-5': <graphs.Node.Node at 0x2087831e3b0>,
 'medical-5-S-5-R-6': <graphs.Node.Node at 0x2087831e3e0>,
 'medical-5-S-5-R-7': <graphs.Node.Node at 0x2087831e410>,
 'medical-5-S-5-R-8': <graphs.Node.Node at 0x2087831e440>,
 'medical-5-S-5-R-9': <graphs.Node.Node at 0x2087831e470>,
 'medical-5-S-6': <graphs.Node.Node at 0x2087831e4a0>,
 'medical-5-S-6-R-0': <graphs.Node.Node at 0x2087831e4d0>,
 'medical-5-S-6-R-1': <graphs.Node.Node at 0x2087831e500>,
 'medical-5-S-6-R-2': <graphs.Node.Node at 0x2087831e530>,
 'medical-5-S-6-R-3': <graphs.Node.Node at 0x2087831e560>,
 'medical-6-S-0': <graphs.Node.Node at 0x2087831e590>,
 'medical-6-S-0-R-0': <graphs.Node.Node at 0x2087831e5c0>,
 'medical-6-S-0-R-1': <graphs.Node.Node at 0x2087831e5f0>,
 'medical-6-S-0-R-2': <graphs.Node.Node at 0x2087831e620>,
 'medical-6-S-0-R-3': <graphs.Node.Node at 0x2087831e650>,
 'medical-6-S-0-R-4': <graphs.Node.Node at 0x2087831e680>,
 'medical-6-S-0-R-5': <graphs.Node.Node at 0x2087831e6b0>,
 'medical-6-S-0-R-6': <graphs.Node.Node at 0x2087831e6e0>,
 'medical-6-S-0-R-7': <graphs.Node.Node at 0x2087831e710>,
 'medical-6-S-0-R-8': <graphs.Node.Node at 0x2087831e740>,
 'medical-6-S-0-R-9': <graphs.Node.Node at 0x2087831e770>,
 'medical-6-S-0-R-10': <graphs.Node.Node at 0x2087831e7a0>,
 'medical-6-S-0-R-11': <graphs.Node.Node at 0x2087831e7d0>,
 'medical-6-S-0-R-12': <graphs.Node.Node at 0x2087831e800>,
 'medical-6-S-0-R-13': <graphs.Node.Node at 0x2087831e830>,
 'medical-6-S-0-R-14': <graphs.Node.Node at 0x2087831e860>,
 'medical-6-S-1': <graphs.Node.Node at 0x2087831e890>,
 'medical-6-S-1-R-0': <graphs.Node.Node at 0x2087831e8c0>,
 'medical-6-S-1-R-1': <graphs.Node.Node at 0x2087831e8f0>,
 'medical-6-S-1-R-2': <graphs.Node.Node at 0x2087831e920>,
 'medical-6-S-1-R-3': <graphs.Node.Node at 0x2087831e950>,
 'medical-6-S-1-R-4': <graphs.Node.Node at 0x2087831e980>,
 'medical-6-S-1-R-5': <graphs.Node.Node at 0x2087831e9b0>,
 'medical-6-S-1-R-6': <graphs.Node.Node at 0x2087831e9e0>,
 'medical-6-S-1-R-7': <graphs.Node.Node at 0x2087831ea10>,
 'medical-6-S-1-R-8': <graphs.Node.Node at 0x2087831ea40>,
 'medical-6-S-1-R-9': <graphs.Node.Node at 0x2087831ea70>,
 'medical-6-S-1-R-10': <graphs.Node.Node at 0x2087831eaa0>,
 'medical-6-S-1-R-11': <graphs.Node.Node at 0x2087831ead0>,
 'medical-6-S-1-R-12': <graphs.Node.Node at 0x2087831eb00>,
 'medical-6-S-1-R-13': <graphs.Node.Node at 0x2087831eb30>,
 'medical-6-S-1-R-14': <graphs.Node.Node at 0x2087831eb60>,
 'medical-6-S-1-R-15': <graphs.Node.Node at 0x2087831eb90>,
 'medical-6-S-1-R-16': <graphs.Node.Node at 0x2087831ebc0>,
 'medical-6-S-2': <graphs.Node.Node at 0x2087831ebf0>,
 'medical-6-S-2-R-0': <graphs.Node.Node at 0x2087831ec20>,
 'medical-6-S-2-R-1': <graphs.Node.Node at 0x2087831ec50>,
 'medical-6-S-2-R-2': <graphs.Node.Node at 0x2087831ec80>,
 'medical-6-S-2-R-3': <graphs.Node.Node at 0x2087831ecb0>,
 'medical-6-S-2-R-4': <graphs.Node.Node at 0x2087831ece0>,
 'medical-6-S-2-R-5': <graphs.Node.Node at 0x2087831ed10>,
 'medical-6-S-3': <graphs.Node.Node at 0x2087831ed40>,
 'medical-6-S-3-R-0': <graphs.Node.Node at 0x2087831ed70>,
 'medical-6-S-3-R-1': <graphs.Node.Node at 0x2087831eda0>,
 'medical-6-S-3-R-2': <graphs.Node.Node at 0x2087831edd0>,
 'medical-6-S-3-R-3': <graphs.Node.Node at 0x2087831ee00>,
 'medical-6-S-3-R-4': <graphs.Node.Node at 0x2087831ee30>,
 'medical-6-S-3-R-5': <graphs.Node.Node at 0x2087831ee60>,
 'medical-6-S-3-R-6': <graphs.Node.Node at 0x2087831ee90>,
 'medical-6-S-3-R-7': <graphs.Node.Node at 0x2087831eec0>,
 'medical-6-S-4': <graphs.Node.Node at 0x2087831eef0>,
 'medical-6-S-4-R-0': <graphs.Node.Node at 0x2087831ef20>,
 'medical-6-S-4-R-1': <graphs.Node.Node at 0x2087831ef50>,
 'medical-6-S-4-R-2': <graphs.Node.Node at 0x2087831ef80>,
 'medical-6-S-4-R-3': <graphs.Node.Node at 0x2087831efb0>,
 'medical-6-S-4-R-4': <graphs.Node.Node at 0x2087831efe0>,
 'medical-6-S-4-R-5': <graphs.Node.Node at 0x2087831f010>,
 'medical-6-S-4-R-6': <graphs.Node.Node at 0x2087831f040>,
 'medical-6-S-4-R-7': <graphs.Node.Node at 0x2087831f070>,
 'medical-6-S-4-R-8': <graphs.Node.Node at 0x2087831f0a0>,
 'medical-6-S-4-R-9': <graphs.Node.Node at 0x2087831f0d0>,
 'medical-6-S-4-R-10': <graphs.Node.Node at 0x2087831f100>,
 'medical-7-S-0': <graphs.Node.Node at 0x2087831f130>,
 'medical-7-S-0-R-0': <graphs.Node.Node at 0x2087831f160>,
 'medical-7-S-0-R-1': <graphs.Node.Node at 0x2087831f190>,
 'medical-7-S-0-R-2': <graphs.Node.Node at 0x2087831f1c0>,
 'medical-7-S-0-R-3': <graphs.Node.Node at 0x2087831f1f0>,
 'medical-7-S-0-R-4': <graphs.Node.Node at 0x2087831f220>,
 'medical-7-S-0-R-5': <graphs.Node.Node at 0x2087831f250>,
 'medical-7-S-0-R-6': <graphs.Node.Node at 0x2087831f280>,
 'medical-7-S-1': <graphs.Node.Node at 0x2087831f2b0>,